import { Kra, KraTemplate, ReviewPeriod } from '../src/types.js';

export const SEED_KRAS: Kra[] = [
  // Engineering KRAs
  {
    id: 'kra_eng_sprint',
    title: 'Sprint Velocity & Delivery Cadence',
    description: 'Achieve planned sprint commitments and ship production features within SLA.',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    category: 'Delivery & Execution',
    metricType: 'PERCENTAGE',
    targetUnit: '%',
    active: true,
    createdAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'kra_eng_quality',
    title: 'Code Quality & Reliability',
    description: 'Maintain >85% automated test coverage with zero critical P0/P1 production regressions.',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    category: 'Quality & Reliability',
    metricType: 'PERCENTAGE',
    targetUnit: '%',
    active: true,
    createdAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'kra_eng_arch',
    title: 'System Architecture & Performance',
    description: 'Optimize service latency (p99 < 150ms) and design modular scalable microservices.',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    category: 'Innovation',
    metricType: 'TARGET_NUMERIC',
    targetUnit: 'ms',
    active: true,
    createdAt: '2025-01-01T00:00:00.000Z',
  },

  // Sales KRAs
  {
    id: 'kra_sales_quota',
    title: 'Quarterly Revenue & Quota Achievement',
    description: 'Meet or exceed assigned quarterly closed-won ARR sales quota targets.',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    category: 'Delivery & Execution',
    metricType: 'PERCENTAGE',
    targetUnit: '%',
    active: true,
    createdAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'kra_sales_acquisition',
    title: 'Enterprise Logo Acquisition',
    description: 'Source, pitch, and convert new qualified enterprise customer accounts.',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    category: 'Delivery & Execution',
    metricType: 'TARGET_NUMERIC',
    targetUnit: 'accounts',
    active: true,
    createdAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'kra_sales_crm',
    title: 'CRM Pipeline Hygiene & Accuracy',
    description: 'Maintain 100% updated opportunity stages, forecasted close dates, and contact logs.',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    category: 'Quality & Reliability',
    metricType: 'PERCENTAGE',
    targetUnit: '%',
    active: true,
    createdAt: '2025-01-01T00:00:00.000Z',
  },

  // HR KRAs
  {
    id: 'kra_hr_appraisal',
    title: 'Appraisal & Performance Review Operations',
    description: 'Ensure 100% on-time submission, calibration, and letter delivery across cohorts.',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources',
    category: 'Delivery & Execution',
    metricType: 'PERCENTAGE',
    targetUnit: '%',
    active: true,
    createdAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'kra_hr_talent',
    title: 'Talent Acquisition SLA & Time-to-Hire',
    description: 'Close critical engineering, sales, and corporate vacancies within 30 days.',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources',
    category: 'Delivery & Execution',
    metricType: 'TARGET_NUMERIC',
    targetUnit: 'days',
    active: true,
    createdAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'kra_hr_retention',
    title: 'Employee Retention & eNPS Engagement',
    description: 'Drive high employee morale, quarterly townhalls, and maintain eNPS score >= 45.',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources',
    category: 'Leadership & Team',
    metricType: 'TARGET_NUMERIC',
    targetUnit: 'score',
    active: true,
    createdAt: '2025-01-01T00:00:00.000Z',
  },
];

export const SEED_KRA_TEMPLATES: KraTemplate[] = [
  {
    id: 'tmpl_eng_ic',
    name: 'Software Engineer Standard Template',
    title: 'Software Engineer Standard Template',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    designationId: 'des_eng_emp',
    designationName: 'Software Engineer',
    totalWeight: 100,
    active: true,
    items: [
      {
        id: 'ki_eng_1',
        kraId: 'kra_eng_sprint',
        kraName: 'Sprint Velocity & Delivery Cadence',
        title: 'Sprint Velocity & Delivery Cadence',
        description: 'Achieve planned sprint commitments and ship production features within SLA.',
        target: '95% planned deliverables',
        measurementCriteria: '1: <80% | 3: 90% | 5: >95%',
        weight: 40,
      },
      {
        id: 'ki_eng_2',
        kraId: 'kra_eng_quality',
        kraName: 'Code Quality & Reliability',
        title: 'Code Quality & Reliability',
        description: 'Maintain >85% automated test coverage with zero critical P0/P1 regressions.',
        target: 'Zero P0 regressions, 85% test coverage',
        measurementCriteria: '1: P0 bugs | 3: 80% coverage | 5: 90%+ coverage',
        weight: 35,
      },
      {
        id: 'ki_eng_3',
        kraId: 'kra_eng_arch',
        kraName: 'System Architecture & Performance',
        title: 'System Architecture & Performance',
        description: 'Optimize service latency and design scalable microservices.',
        target: 'p99 latency < 150ms',
        measurementCriteria: '1: >300ms | 3: 150-200ms | 5: <150ms',
        weight: 25,
      },
    ],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'tmpl_sales_ic',
    name: 'Sales Representative Standard Template',
    title: 'Sales Representative Standard Template',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    designationId: 'des_sales_emp',
    designationName: 'Sales Representative',
    totalWeight: 100,
    active: true,
    items: [
      {
        id: 'ki_sales_1',
        kraId: 'kra_sales_quota',
        kraName: 'Quarterly Revenue & Quota Achievement',
        title: 'Quarterly Revenue & Quota Achievement',
        description: 'Meet or exceed assigned quarterly closed-won ARR sales quota targets.',
        target: '100% quota achieved',
        measurementCriteria: '1: <70% | 3: 100% | 5: >120%',
        weight: 50,
      },
      {
        id: 'ki_sales_2',
        kraId: 'kra_sales_acquisition',
        kraName: 'Enterprise Logo Acquisition',
        title: 'Enterprise Logo Acquisition',
        description: 'Source, pitch, and convert new qualified enterprise customer accounts.',
        target: '8 enterprise logos',
        measurementCriteria: '1: <4 | 3: 8 | 5: >10',
        weight: 30,
      },
      {
        id: 'ki_sales_3',
        kraId: 'kra_sales_crm',
        kraName: 'CRM Pipeline Hygiene & Accuracy',
        title: 'CRM Pipeline Hygiene & Accuracy',
        description: 'Maintain 100% updated opportunity stages, close dates, and contact logs.',
        target: '95% hygiene score',
        measurementCriteria: '1: <80% | 3: 95% | 5: 100%',
        weight: 20,
      },
    ],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'tmpl_hr_ic',
    name: 'HR Specialist Standard Template',
    title: 'HR Specialist Standard Template',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources',
    designationId: 'des_hr_emp',
    designationName: 'HR Specialist',
    totalWeight: 100,
    active: true,
    items: [
      {
        id: 'ki_hr_1',
        kraId: 'kra_hr_appraisal',
        kraName: 'Appraisal & Performance Review Operations',
        title: 'Appraisal & Performance Review Operations',
        description: 'Ensure 100% on-time submission, calibration, and letter delivery.',
        target: '100% on-time execution',
        measurementCriteria: '1: <85% | 3: 95% | 5: 100%',
        weight: 40,
      },
      {
        id: 'ki_hr_2',
        kraId: 'kra_hr_talent',
        kraName: 'Talent Acquisition SLA & Time-to-Hire',
        title: 'Talent Acquisition SLA & Time-to-Hire',
        description: 'Close critical engineering, sales, and corporate vacancies within 30 days.',
        target: '< 30 days time-to-hire',
        measurementCriteria: '1: >45d | 3: 30d | 5: <22d',
        weight: 35,
      },
      {
        id: 'ki_hr_3',
        kraId: 'kra_hr_retention',
        kraName: 'Employee Retention & eNPS Engagement',
        title: 'Employee Retention & eNPS Engagement',
        description: 'Drive high employee morale and maintain eNPS score >= 45.',
        target: 'eNPS >= 45',
        measurementCriteria: '1: <25 | 3: 45 | 5: >55',
        weight: 25,
      },
    ],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
];

export const SEED_REVIEW_PERIODS: ReviewPeriod[] = [
  {
    id: 'period_2025_q3',
    name: '2025-Q3 (Jul - Sep)',
    quarter: 3,
    year: 2025,
    startDate: '2025-07-01',
    endDate: '2025-09-30',
    dueDate: '2025-10-15',
    status: 'LOCKED',
  },
  {
    id: 'period_2025_q4',
    name: '2025-Q4 (Oct - Dec)',
    quarter: 4,
    year: 2025,
    startDate: '2025-10-01',
    endDate: '2025-12-31',
    dueDate: '2026-01-15',
    status: 'LOCKED',
  },
  {
    id: 'period_2026_q1',
    name: '2026-Q1 (Jan - Mar)',
    quarter: 1,
    year: 2026,
    startDate: '2026-01-01',
    endDate: '2026-03-31',
    dueDate: '2026-04-15',
    status: 'ACTIVE',
  },
  {
    id: 'period_2026_q2',
    name: '2026-Q2 (Apr - Jun)',
    quarter: 2,
    year: 2026,
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    dueDate: '2026-07-15',
    status: 'UPCOMING',
  },
];
