import { EmployeeReview } from '../src/types.js';

export const SEED_EMPLOYEE_REVIEWS: EmployeeReview[] = [
  // --- Arjun Singhania (emp_admin - EMP-001) ---
  {
    id: 'rev_2025_q4_emp_admin',
    employeeId: 'emp_admin',
    employeeCode: 'EMP-001',
    employeeName: 'Arjun Singhania',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources & Talent',
    designationName: 'HR Business Partner',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleColor: '#1e3a8a',
    isAppraisalMonthDue: false,
    managerId: 'emp_hr_lead',
    managerName: 'Pooja Iyer',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'MANAGER_PENDING',
    selfScore: 4.20,
    isSelfSubmitted: true,
    finalScore: 4.25,
    kraSnapshot: [
      {
        id: 'snap_adm_q4_1',
        kraId: 'kra_hr_appraisal_ops',
        kraName: 'Appraisal & Quarterly Review Execution',
        title: 'Appraisal & Quarterly Review Execution',
        targetSnapshot: '100% on-time execution of review cohorts',
        measurementCriteria: '1: <80% | 3: 95-100% | 5: 100% on-time',
        weight: 40,
        achievement: 'Completed Q4 review launches with zero escalations',
        rating: 4,
        comments: 'High operational precision.',
      },
      {
        id: 'snap_adm_q4_2',
        kraId: 'kra_hr_talent_acq',
        kraName: 'Talent Acquisition & Time-to-Fill',
        title: 'Talent Acquisition & Time-to-Fill',
        targetSnapshot: 'Average time-to-hire < 30 days',
        measurementCriteria: '1: >45 days | 3: 25-30 days | 5: <20 days',
        weight: 35,
        achievement: 'Maintained 26 days average SLA for business roles',
        rating: 4,
        comments: 'Strong pipeline management with hiring managers.',
      },
      {
        id: 'snap_adm_q4_3',
        kraId: 'kra_hr_engagement',
        kraName: 'Employee Engagement & Retention',
        title: 'Employee Engagement & Retention',
        targetSnapshot: 'eNPS ≥ +45, attrition rate < 8%',
        measurementCriteria: '1: <20 | 3: 40-45 | 5: >55',
        weight: 25,
        achievement: 'Led successful year-end rewards & recognition program',
        rating: 5,
        comments: 'Outstanding employee feedback received.',
      },
    ],
    strengths: 'Rigorous process adherence and clear stakeholder communication.',
    improvements: 'Automate onboarding documentation checks.',
    managerOverallComments: 'Strong quarterly execution across all HR operational goals.',
    isClosed: false,
    completedAt: '2026-01-10T11:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
    updatedAt: '2026-01-10T11:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_emp_admin',
    employeeId: 'emp_admin',
    employeeCode: 'EMP-001',
    employeeName: 'Arjun Singhania',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources & Talent',
    designationName: 'HR Business Partner',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleColor: '#1e3a8a',
    isAppraisalMonthDue: true,
    managerId: 'emp_hr_lead',
    managerName: 'Pooja Iyer',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'MANAGER_PENDING',
    selfScore: 4.30,
    isSelfSubmitted: true,
    finalScore: 4.30,
    kraSnapshot: [
      {
        id: 'snap_adm_q1_1',
        kraId: 'kra_hr_appraisal_ops',
        kraName: 'Appraisal & Quarterly Review Execution',
        title: 'Appraisal & Quarterly Review Execution',
        targetSnapshot: '100% on-time execution of review cohorts',
        measurementCriteria: '1: <80% | 3: 95-100% | 5: 100% on-time',
        weight: 40,
        achievement: 'Closed Cycle A annual appraisal letters smoothly',
        rating: 4,
        comments: 'Executed seamless review cadence.',
      },
      {
        id: 'snap_adm_q1_2',
        kraId: 'kra_hr_talent_acq',
        kraName: 'Talent Acquisition & Time-to-Fill',
        title: 'Talent Acquisition & Time-to-Fill',
        targetSnapshot: 'Average time-to-hire < 30 days',
        measurementCriteria: '1: >45 days | 3: 25-30 days | 5: <20 days',
        weight: 35,
        achievement: 'Filled 4 critical leadership positions',
        rating: 5,
        comments: 'Excellent headhunting and offer conversion rate.',
      },
      {
        id: 'snap_adm_q1_3',
        kraId: 'kra_hr_engagement',
        kraName: 'Employee Engagement & Retention',
        title: 'Employee Engagement & Retention',
        targetSnapshot: 'eNPS ≥ +45, attrition rate < 8%',
        measurementCriteria: '1: <20 | 3: 40-45 | 5: >55',
        weight: 25,
        achievement: 'Executed Q1 pulse survey with 92% response rate',
        rating: 4,
        comments: 'Actionable analytics delivered to leadership.',
      },
    ],
    strengths: 'Executive recruitment speed and reliable HR compliance.',
    improvements: 'Enhance self-service workflow automation for managers.',
    managerOverallComments: 'Consistently exceeding expectations.',
    isClosed: false,
    completedAt: '2026-04-12T10:00:00.000Z',
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-04-12T10:00:00.000Z',
  },
  {
    id: 'rev_2026_q2_emp_admin',
    employeeId: 'emp_admin',
    employeeCode: 'EMP-001',
    employeeName: 'Arjun Singhania',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources & Talent',
    designationName: 'HR Business Partner',
    reviewPeriodId: 'period_2026_q2',
    reviewPeriodName: '2026-Q2 (Apr - Jun)',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleColor: '#1e3a8a',
    isAppraisalMonthDue: false,
    managerId: 'emp_hr_lead',
    managerName: 'Pooja Iyer',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'MANAGER_PENDING',
    selfScore: 4.40,
    isSelfSubmitted: true,
    finalScore: 4.35,
    kraSnapshot: [
      {
        id: 'snap_adm_q2_1',
        kraId: 'kra_hr_appraisal_ops',
        kraName: 'Appraisal & Quarterly Review Execution',
        title: 'Appraisal & Quarterly Review Execution',
        targetSnapshot: '100% on-time execution of review cohorts',
        measurementCriteria: '1: <80% | 3: 95-100% | 5: 100% on-time',
        weight: 40,
        achievement: 'Coordinated Cycle C & D mid-year appraisals',
        rating: 5,
        comments: 'Zero calibration disputes reported.',
      },
      {
        id: 'snap_adm_q2_2',
        kraId: 'kra_hr_talent_acq',
        kraName: 'Talent Acquisition & Time-to-Fill',
        title: 'Talent Acquisition & Time-to-Fill',
        targetSnapshot: 'Average time-to-hire < 30 days',
        measurementCriteria: '1: >45 days | 3: 25-30 days | 5: <20 days',
        weight: 35,
        achievement: 'Average time-to-hire reduced to 23 days',
        rating: 4,
        comments: 'Streamlined interview loops.',
      },
      {
        id: 'snap_adm_q2_3',
        kraId: 'kra_hr_engagement',
        kraName: 'Employee Engagement & Retention',
        title: 'Employee Engagement & Retention',
        targetSnapshot: 'eNPS ≥ +45, attrition rate < 8%',
        measurementCriteria: '1: <20 | 3: 40-45 | 5: >55',
        weight: 25,
        achievement: 'Organized tech symposium and wellness drive',
        rating: 4,
        comments: 'High employee participation.',
      },
    ],
    strengths: 'Talent development initiative and cross-departmental alignment.',
    improvements: 'Delegate more routine ticket routing.',
    managerOverallComments: 'Excellent performance in mid-year operations.',
    isClosed: false,
    completedAt: '2026-07-14T15:00:00.000Z',
    createdAt: '2026-04-01T09:00:00.000Z',
    updatedAt: '2026-07-14T15:00:00.000Z',
  },
  {
    id: 'rev_2026_q3_emp_admin',
    employeeId: 'emp_admin',
    employeeCode: 'EMP-001',
    employeeName: 'Arjun Singhania',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources & Talent',
    designationName: 'HR Business Partner',
    reviewPeriodId: 'period_2026_q3',
    reviewPeriodName: '2026-Q3 (Jul - Sep)',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleColor: '#1e3a8a',
    isAppraisalMonthDue: false,
    managerId: 'emp_hr_lead',
    managerName: 'Pooja Iyer',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'MANAGER_PENDING',
    selfScore: 4.30,
    isSelfSubmitted: true,
    finalScore: 4.30,
    kraSnapshot: [
      {
        id: 'snap_adm_q3_1',
        kraId: 'kra_hr_appraisal_ops',
        kraName: 'Appraisal & Quarterly Review Execution',
        title: 'Appraisal & Quarterly Review Execution',
        targetSnapshot: '100% on-time execution of review cohorts',
        measurementCriteria: '1: <80% | 3: 95-100% | 5: 100% on-time',
        weight: 40,
        achievement: 'Prepared Cycle E & F review workflows on schedule',
        rating: 4,
        comments: 'Active tracking of all pending manager reviews.',
      },
      {
        id: 'snap_adm_q3_2',
        kraId: 'kra_hr_talent_acq',
        kraName: 'Talent Acquisition & Time-to-Fill',
        title: 'Talent Acquisition & Time-to-Fill',
        targetSnapshot: 'Average time-to-hire < 30 days',
        measurementCriteria: '1: >45 days | 3: 25-30 days | 5: <20 days',
        weight: 35,
        achievement: 'Closed 8 specialized software engineering requisitions',
        rating: 5,
        comments: 'Outstanding candidate experience ratings.',
      },
      {
        id: 'snap_adm_q3_3',
        kraId: 'kra_hr_engagement',
        kraName: 'Employee Engagement & Retention',
        title: 'Employee Engagement & Retention',
        targetSnapshot: 'eNPS ≥ +45, attrition rate < 8%',
        measurementCriteria: '1: <20 | 3: 40-45 | 5: >55',
        weight: 25,
        achievement: 'Q3 eNPS score reached +51 with strong retention in engineering',
        rating: 4,
        comments: 'Proactive retention interviews conducted.',
      },
    ],
    strengths: 'Analytical capability, candidate experience focus, and HR operations leadership.',
    improvements: 'Continue optimizing automated appraisal reminders.',
    managerOverallComments: 'Consistently high-calibre business partnering.',
    isClosed: false,
    completedAt: '2026-09-01T16:00:00.000Z',
    createdAt: '2026-07-01T09:00:00.000Z',
    updatedAt: '2026-09-01T16:00:00.000Z',
  },

  // --- Pooja Iyer (emp_hr_lead - EMP-002) ---
  {
    id: 'rev_2025_q4_emp_hr_lead',
    employeeId: 'emp_hr_lead',
    employeeCode: 'EMP-002',
    employeeName: 'Pooja Iyer',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources & Talent',
    designationName: 'Lead HR Business Partner',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_b',
    cycleCode: 'B',
    cycleColor: '#0f766e',
    isAppraisalMonthDue: false,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'MANAGER_PENDING',
    selfScore: 4.50,
    isSelfSubmitted: true,
    finalScore: 4.45,
    kraSnapshot: [
      {
        id: 'snap_hrl_q4_1',
        kraId: 'kra_hr_appraisal_ops',
        kraName: 'Appraisal & Quarterly Review Execution',
        title: 'Appraisal & Quarterly Review Execution',
        targetSnapshot: '100% on-time execution of review cohorts',
        measurementCriteria: '1: <80% | 3: 95-100% | 5: 100% on-time',
        weight: 40,
        achievement: 'Launched multi-cycle appraisal framework seamlessly',
        rating: 5,
        comments: 'Strategic alignment across executive leadership.',
      },
      {
        id: 'snap_hrl_q4_2',
        kraId: 'kra_hr_talent_acq',
        kraName: 'Talent Acquisition & Time-to-Fill',
        title: 'Talent Acquisition & Time-to-Fill',
        targetSnapshot: 'Average time-to-hire < 30 days',
        measurementCriteria: '1: >45 days | 3: 25-30 days | 5: <20 days',
        weight: 35,
        achievement: 'Led executive hiring across Engineering and Sales',
        rating: 4,
        comments: 'Top tier talent hired.',
      },
      {
        id: 'snap_hrl_q4_3',
        kraId: 'kra_hr_engagement',
        kraName: 'Employee Engagement & Retention',
        title: 'Employee Engagement & Retention',
        targetSnapshot: 'eNPS ≥ +45, attrition rate < 8%',
        measurementCriteria: '1: <20 | 3: 40-45 | 5: >55',
        weight: 25,
        achievement: 'Voluntary attrition reduced to 5.8% annually',
        rating: 5,
        comments: 'Stellar retention strategies.',
      },
    ],
    strengths: 'People leadership, organization design, and strategic policy design.',
    improvements: 'Scale HR analytics dashboard reporting.',
    managerOverallComments: 'Exceptional HR leadership and execution.',
    isClosed: false,
    completedAt: '2026-01-12T14:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
    updatedAt: '2026-01-12T14:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_emp_hr_lead',
    employeeId: 'emp_hr_lead',
    employeeCode: 'EMP-002',
    employeeName: 'Pooja Iyer',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources & Talent',
    designationName: 'Lead HR Business Partner',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_b',
    cycleCode: 'B',
    cycleColor: '#0f766e',
    isAppraisalMonthDue: true,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'MANAGER_PENDING',
    selfScore: 4.50,
    isSelfSubmitted: true,
    finalScore: 4.50,
    kraSnapshot: [
      {
        id: 'snap_hrl_q1_1',
        kraId: 'kra_hr_appraisal_ops',
        kraName: 'Appraisal & Quarterly Review Execution',
        title: 'Appraisal & Quarterly Review Execution',
        targetSnapshot: '100% on-time execution of review cohorts',
        measurementCriteria: '1: <80% | 3: 95-100% | 5: 100% on-time',
        weight: 40,
        achievement: 'Closed Cycle B appraisals and compensation adjustments',
        rating: 5,
        comments: '100% on-time closure.',
      },
      {
        id: 'snap_hrl_q1_2',
        kraId: 'kra_hr_talent_acq',
        kraName: 'Talent Acquisition & Time-to-Fill',
        title: 'Talent Acquisition & Time-to-Fill',
        targetSnapshot: 'Average time-to-hire < 30 days',
        measurementCriteria: '1: >45 days | 3: 25-30 days | 5: <20 days',
        weight: 35,
        achievement: 'Average time-to-hire kept at 24 days',
        rating: 4,
        comments: 'Fast onboarding turnaround.',
      },
      {
        id: 'snap_hrl_q1_3',
        kraId: 'kra_hr_engagement',
        kraName: 'Employee Engagement & Retention',
        title: 'Employee Engagement & Retention',
        targetSnapshot: 'eNPS ≥ +45, attrition rate < 8%',
        measurementCriteria: '1: <20 | 3: 40-45 | 5: >55',
        weight: 25,
        achievement: 'Launched mental health and mentorship programs',
        rating: 5,
        comments: 'Highly praised by employees.',
      },
    ],
    strengths: 'Empathetic leadership and structured organizational frameworks.',
    improvements: 'Continue refining succession planning.',
    managerOverallComments: 'Consistently sets a benchmark for operational excellence.',
    isClosed: false,
    completedAt: '2026-04-10T12:00:00.000Z',
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-04-10T12:00:00.000Z',
  },
  {
    id: 'rev_2026_q2_emp_hr_lead',
    employeeId: 'emp_hr_lead',
    employeeCode: 'EMP-002',
    employeeName: 'Pooja Iyer',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources & Talent',
    designationName: 'Lead HR Business Partner',
    reviewPeriodId: 'period_2026_q2',
    reviewPeriodName: '2026-Q2 (Apr - Jun)',
    cycleId: 'cycle_b',
    cycleCode: 'B',
    cycleColor: '#0f766e',
    isAppraisalMonthDue: false,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'MANAGER_PENDING',
    selfScore: 4.55,
    isSelfSubmitted: true,
    finalScore: 4.50,
    kraSnapshot: [
      {
        id: 'snap_hrl_q2_1',
        kraId: 'kra_hr_appraisal_ops',
        kraName: 'Appraisal & Quarterly Review Execution',
        title: 'Appraisal & Quarterly Review Execution',
        targetSnapshot: '100% on-time execution of review cohorts',
        measurementCriteria: '1: <80% | 3: 95-100% | 5: 100% on-time',
        weight: 40,
        achievement: 'Managed Cycle C & D appraisal calibrations flawlessly',
        rating: 5,
        comments: 'Accurate budget adherence.',
      },
      {
        id: 'snap_hrl_q2_2',
        kraId: 'kra_hr_talent_acq',
        kraName: 'Talent Acquisition & Time-to-Fill',
        title: 'Talent Acquisition & Time-to-Fill',
        targetSnapshot: 'Average time-to-hire < 30 days',
        measurementCriteria: '1: >45 days | 3: 25-30 days | 5: <20 days',
        weight: 35,
        achievement: 'Expanded campus recruitment and intern hiring',
        rating: 4,
        comments: 'Great pipeline generation.',
      },
      {
        id: 'snap_hrl_q2_3',
        kraId: 'kra_hr_engagement',
        kraName: 'Employee Engagement & Retention',
        title: 'Employee Engagement & Retention',
        targetSnapshot: 'eNPS ≥ +45, attrition rate < 8%',
        measurementCriteria: '1: <20 | 3: 40-45 | 5: >55',
        weight: 25,
        achievement: 'Mid-year eNPS score hit +54',
        rating: 5,
        comments: 'Very strong culture building.',
      },
    ],
    strengths: 'Cross-functional diplomacy and high talent retention.',
    improvements: 'None noted.',
    managerOverallComments: 'Outstanding performance throughout the quarter.',
    isClosed: false,
    completedAt: '2026-07-15T16:00:00.000Z',
    createdAt: '2026-04-01T09:00:00.000Z',
    updatedAt: '2026-07-15T16:00:00.000Z',
  },
  {
    id: 'rev_2026_q3_emp_hr_lead',
    employeeId: 'emp_hr_lead',
    employeeCode: 'EMP-002',
    employeeName: 'Pooja Iyer',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources & Talent',
    designationName: 'Lead HR Business Partner',
    reviewPeriodId: 'period_2026_q3',
    reviewPeriodName: '2026-Q3 (Jul - Sep)',
    cycleId: 'cycle_b',
    cycleCode: 'B',
    cycleColor: '#0f766e',
    isAppraisalMonthDue: false,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'MANAGER_PENDING',
    selfScore: 4.60,
    isSelfSubmitted: true,
    finalScore: 4.55,
    kraSnapshot: [
      {
        id: 'snap_hrl_q3_1',
        kraId: 'kra_hr_appraisal_ops',
        kraName: 'Appraisal & Quarterly Review Execution',
        title: 'Appraisal & Quarterly Review Execution',
        targetSnapshot: '100% on-time execution of review cohorts',
        measurementCriteria: '1: <80% | 3: 95-100% | 5: 100% on-time',
        weight: 40,
        achievement: 'Supervised Cycle E & F review workflows and calibration panels',
        rating: 5,
        comments: 'Outstanding leadership of review operations.',
      },
      {
        id: 'snap_hrl_q3_2',
        kraId: 'kra_hr_talent_acq',
        kraName: 'Talent Acquisition & Time-to-Fill',
        title: 'Talent Acquisition & Time-to-Fill',
        targetSnapshot: 'Average time-to-hire < 30 days',
        measurementCriteria: '1: >45 days | 3: 25-30 days | 5: <20 days',
        weight: 35,
        achievement: 'Time to hire reduced to 21 days for technical tracks',
        rating: 4,
        comments: 'High hiring manager satisfaction.',
      },
      {
        id: 'snap_hrl_q3_3',
        kraId: 'kra_hr_engagement',
        kraName: 'Employee Engagement & Retention',
        title: 'Employee Engagement & Retention',
        targetSnapshot: 'eNPS ≥ +45, attrition rate < 8%',
        measurementCriteria: '1: <20 | 3: 40-45 | 5: >55',
        weight: 25,
        achievement: 'Conducted culture survey and DEI training sessions',
        rating: 5,
        comments: 'Highly engaging execution.',
      },
    ],
    strengths: 'Executive collaboration, talent planning, and organizational excellence.',
    improvements: 'None.',
    managerOverallComments: 'Exceptional pillar of company culture and leadership.',
    isClosed: false,
    completedAt: '2026-08-20T17:00:00.000Z',
    createdAt: '2026-07-01T09:00:00.000Z',
    updatedAt: '2026-08-20T17:00:00.000Z',
  },

  // --- Rohan Deshmukh (emp_mgr_eng - EMP-101) ---
  {
    id: 'rev_2025_q4_emp_mgr_eng',
    employeeId: 'emp_mgr_eng',
    employeeCode: 'EMP-101',
    employeeName: 'Rohan Deshmukh',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'Engineering Manager',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_c',
    cycleCode: 'C',
    cycleColor: '#15803d',
    isAppraisalMonthDue: false,
    managerId: 'emp_hod_eng',
    managerName: 'Vikram Mehta',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'MANAGER_PENDING',
    selfScore: 4.40,
    isSelfSubmitted: true,
    finalScore: 4.40,
    kraSnapshot: [
      {
        id: 'snap_mgr_q4_1',
        kraId: 'kra_code_delivery',
        kraName: 'Sprint Feature Delivery & Execution',
        title: 'Sprint Feature Delivery & Execution',
        targetSnapshot: '≥ 90% velocity completed, zero Sev-1 bugs in prod',
        measurementCriteria: '1: <70% | 3: 85-90% | 5: >95%',
        weight: 35,
        achievement: '96% of planned sprint deliverables shipped on time',
        rating: 5,
        comments: 'High engineering throughput.',
      },
      {
        id: 'snap_mgr_q4_2',
        kraId: 'kra_sys_arch',
        kraName: 'System Architecture & Maintainability',
        title: 'System Architecture & Maintainability',
        targetSnapshot: 'P95 response times < 200ms, test coverage ≥ 85%',
        measurementCriteria: '1: Latency regression | 3: SLA met | 5: Significant optimization',
        weight: 30,
        achievement: 'Supervised migration to containerized microservices',
        rating: 4,
        comments: 'Reliable and robust deployment pipelines.',
      },
      {
        id: 'snap_mgr_q4_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Production Reliability & Incident SLA',
        title: 'Production Reliability & Incident SLA',
        targetSnapshot: 'Zero Sev-1 outages, MTTR < 15 mins',
        measurementCriteria: '1: Frequent downtime | 3: Clean SLA | 5: 99.99% uptime',
        weight: 35,
        achievement: '99.98% service uptime achieved across core services',
        rating: 4,
        comments: 'Fast on-call response cadence.',
      },
    ],
    strengths: 'Engineering roadmap execution and team mentorship.',
    improvements: 'Increase technical writing and documentation.',
    managerOverallComments: 'Solid engineering management throughout Q4.',
    isClosed: false,
    completedAt: '2026-01-14T11:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
    updatedAt: '2026-01-14T11:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_emp_mgr_eng',
    employeeId: 'emp_mgr_eng',
    employeeCode: 'EMP-101',
    employeeName: 'Rohan Deshmukh',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'Engineering Manager',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_c',
    cycleCode: 'C',
    cycleColor: '#15803d',
    isAppraisalMonthDue: false,
    managerId: 'emp_hod_eng',
    managerName: 'Vikram Mehta',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'MANAGER_PENDING',
    selfScore: 4.50,
    isSelfSubmitted: true,
    finalScore: 4.50,
    kraSnapshot: [
      {
        id: 'snap_mgr_q1_1',
        kraId: 'kra_code_delivery',
        kraName: 'Sprint Feature Delivery & Execution',
        title: 'Sprint Feature Delivery & Execution',
        targetSnapshot: '≥ 90% velocity completed, zero Sev-1 bugs in prod',
        measurementCriteria: '1: <70% | 3: 85-90% | 5: >95%',
        weight: 35,
        achievement: 'Delivered customer billing portal overhaul',
        rating: 5,
        comments: 'Pristine execution.',
      },
      {
        id: 'snap_mgr_q1_2',
        kraId: 'kra_sys_arch',
        kraName: 'System Architecture & Maintainability',
        title: 'System Architecture & Maintainability',
        targetSnapshot: 'P95 response times < 200ms, test coverage ≥ 85%',
        measurementCriteria: '1: Latency regression | 3: SLA met | 5: Significant optimization',
        weight: 30,
        achievement: 'Refactored auth token validation layer',
        rating: 4,
        comments: 'Clean API boundaries.',
      },
      {
        id: 'snap_mgr_q1_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Production Reliability & Incident SLA',
        title: 'Production Reliability & Incident SLA',
        targetSnapshot: 'Zero Sev-1 outages, MTTR < 15 mins',
        measurementCriteria: '1: Frequent downtime | 3: Clean SLA | 5: 99.99% uptime',
        weight: 35,
        achievement: 'Maintained 100% on-call rotation coverage',
        rating: 5,
        comments: 'Exemplary on-call hygiene.',
      },
    ],
    strengths: 'Technical leadership and cross-functional pod coordination.',
    improvements: 'Continue training junior engineers.',
    managerOverallComments: 'Consistently high technical quality.',
    isClosed: false,
    completedAt: '2026-04-12T15:00:00.000Z',
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-04-12T15:00:00.000Z',
  },
  {
    id: 'rev_2026_q2_emp_mgr_eng',
    employeeId: 'emp_mgr_eng',
    employeeCode: 'EMP-101',
    employeeName: 'Rohan Deshmukh',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'Engineering Manager',
    reviewPeriodId: 'period_2026_q2',
    reviewPeriodName: '2026-Q2 (Apr - Jun)',
    cycleId: 'cycle_c',
    cycleCode: 'C',
    cycleColor: '#15803d',
    isAppraisalMonthDue: true,
    managerId: 'emp_hod_eng',
    managerName: 'Vikram Mehta',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.45,
    isSelfSubmitted: true,
    finalScore: 4.45,
    kraSnapshot: [
      {
        id: 'snap_mgr_q2_1',
        kraId: 'kra_code_delivery',
        kraName: 'Sprint Feature Delivery & Execution',
        title: 'Sprint Feature Delivery & Execution',
        targetSnapshot: '≥ 90% velocity completed, zero Sev-1 bugs in prod',
        measurementCriteria: '1: <70% | 3: 85-90% | 5: >95%',
        weight: 35,
        achievement: 'Completed Cycle C appraisal reviews for direct reports',
        rating: 4,
        comments: 'On-time reviews submitted.',
      },
      {
        id: 'snap_mgr_q2_2',
        kraId: 'kra_sys_arch',
        kraName: 'System Architecture & Maintainability',
        title: 'System Architecture & Maintainability',
        targetSnapshot: 'P95 response times < 200ms, test coverage ≥ 85%',
        measurementCriteria: '1: Latency regression | 3: SLA met | 5: Significant optimization',
        weight: 30,
        achievement: 'P95 latency dropped by 22% on read paths',
        rating: 5,
        comments: 'High performance gain.',
      },
      {
        id: 'snap_mgr_q2_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Production Reliability & Incident SLA',
        title: 'Production Reliability & Incident SLA',
        targetSnapshot: 'Zero Sev-1 outages, MTTR < 15 mins',
        measurementCriteria: '1: Frequent downtime | 3: Clean SLA | 5: 99.99% uptime',
        weight: 35,
        achievement: 'Zero sev-1 incidents for 90 consecutive days',
        rating: 4,
        comments: 'Excellent stability.',
      },
    ],
    strengths: 'People leadership, systems architecture, and fast delivery cadence.',
    improvements: 'None.',
    managerOverallComments: 'Consistently strong performance.',
    isClosed: true,
    completedAt: '2026-07-16T12:00:00.000Z',
    createdAt: '2026-04-01T09:00:00.000Z',
    updatedAt: '2026-07-16T12:00:00.000Z',
  },
  {
    id: 'rev_2026_q3_emp_mgr_eng',
    employeeId: 'emp_mgr_eng',
    employeeCode: 'EMP-101',
    employeeName: 'Rohan Deshmukh',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'Engineering Manager',
    reviewPeriodId: 'period_2026_q3',
    reviewPeriodName: '2026-Q3 (Jul - Sep)',
    cycleId: 'cycle_c',
    cycleCode: 'C',
    cycleColor: '#15803d',
    isAppraisalMonthDue: false,
    managerId: 'emp_hod_eng',
    managerName: 'Vikram Mehta',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.50,
    isSelfSubmitted: true,
    finalScore: 4.45,
    kraSnapshot: [
      {
        id: 'snap_mgr_q3_1',
        kraId: 'kra_code_delivery',
        kraName: 'Sprint Feature Delivery & Execution',
        title: 'Sprint Feature Delivery & Execution',
        targetSnapshot: '≥ 90% velocity completed, zero Sev-1 bugs in prod',
        measurementCriteria: '1: <70% | 3: 85-90% | 5: >95%',
        weight: 35,
        achievement: 'Guided release of real-time appraisal notifications and WebSocket sync',
        rating: 5,
        comments: 'High quality software delivered.',
      },
      {
        id: 'snap_mgr_q3_2',
        kraId: 'kra_sys_arch',
        kraName: 'System Architecture & Maintainability',
        title: 'System Architecture & Maintainability',
        targetSnapshot: 'P95 response times < 200ms, test coverage ≥ 85%',
        measurementCriteria: '1: Latency regression | 3: SLA met | 5: Significant optimization',
        weight: 30,
        achievement: 'Maintained 88% unit test coverage across codebases',
        rating: 4,
        comments: 'High rigor in testing.',
      },
      {
        id: 'snap_mgr_q3_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Production Reliability & Incident SLA',
        title: 'Production Reliability & Incident SLA',
        targetSnapshot: 'Zero Sev-1 outages, MTTR < 15 mins',
        measurementCriteria: '1: Frequent downtime | 3: Clean SLA | 5: 99.99% uptime',
        weight: 35,
        achievement: 'Zero production downtime reported in Q3',
        rating: 4,
        comments: 'High availability maintained.',
      },
    ],
    strengths: 'Engineering management, architectural vision, and team scaling.',
    improvements: 'Continue developing next generation tech leads.',
    managerOverallComments: 'High trust leader and exemplary manager.',
    isClosed: true,
    completedAt: '2026-09-01T14:00:00.000Z',
    createdAt: '2026-07-01T09:00:00.000Z',
    updatedAt: '2026-09-01T14:00:00.000Z',
  },

  // --- Vikram Mehta (emp_hod_eng - EMP-100) ---
  {
    id: 'rev_2025_q4_emp_hod_eng',
    employeeId: 'emp_hod_eng',
    employeeCode: 'EMP-100',
    employeeName: 'Vikram Mehta',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'VP of Engineering (HOD)',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_d',
    cycleCode: 'D',
    cycleColor: '#7e22ce',
    isAppraisalMonthDue: false,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.60,
    isSelfSubmitted: true,
    finalScore: 4.60,
    kraSnapshot: [
      {
        id: 'snap_hod_q4_1',
        kraId: 'kra_code_delivery',
        kraName: 'Departmental Roadmap & Delivery',
        title: 'Departmental Roadmap & Delivery',
        targetSnapshot: '100% strategic initiatives delivered within budget',
        measurementCriteria: '1: <80% | 3: 95% | 5: 100% on schedule',
        weight: 40,
        achievement: 'Shipped Q4 company-wide tech milestones on budget',
        rating: 5,
        comments: 'Flawless strategic execution.',
      },
      {
        id: 'snap_hod_q4_2',
        kraId: 'kra_sys_arch',
        kraName: 'Engineering Excellence & Infrastructure',
        title: 'Engineering Excellence & Infrastructure',
        targetSnapshot: 'Zero major security incidents, <150ms p95 latency',
        measurementCriteria: '1: Regressions | 3: Clean SLA | 5: Industry leading tech stack',
        weight: 35,
        achievement: 'Completed SOC2 certification readiness with 0 blockers',
        rating: 5,
        comments: 'Top notch security and infrastructure rigor.',
      },
      {
        id: 'snap_hod_q4_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Team Engagement & Tech Retention',
        title: 'Team Engagement & Tech Retention',
        targetSnapshot: 'Attrition < 5%, eNPS ≥ +50',
        measurementCriteria: '1: High churn | 3: Normal | 5: Stellar team retention',
        weight: 25,
        achievement: 'Retained 100% senior engineering talent',
        rating: 4,
        comments: 'Great team morale and culture.',
      },
    ],
    strengths: 'Executive tech strategy, talent development, and high reliability.',
    improvements: 'None.',
    managerOverallComments: 'Outstanding organizational leadership.',
    isClosed: true,
    completedAt: '2026-01-15T16:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
    updatedAt: '2026-01-15T16:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_emp_hod_eng',
    employeeId: 'emp_hod_eng',
    employeeCode: 'EMP-100',
    employeeName: 'Vikram Mehta',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'VP of Engineering (HOD)',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_d',
    cycleCode: 'D',
    cycleColor: '#7e22ce',
    isAppraisalMonthDue: false,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.65,
    isSelfSubmitted: true,
    finalScore: 4.65,
    kraSnapshot: [
      {
        id: 'snap_hod_q1_1',
        kraId: 'kra_code_delivery',
        kraName: 'Departmental Roadmap & Delivery',
        title: 'Departmental Roadmap & Delivery',
        targetSnapshot: '100% strategic initiatives delivered within budget',
        measurementCriteria: '1: <80% | 3: 95% | 5: 100% on schedule',
        weight: 40,
        achievement: 'Architected company data platform transformation',
        rating: 5,
        comments: 'Clear architectural roadmap.',
      },
      {
        id: 'snap_hod_q1_2',
        kraId: 'kra_sys_arch',
        kraName: 'Engineering Excellence & Infrastructure',
        title: 'Engineering Excellence & Infrastructure',
        targetSnapshot: 'Zero major security incidents, <150ms p95 latency',
        measurementCriteria: '1: Regressions | 3: Clean SLA | 5: Industry leading tech stack',
        weight: 35,
        achievement: 'Cloud infrastructure cost reduced by 18% with zero performance hit',
        rating: 5,
        comments: 'Excellent financial stewardship.',
      },
      {
        id: 'snap_hod_q1_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Team Engagement & Tech Retention',
        title: 'Team Engagement & Tech Retention',
        targetSnapshot: 'Attrition < 5%, eNPS ≥ +50',
        measurementCriteria: '1: High churn | 3: Normal | 5: Stellar team retention',
        weight: 25,
        achievement: 'Promoted 3 internal leads to management positions',
        rating: 4,
        comments: 'Strong leadership pipeline.',
      },
    ],
    strengths: 'Visionary leadership, cost optimization, and technical depth.',
    improvements: 'None.',
    managerOverallComments: 'Consistently exceptional contribution.',
    isClosed: true,
    completedAt: '2026-04-14T10:00:00.000Z',
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-04-14T10:00:00.000Z',
  },
  {
    id: 'rev_2026_q2_emp_hod_eng',
    employeeId: 'emp_hod_eng',
    employeeCode: 'EMP-100',
    employeeName: 'Vikram Mehta',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'VP of Engineering (HOD)',
    reviewPeriodId: 'period_2026_q2',
    reviewPeriodName: '2026-Q2 (Apr - Jun)',
    cycleId: 'cycle_d',
    cycleCode: 'D',
    cycleColor: '#7e22ce',
    isAppraisalMonthDue: true,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.70,
    isSelfSubmitted: true,
    finalScore: 4.70,
    kraSnapshot: [
      {
        id: 'snap_hod_q2_1',
        kraId: 'kra_code_delivery',
        kraName: 'Departmental Roadmap & Delivery',
        title: 'Departmental Roadmap & Delivery',
        targetSnapshot: '100% strategic initiatives delivered within budget',
        measurementCriteria: '1: <80% | 3: 95% | 5: 100% on schedule',
        weight: 40,
        achievement: 'Cycle D departmental appraisal calibration finalized smoothly',
        rating: 5,
        comments: 'Fair, evidence-based calibration.',
      },
      {
        id: 'snap_hod_q2_2',
        kraId: 'kra_sys_arch',
        kraName: 'Engineering Excellence & Infrastructure',
        title: 'Engineering Excellence & Infrastructure',
        targetSnapshot: 'Zero major security incidents, <150ms p95 latency',
        measurementCriteria: '1: Regressions | 3: Clean SLA | 5: Industry leading tech stack',
        weight: 35,
        achievement: 'Zero Sev-1 outages across 180 days',
        rating: 5,
        comments: 'Rock solid reliability.',
      },
      {
        id: 'snap_hod_q2_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Team Engagement & Tech Retention',
        title: 'Team Engagement & Tech Retention',
        targetSnapshot: 'Attrition < 5%, eNPS ≥ +50',
        measurementCriteria: '1: High churn | 3: Normal | 5: Stellar team retention',
        weight: 25,
        achievement: 'Engineering eNPS reached +58',
        rating: 4,
        comments: 'Exceptional team trust.',
      },
    ],
    strengths: 'Executive execution and technical excellence.',
    improvements: 'None.',
    managerOverallComments: 'Top performing department executive.',
    isClosed: true,
    completedAt: '2026-06-25T11:00:00.000Z',
    createdAt: '2026-04-01T09:00:00.000Z',
    updatedAt: '2026-06-25T11:00:00.000Z',
  },
  {
    id: 'rev_2026_q3_emp_hod_eng',
    employeeId: 'emp_hod_eng',
    employeeCode: 'EMP-100',
    employeeName: 'Vikram Mehta',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'VP of Engineering (HOD)',
    reviewPeriodId: 'period_2026_q3',
    reviewPeriodName: '2026-Q3 (Jul - Sep)',
    cycleId: 'cycle_d',
    cycleCode: 'D',
    cycleColor: '#7e22ce',
    isAppraisalMonthDue: false,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.65,
    isSelfSubmitted: true,
    finalScore: 4.65,
    kraSnapshot: [
      {
        id: 'snap_hod_q3_1',
        kraId: 'kra_code_delivery',
        kraName: 'Departmental Roadmap & Delivery',
        title: 'Departmental Roadmap & Delivery',
        targetSnapshot: '100% strategic initiatives delivered within budget',
        measurementCriteria: '1: <80% | 3: 95% | 5: 100% on schedule',
        weight: 40,
        achievement: 'Led delivery of AI and Real-time analytics capabilities',
        rating: 5,
        comments: 'Accelerated innovation cadence.',
      },
      {
        id: 'snap_hod_q3_2',
        kraId: 'kra_sys_arch',
        kraName: 'Engineering Excellence & Infrastructure',
        title: 'Engineering Excellence & Infrastructure',
        targetSnapshot: 'Zero major security incidents, <150ms p95 latency',
        measurementCriteria: '1: Regressions | 3: Clean SLA | 5: Industry leading tech stack',
        weight: 35,
        achievement: 'Automated CI/CD deployment verification across all microservices',
        rating: 5,
        comments: 'Modern automated deployment pipeline.',
      },
      {
        id: 'snap_hod_q3_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Team Engagement & Tech Retention',
        title: 'Team Engagement & Tech Retention',
        targetSnapshot: 'Attrition < 5%, eNPS ≥ +50',
        measurementCriteria: '1: High churn | 3: Normal | 5: Stellar team retention',
        weight: 25,
        achievement: 'Engineering team retention maintained at 98%',
        rating: 4,
        comments: 'High engagement and culture stability.',
      },
    ],
    strengths: 'Strategic technology transformation, executive leadership, and flawless delivery.',
    improvements: 'None.',
    managerOverallComments: 'Exemplary VP of Engineering.',
    isClosed: true,
    completedAt: '2026-09-01T15:00:00.000Z',
    createdAt: '2026-07-01T09:00:00.000Z',
    updatedAt: '2026-09-01T15:00:00.000Z',
  },

  // --- Siddharth Patel (emp_dev_1 - EMP-102) ---
  {
    id: 'rev_2025_q4_emp_dev_1',
    employeeId: 'emp_dev_1',
    employeeCode: 'EMP-102',
    employeeName: 'Siddharth Patel',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'Senior Software Engineer',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_f',
    cycleCode: 'F',
    cycleColor: '#c2410c',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_eng',
    managerName: 'Rohan Deshmukh',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.20,
    isSelfSubmitted: true,
    finalScore: 4.20,
    kraSnapshot: [
      {
        id: 'snap_dev1_q4_1',
        kraId: 'kra_code_delivery',
        kraName: 'Sprint Feature Delivery & Execution',
        title: 'Sprint Feature Delivery & Execution',
        targetSnapshot: '≥ 90% velocity completed, zero Sev-1 bugs in prod',
        measurementCriteria: '1: <70% | 3: 85-90% | 5: >95%',
        weight: 35,
        achievement: 'Delivered GraphQL gateway migration ahead of schedule',
        rating: 4,
        comments: 'High execution capability.',
      },
      {
        id: 'snap_dev1_q4_2',
        kraId: 'kra_sys_arch',
        kraName: 'System Architecture & Maintainability',
        title: 'System Architecture & Maintainability',
        targetSnapshot: 'P95 response times < 200ms, test coverage ≥ 85%',
        measurementCriteria: '1: Latency regression | 3: SLA met | 5: Significant optimization',
        weight: 30,
        achievement: 'Clean schema definition and error handling',
        rating: 4,
        comments: 'Well documented interfaces.',
      },
      {
        id: 'snap_dev1_q4_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Production Reliability & Incident SLA',
        title: 'Production Reliability & Incident SLA',
        targetSnapshot: 'Zero Sev-1 outages, MTTR < 15 mins',
        measurementCriteria: '1: Frequent downtime | 3: Clean SLA | 5: 99.99% uptime',
        weight: 35,
        achievement: 'Zero production defects in deployed gateway',
        rating: 5,
        comments: 'Excellent quality.',
      },
    ],
    strengths: 'Fast turnaround, domain expertise, and clean code.',
    improvements: 'Increase test coverage on legacy endpoints.',
    managerOverallComments: 'Strong contributor to engineering delivery.',
    isClosed: true,
    completedAt: '2026-01-10T10:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
    updatedAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_emp_dev_1',
    employeeId: 'emp_dev_1',
    employeeCode: 'EMP-102',
    employeeName: 'Siddharth Patel',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'Senior Software Engineer',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_f',
    cycleCode: 'F',
    cycleColor: '#c2410c',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_eng',
    managerName: 'Rohan Deshmukh',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.40,
    isSelfSubmitted: true,
    finalScore: 4.40,
    kraSnapshot: [
      {
        id: 'snap_dev1_q1_1',
        kraId: 'kra_code_delivery',
        kraName: 'Sprint Feature Delivery & Execution',
        title: 'Sprint Feature Delivery & Execution',
        targetSnapshot: '≥ 90% velocity completed, zero Sev-1 bugs in prod',
        measurementCriteria: '1: <70% | 3: 85-90% | 5: >95%',
        weight: 35,
        achievement: 'Optimized critical DB queries, reducing p99 latency by 45%',
        rating: 5,
        comments: 'Great performance profiling.',
      },
      {
        id: 'snap_dev1_q1_2',
        kraId: 'kra_sys_arch',
        kraName: 'System Architecture & Maintainability',
        title: 'System Architecture & Maintainability',
        targetSnapshot: 'P95 response times < 200ms, test coverage ≥ 85%',
        measurementCriteria: '1: Latency regression | 3: SLA met | 5: Significant optimization',
        weight: 30,
        achievement: 'Implemented indexing strategy and Redis caching',
        rating: 4,
        comments: 'Clean architecture.',
      },
      {
        id: 'snap_dev1_q1_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Production Reliability & Incident SLA',
        title: 'Production Reliability & Incident SLA',
        targetSnapshot: 'Zero Sev-1 outages, MTTR < 15 mins',
        measurementCriteria: '1: Frequent downtime | 3: Clean SLA | 5: 99.99% uptime',
        weight: 35,
        achievement: 'Maintained 100% SLA during traffic spikes',
        rating: 4,
        comments: 'Reliable execution.',
      },
    ],
    strengths: 'Performance optimization and query tuning.',
    improvements: 'None.',
    managerOverallComments: 'Superb technical progress.',
    isClosed: true,
    completedAt: '2026-04-11T14:00:00.000Z',
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-04-11T14:00:00.000Z',
  },
  {
    id: 'rev_2026_q2_emp_dev_1',
    employeeId: 'emp_dev_1',
    employeeCode: 'EMP-102',
    employeeName: 'Siddharth Patel',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'Senior Software Engineer',
    reviewPeriodId: 'period_2026_q2',
    reviewPeriodName: '2026-Q2 (Apr - Jun)',
    cycleId: 'cycle_f',
    cycleCode: 'F',
    cycleColor: '#c2410c',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_eng',
    managerName: 'Rohan Deshmukh',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.50,
    isSelfSubmitted: true,
    finalScore: 4.50,
    kraSnapshot: [
      {
        id: 'snap_dev1_q2_1',
        kraId: 'kra_code_delivery',
        kraName: 'Sprint Feature Delivery & Execution',
        title: 'Sprint Feature Delivery & Execution',
        targetSnapshot: '≥ 90% velocity completed, zero Sev-1 bugs in prod',
        measurementCriteria: '1: <70% | 3: 85-90% | 5: >95%',
        weight: 35,
        achievement: 'Mentored 2 junior engineers, maintained zero production incidents',
        rating: 5,
        comments: 'Stepped up as tech lead for payments pod.',
      },
      {
        id: 'snap_dev1_q2_2',
        kraId: 'kra_sys_arch',
        kraName: 'System Architecture & Maintainability',
        title: 'System Architecture & Maintainability',
        targetSnapshot: 'P95 response times < 200ms, test coverage ≥ 85%',
        measurementCriteria: '1: Latency regression | 3: SLA met | 5: Significant optimization',
        weight: 30,
        achievement: 'Authored architectural design documents for payment gateway integration',
        rating: 4,
        comments: 'High technical rigor.',
      },
      {
        id: 'snap_dev1_q2_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Production Reliability & Incident SLA',
        title: 'Production Reliability & Incident SLA',
        targetSnapshot: 'Zero Sev-1 outages, MTTR < 15 mins',
        measurementCriteria: '1: Frequent downtime | 3: Clean SLA | 5: 99.99% uptime',
        weight: 35,
        achievement: 'Payment integration delivered with 99.99% success rate',
        rating: 5,
        comments: 'Outstanding reliability.',
      },
    ],
    strengths: 'Leadership maturity, system design, and junior engineer mentoring.',
    improvements: 'None.',
    managerOverallComments: 'Demonstrating Lead Software Engineer capabilities.',
    isClosed: true,
    completedAt: '2026-07-12T16:00:00.000Z',
    createdAt: '2026-04-01T09:00:00.000Z',
    updatedAt: '2026-07-12T16:00:00.000Z',
  },
  {
    id: 'rev_2026_q3_emp_dev_1',
    employeeId: 'emp_dev_1',
    employeeCode: 'EMP-102',
    employeeName: 'Siddharth Patel',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'Senior Software Engineer',
    reviewPeriodId: 'period_2026_q3',
    reviewPeriodName: '2026-Q3 (Jul - Sep)',
    cycleId: 'cycle_f',
    cycleCode: 'F',
    cycleColor: '#c2410c',
    isAppraisalMonthDue: true,
    managerId: 'emp_mgr_eng',
    managerName: 'Rohan Deshmukh',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.40,
    isSelfSubmitted: true,
    finalScore: 4.40,
    kraSnapshot: [
      {
        id: 'snap_dev1_q3_1',
        kraId: 'kra_code_delivery',
        kraName: 'Sprint Feature Delivery & Execution',
        title: 'Sprint Feature Delivery & Execution',
        targetSnapshot: '≥ 90% velocity completed, zero Sev-1 bugs in prod',
        measurementCriteria: '1: <70% | 3: 85-90% | 5: >95%',
        weight: 35,
        achievement: 'Architected real-time WebSocket notification engine with full failover',
        rating: 5,
        comments: 'Exceptional delivery on complex distributed subsystems.',
      },
      {
        id: 'snap_dev1_q3_2',
        kraId: 'kra_sys_arch',
        kraName: 'System Architecture & Maintainability',
        title: 'System Architecture & Maintainability',
        targetSnapshot: 'P95 response times < 200ms, test coverage ≥ 85%',
        measurementCriteria: '1: Latency regression | 3: SLA met | 5: Significant optimization',
        weight: 30,
        achievement: 'Refactored backend data sync and audit logging',
        rating: 4,
        comments: 'Solid code cleanliness.',
      },
      {
        id: 'snap_dev1_q3_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Production Reliability & Incident SLA',
        title: 'Production Reliability & Incident SLA',
        targetSnapshot: 'Zero Sev-1 outages, MTTR < 15 mins',
        measurementCriteria: '1: Frequent downtime | 3: Clean SLA | 5: 99.99% uptime',
        weight: 35,
        achievement: 'Zero production defects across 6 continuous sprint releases',
        rating: 4,
        comments: 'High reliability.',
      },
    ],
    strengths: 'Architecture design, reliable feature execution, and team mentorship.',
    improvements: 'None.',
    managerOverallComments: 'Strong recommendation for Lead Software Engineer in Cycle F appraisal.',
    isClosed: true,
    completedAt: '2026-09-01T11:00:00.000Z',
    createdAt: '2026-07-01T09:00:00.000Z',
    updatedAt: '2026-09-01T11:00:00.000Z',
  },

  // --- Neha Kapoor (emp_dev_2 - EMP-103) ---
  {
    id: 'rev_2025_q3_emp_dev_2',
    employeeId: 'emp_dev_2',
    employeeCode: 'EMP-103',
    employeeName: 'Neha Kapoor',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'Software Engineer I',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_d',
    cycleCode: 'D',
    cycleColor: '#7e22ce',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_eng',
    managerName: 'Rohan Deshmukh',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.40,
    isSelfSubmitted: true,
    finalScore: 4.50,
    kraSnapshot: [
      {
        id: 'snap_dev2_q4_1',
        kraId: 'kra_code_delivery',
        kraName: 'Sprint Feature Delivery & Execution',
        title: 'Sprint Feature Delivery & Execution',
        targetSnapshot: '≥ 90% velocity completed, zero Sev-1 bugs in prod',
        measurementCriteria: '1: <70% | 3: 85-90% | 5: >95%',
        weight: 35,
        achievement: 'Built reusable component library and Tailwind design system',
        rating: 5,
        comments: 'Outstanding frontend execution.',
      },
      {
        id: 'snap_dev2_q4_2',
        kraId: 'kra_sys_arch',
        kraName: 'System Architecture & Maintainability',
        title: 'System Architecture & Maintainability',
        targetSnapshot: 'P95 response times < 200ms, test coverage ≥ 85%',
        measurementCriteria: '1: Latency regression | 3: SLA met | 5: Significant optimization',
        weight: 30,
        achievement: 'Standardized accessible form components and inputs',
        rating: 4,
        comments: 'Clean code.',
      },
      {
        id: 'snap_dev2_q4_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Production Reliability & Incident SLA',
        title: 'Production Reliability & Incident SLA',
        targetSnapshot: 'Zero Sev-1 outages, MTTR < 15 mins',
        measurementCriteria: '1: Frequent downtime | 3: Clean SLA | 5: 99.99% uptime',
        weight: 35,
        achievement: 'Zero UI regressions reported on new component rollout',
        rating: 5,
        comments: 'High visual precision.',
      },
    ],
    strengths: 'UI/UX craftsmanship, fast delivery, and component architecture.',
    improvements: 'None.',
    managerOverallComments: 'High potential software engineer.',
    isClosed: true,
    completedAt: '2026-01-12T10:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
    updatedAt: '2026-01-12T10:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_emp_dev_2',
    employeeId: 'emp_dev_2',
    employeeCode: 'EMP-103',
    employeeName: 'Neha Kapoor',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'Software Engineer I',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_d',
    cycleCode: 'D',
    cycleColor: '#7e22ce',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_eng',
    managerName: 'Rohan Deshmukh',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.60,
    isSelfSubmitted: true,
    finalScore: 4.60,
    kraSnapshot: [
      {
        id: 'snap_dev2_q1_1',
        kraId: 'kra_code_delivery',
        kraName: 'Sprint Feature Delivery & Execution',
        title: 'Sprint Feature Delivery & Execution',
        targetSnapshot: '≥ 90% velocity completed, zero Sev-1 bugs in prod',
        measurementCriteria: '1: <70% | 3: 85-90% | 5: >95%',
        weight: 35,
        achievement: 'Reduced frontend bundle size by 38% with tree-shaking',
        rating: 5,
        comments: 'Significant performance improvement.',
      },
      {
        id: 'snap_dev2_q1_2',
        kraId: 'kra_sys_arch',
        kraName: 'System Architecture & Maintainability',
        title: 'System Architecture & Maintainability',
        targetSnapshot: 'P95 response times < 200ms, test coverage ≥ 85%',
        measurementCriteria: '1: Latency regression | 3: SLA met | 5: Significant optimization',
        weight: 30,
        achievement: 'Refactored state management to lightweight stores',
        rating: 4,
        comments: 'Great architectural choices.',
      },
      {
        id: 'snap_dev2_q1_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Production Reliability & Incident SLA',
        title: 'Production Reliability & Incident SLA',
        targetSnapshot: 'Zero Sev-1 outages, MTTR < 15 mins',
        measurementCriteria: '1: Frequent downtime | 3: Clean SLA | 5: 99.99% uptime',
        weight: 35,
        achievement: 'Achieved 99.99% crash-free sessions',
        rating: 5,
        comments: 'Top notch quality.',
      },
    ],
    strengths: 'Frontend optimization, fast iteration speed, and high aesthetic sense.',
    improvements: 'Expand backend services knowledge.',
    managerOverallComments: 'Consistently exceptional work.',
    isClosed: true,
    completedAt: '2026-04-10T11:00:00.000Z',
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-04-10T11:00:00.000Z',
  },
  {
    id: 'rev_2026_q2_emp_dev_2',
    employeeId: 'emp_dev_2',
    employeeCode: 'EMP-103',
    employeeName: 'Neha Kapoor',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'Software Engineer I',
    reviewPeriodId: 'period_2026_q2',
    reviewPeriodName: '2026-Q2 (Apr - Jun)',
    cycleId: 'cycle_d',
    cycleCode: 'D',
    cycleColor: '#7e22ce',
    isAppraisalMonthDue: true,
    managerId: 'emp_mgr_eng',
    managerName: 'Rohan Deshmukh',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.70,
    isSelfSubmitted: true,
    finalScore: 4.70,
    kraSnapshot: [
      {
        id: 'snap_dev2_q2_1',
        kraId: 'kra_code_delivery',
        kraName: 'Sprint Feature Delivery & Execution',
        title: 'Sprint Feature Delivery & Execution',
        targetSnapshot: '≥ 90% velocity completed, zero Sev-1 bugs in prod',
        measurementCriteria: '1: <70% | 3: 85-90% | 5: >95%',
        weight: 35,
        achievement: 'Flawless execution of user settings redesign and accessibility overhaul',
        rating: 5,
        comments: 'Praise from product and executive teams.',
      },
      {
        id: 'snap_dev2_q2_2',
        kraId: 'kra_sys_arch',
        kraName: 'System Architecture & Maintainability',
        title: 'System Architecture & Maintainability',
        targetSnapshot: 'P95 response times < 200ms, test coverage ≥ 85%',
        measurementCriteria: '1: Latency regression | 3: SLA met | 5: Significant optimization',
        weight: 30,
        achievement: 'Completed automated E2E testing framework',
        rating: 4,
        comments: 'High testing discipline.',
      },
      {
        id: 'snap_dev2_q2_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Production Reliability & Incident SLA',
        title: 'Production Reliability & Incident SLA',
        targetSnapshot: 'Zero Sev-1 outages, MTTR < 15 mins',
        measurementCriteria: '1: Frequent downtime | 3: Clean SLA | 5: 99.99% uptime',
        weight: 35,
        achievement: 'Zero production rollbacks across entire quarter',
        rating: 5,
        comments: 'Outstanding reliability.',
      },
    ],
    strengths: 'Exemplary code quality, UI polish, and proactive collaboration.',
    improvements: 'None.',
    managerOverallComments: 'Strong recommendation for promotion to Senior Software Engineer (Cycle D appraisal locked).',
    isClosed: true,
    completedAt: '2026-06-15T09:00:00.000Z',
    createdAt: '2026-04-01T09:00:00.000Z',
    updatedAt: '2026-06-15T09:00:00.000Z',
  },
  {
    id: 'rev_2026_q3_emp_dev_2',
    employeeId: 'emp_dev_2',
    employeeCode: 'EMP-103',
    employeeName: 'Neha Kapoor',
    departmentId: 'dept_eng',
    departmentName: 'Engineering & Technology',
    designationName: 'Senior Software Engineer',
    reviewPeriodId: 'period_2026_q3',
    reviewPeriodName: '2026-Q3 (Jul - Sep)',
    cycleId: 'cycle_d',
    cycleCode: 'D',
    cycleColor: '#7e22ce',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_eng',
    managerName: 'Rohan Deshmukh',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.60,
    isSelfSubmitted: true,
    finalScore: 4.60,
    kraSnapshot: [
      {
        id: 'snap_dev2_q3_1',
        kraId: 'kra_code_delivery',
        kraName: 'Sprint Feature Delivery & Execution',
        title: 'Sprint Feature Delivery & Execution',
        targetSnapshot: '≥ 90% velocity completed, zero Sev-1 bugs in prod',
        measurementCriteria: '1: <70% | 3: 85-90% | 5: >95%',
        weight: 35,
        achievement: 'Led the UI implementation for the 8-cycle appraisal dashboard and ESS portal',
        rating: 5,
        comments: 'Outstanding delivery and craftsmanship.',
      },
      {
        id: 'snap_dev2_q3_2',
        kraId: 'kra_sys_arch',
        kraName: 'System Architecture & Maintainability',
        title: 'System Architecture & Maintainability',
        targetSnapshot: 'P95 response times < 200ms, test coverage ≥ 85%',
        measurementCriteria: '1: Latency regression | 3: SLA met | 5: Significant optimization',
        weight: 30,
        achievement: 'Integrated real-time websocket subscriptions cleanly with React state',
        rating: 4,
        comments: 'Well structured and resilient.',
      },
      {
        id: 'snap_dev2_q3_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Production Reliability & Incident SLA',
        title: 'Production Reliability & Incident SLA',
        targetSnapshot: 'Zero Sev-1 outages, MTTR < 15 mins',
        measurementCriteria: '1: Frequent downtime | 3: Clean SLA | 5: 99.99% uptime',
        weight: 35,
        achievement: 'Zero production regressions or bugs',
        rating: 5,
        comments: 'Flawless execution.',
      },
    ],
    strengths: 'UI craftsmanship, high velocity, and clean reactive architecture.',
    improvements: 'None.',
    managerOverallComments: 'Continues to shine in Senior Engineer role.',
    isClosed: true,
    completedAt: '2026-09-01T10:15:00.000Z',
    createdAt: '2026-07-01T09:00:00.000Z',
    updatedAt: '2026-09-01T10:15:00.000Z',
  },

  // --- Kavita Menon (emp_sales_1 - EMP-201) ---
  {
    id: 'rev_2025_q4_emp_sales_1',
    employeeId: 'emp_sales_1',
    employeeCode: 'EMP-201',
    employeeName: 'Kavita Menon',
    departmentId: 'dept_sales',
    departmentName: 'Sales & Business Development',
    designationName: 'Sales Account Executive',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_f',
    cycleCode: 'F',
    cycleColor: '#c2410c',
    isAppraisalMonthDue: false,
    managerId: 'emp_hod_sales',
    managerName: 'Ananya Sharma',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.60,
    isSelfSubmitted: true,
    finalScore: 4.60,
    kraSnapshot: [
      {
        id: 'snap_sales1_q4_1',
        kraId: 'kra_sales_quota',
        kraName: 'Quarterly Revenue Target Quota',
        title: 'Quarterly Revenue Target Quota',
        targetSnapshot: '100% target quota achieved ($250k ARR)',
        measurementCriteria: '1: <60% | 3: 90-100% | 5: >120%',
        weight: 45,
        achievement: 'Closed $285k ARR (114% of quarterly quota)',
        rating: 5,
        comments: 'Strong enterprise deal closing.',
      },
      {
        id: 'snap_sales1_q4_2',
        kraId: 'kra_sales_pipe',
        kraName: 'Pipeline Generation & Outbound',
        title: 'Pipeline Generation & Outbound',
        targetSnapshot: '3x quota coverage in qualified active opportunities',
        measurementCriteria: '1: <1.5x | 3: 3x | 5: >4x',
        weight: 30,
        achievement: 'Maintained 3.6x qualified pipeline',
        rating: 4,
        comments: 'Steady outbound cadence.',
      },
      {
        id: 'snap_sales1_q4_3',
        kraId: 'kra_client_retention',
        kraName: 'Client Retention & Expansion',
        title: 'Client Retention & Expansion',
        targetSnapshot: '≥ 95% net revenue retention rate',
        measurementCriteria: '1: High churn | 3: 95% | 5: >110%',
        weight: 25,
        achievement: '104% net revenue retention achieved',
        rating: 5,
        comments: 'Great customer trust.',
      },
    ],
    strengths: 'Deal qualification, executive presentation, and relationship building.',
    improvements: 'None.',
    managerOverallComments: 'Top sales producer for the region.',
    isClosed: true,
    completedAt: '2026-01-10T15:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
    updatedAt: '2026-01-10T15:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_emp_sales_1',
    employeeId: 'emp_sales_1',
    employeeCode: 'EMP-201',
    employeeName: 'Kavita Menon',
    departmentId: 'dept_sales',
    departmentName: 'Sales & Business Development',
    designationName: 'Sales Account Executive',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_f',
    cycleCode: 'F',
    cycleColor: '#c2410c',
    isAppraisalMonthDue: false,
    managerId: 'emp_hod_sales',
    managerName: 'Ananya Sharma',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.70,
    isSelfSubmitted: true,
    finalScore: 4.70,
    kraSnapshot: [
      {
        id: 'snap_sales1_q1_1',
        kraId: 'kra_sales_quota',
        kraName: 'Quarterly Revenue Target Quota',
        title: 'Quarterly Revenue Target Quota',
        targetSnapshot: '100% target quota achieved ($250k ARR)',
        measurementCriteria: '1: <60% | 3: 90-100% | 5: >120%',
        weight: 45,
        achievement: 'Closed $315k ARR (126% of quarterly quota)',
        rating: 5,
        comments: 'Exemplary deal execution.',
      },
      {
        id: 'snap_sales1_q1_2',
        kraId: 'kra_sales_pipe',
        kraName: 'Pipeline Generation & Outbound',
        title: 'Pipeline Generation & Outbound',
        targetSnapshot: '3x quota coverage in qualified active opportunities',
        measurementCriteria: '1: <1.5x | 3: 3x | 5: >4x',
        weight: 30,
        achievement: 'Generated 4.1x qualified enterprise pipeline',
        rating: 5,
        comments: 'High conversion velocity.',
      },
      {
        id: 'snap_sales1_q1_3',
        kraId: 'kra_client_retention',
        kraName: 'Client Retention & Expansion',
        title: 'Client Retention & Expansion',
        targetSnapshot: '≥ 95% net revenue retention rate',
        measurementCriteria: '1: High churn | 3: 95% | 5: >110%',
        weight: 25,
        achievement: '100% renewal rate and 2 account expansions',
        rating: 4,
        comments: 'High customer satisfaction.',
      },
    ],
    strengths: 'Superior outbound prospecting and quota overachievement.',
    improvements: 'None.',
    managerOverallComments: 'Outstanding performance across the quarter.',
    isClosed: true,
    completedAt: '2026-04-10T16:00:00.000Z',
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-04-10T16:00:00.000Z',
  },
  {
    id: 'rev_2026_q2_emp_sales_1',
    employeeId: 'emp_sales_1',
    employeeCode: 'EMP-201',
    employeeName: 'Kavita Menon',
    departmentId: 'dept_sales',
    departmentName: 'Sales & Business Development',
    designationName: 'Sales Account Executive',
    reviewPeriodId: 'period_2026_q2',
    reviewPeriodName: '2026-Q2 (Apr - Jun)',
    cycleId: 'cycle_f',
    cycleCode: 'F',
    cycleColor: '#c2410c',
    isAppraisalMonthDue: false,
    managerId: 'emp_hod_sales',
    managerName: 'Ananya Sharma',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.80,
    isSelfSubmitted: true,
    finalScore: 4.80,
    kraSnapshot: [
      {
        id: 'snap_sales1_q2_1',
        kraId: 'kra_sales_quota',
        kraName: 'Quarterly Revenue Target Quota',
        title: 'Quarterly Revenue Target Quota',
        targetSnapshot: '100% target quota achieved ($250k ARR)',
        measurementCriteria: '1: <60% | 3: 90-100% | 5: >120%',
        weight: 45,
        achievement: 'Closed $340k ARR (136% of quarterly quota)',
        rating: 5,
        comments: 'Top sales producer in the company.',
      },
      {
        id: 'snap_sales1_q2_2',
        kraId: 'kra_sales_pipe',
        kraName: 'Pipeline Generation & Outbound',
        title: 'Pipeline Generation & Outbound',
        targetSnapshot: '3x quota coverage in qualified active opportunities',
        measurementCriteria: '1: <1.5x | 3: 3x | 5: >4x',
        weight: 30,
        achievement: 'Created $1.2M qualified pipeline for H2',
        rating: 5,
        comments: 'Proactive pipeline creation.',
      },
      {
        id: 'snap_sales1_q2_3',
        kraId: 'kra_client_retention',
        kraName: 'Client Retention & Expansion',
        title: 'Client Retention & Expansion',
        targetSnapshot: '≥ 95% net revenue retention rate',
        measurementCriteria: '1: High churn | 3: 95% | 5: >110%',
        weight: 25,
        achievement: '112% NRR achieved on key accounts',
        rating: 4,
        comments: 'Solid client loyalty.',
      },
    ],
    strengths: 'Executive deal closing, rapid response, and client empathy.',
    improvements: 'None.',
    managerOverallComments: 'Top decile performer company-wide.',
    isClosed: true,
    completedAt: '2026-07-12T14:00:00.000Z',
    createdAt: '2026-04-01T09:00:00.000Z',
    updatedAt: '2026-07-12T14:00:00.000Z',
  },
  {
    id: 'rev_2026_q3_emp_sales_1',
    employeeId: 'emp_sales_1',
    employeeCode: 'EMP-201',
    employeeName: 'Kavita Menon',
    departmentId: 'dept_sales',
    departmentName: 'Sales & Business Development',
    designationName: 'Sales Account Executive',
    reviewPeriodId: 'period_2026_q3',
    reviewPeriodName: '2026-Q3 (Jul - Sep)',
    cycleId: 'cycle_f',
    cycleCode: 'F',
    cycleColor: '#c2410c',
    isAppraisalMonthDue: true,
    managerId: 'emp_hod_sales',
    managerName: 'Ananya Sharma',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.75,
    isSelfSubmitted: true,
    finalScore: 4.75,
    kraSnapshot: [
      {
        id: 'snap_sales1_q3_1',
        kraId: 'kra_sales_quota',
        kraName: 'Quarterly Revenue Target Quota',
        title: 'Quarterly Revenue Target Quota',
        targetSnapshot: '100% target quota achieved ($250k ARR)',
        measurementCriteria: '1: <60% | 3: 90-100% | 5: >120%',
        weight: 45,
        achievement: 'Closed $325k ARR (130% quota) and trained 2 new account executives',
        rating: 5,
        comments: 'Top performer recommended for promotion in Cycle F appraisal.',
      },
      {
        id: 'snap_sales1_q3_2',
        kraId: 'kra_sales_pipe',
        kraName: 'Pipeline Generation & Outbound',
        title: 'Pipeline Generation & Outbound',
        targetSnapshot: '3x quota coverage in qualified active opportunities',
        measurementCriteria: '1: <1.5x | 3: 3x | 5: >4x',
        weight: 30,
        achievement: '4.2x qualified pipeline for Q4 commercial territory',
        rating: 5,
        comments: 'Consistent prospecting discipline.',
      },
      {
        id: 'snap_sales1_q3_3',
        kraId: 'kra_client_retention',
        kraName: 'Client Retention & Expansion',
        title: 'Client Retention & Expansion',
        targetSnapshot: '≥ 95% net revenue retention rate',
        measurementCriteria: '1: High churn | 3: 95% | 5: >110%',
        weight: 25,
        achievement: '100% gross logo retention in assigned portfolio',
        rating: 4,
        comments: 'Excellent client satisfaction.',
      },
    ],
    strengths: 'Quota overachievement, leadership in peer coaching, and deal strategy.',
    improvements: 'None.',
    managerOverallComments: 'Recommended for promotion to Senior Account Executive & Mid-Market Lead.',
    isClosed: true,
    completedAt: '2026-09-01T12:00:00.000Z',
    createdAt: '2026-07-01T09:00:00.000Z',
    updatedAt: '2026-09-01T12:00:00.000Z',
  },

  // --- Ananya Sharma (emp_hod_sales - EMP-200) ---
  {
    id: 'rev_2025_q4_emp_hod_sales',
    employeeId: 'emp_hod_sales',
    employeeCode: 'EMP-200',
    employeeName: 'Ananya Sharma',
    departmentId: 'dept_sales',
    departmentName: 'Sales & Business Development',
    designationName: 'Sales Director (HOD)',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_h',
    cycleCode: 'H',
    cycleColor: '#312e81',
    isAppraisalMonthDue: false,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.50,
    isSelfSubmitted: true,
    finalScore: 4.50,
    kraSnapshot: [
      {
        id: 'snap_hods_q4_1',
        kraId: 'kra_sales_quota',
        kraName: 'Departmental Revenue Target',
        title: 'Departmental Revenue Target',
        targetSnapshot: '100% of quarterly departmental quota',
        measurementCriteria: '1: <80% | 3: 100% | 5: >115%',
        weight: 45,
        achievement: 'Department achieved 108% of Q4 revenue target ($1.62M ARR)',
        rating: 5,
        comments: 'Strong revenue leadership.',
      },
      {
        id: 'snap_hods_q4_2',
        kraId: 'kra_sales_pipe',
        kraName: 'Enterprise Pipeline Expansion',
        title: 'Enterprise Pipeline Expansion',
        targetSnapshot: '3.5x pipeline coverage for commercial team',
        measurementCriteria: '1: <2x | 3: 3.5x | 5: >4.5x',
        weight: 30,
        achievement: 'Grew active enterprise pipeline to 3.8x coverage',
        rating: 4,
        comments: 'Strong partner and channel alignment.',
      },
      {
        id: 'snap_hods_q4_3',
        kraId: 'kra_client_retention',
        kraName: 'Sales Team Retention & Enablement',
        title: 'Sales Team Retention & Enablement',
        targetSnapshot: 'Attrition < 8%, 100% sales enablement certification',
        measurementCriteria: '1: Churn | 3: On track | 5: Top decile enablement',
        weight: 25,
        achievement: 'Zero AE turnover in Q4',
        rating: 5,
        comments: 'High team motivation.',
      },
    ],
    strengths: 'Revenue operations, enterprise deal coaching, and talent retention.',
    improvements: 'None.',
    managerOverallComments: 'Outstanding sales leadership.',
    isClosed: true,
    completedAt: '2026-01-14T17:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
    updatedAt: '2026-01-14T17:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_emp_hod_sales',
    employeeId: 'emp_hod_sales',
    employeeCode: 'EMP-200',
    employeeName: 'Ananya Sharma',
    departmentId: 'dept_sales',
    departmentName: 'Sales & Business Development',
    designationName: 'Sales Director (HOD)',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_h',
    cycleCode: 'H',
    cycleColor: '#312e81',
    isAppraisalMonthDue: false,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.60,
    isSelfSubmitted: true,
    finalScore: 4.60,
    kraSnapshot: [
      {
        id: 'snap_hods_q1_1',
        kraId: 'kra_sales_quota',
        kraName: 'Departmental Revenue Target',
        title: 'Departmental Revenue Target',
        targetSnapshot: '100% of quarterly departmental quota',
        measurementCriteria: '1: <80% | 3: 100% | 5: >115%',
        weight: 45,
        achievement: 'Department reached 114% of quota ($1.71M closed ARR)',
        rating: 5,
        comments: 'Rapid deal turnaround.',
      },
      {
        id: 'snap_hods_q1_2',
        kraId: 'kra_sales_pipe',
        kraName: 'Enterprise Pipeline Expansion',
        title: 'Enterprise Pipeline Expansion',
        targetSnapshot: '3.5x pipeline coverage for commercial team',
        measurementCriteria: '1: <2x | 3: 3.5x | 5: >4.5x',
        weight: 30,
        achievement: 'Established new partner distribution network',
        rating: 4,
        comments: 'Broadened market reach.',
      },
      {
        id: 'snap_hods_q1_3',
        kraId: 'kra_client_retention',
        kraName: 'Sales Team Retention & Enablement',
        title: 'Sales Team Retention & Enablement',
        targetSnapshot: 'Attrition < 8%, 100% sales enablement certification',
        measurementCriteria: '1: Churn | 3: On track | 5: Top decile enablement',
        weight: 25,
        achievement: 'Onboarded 3 new high-performing AEs',
        rating: 5,
        comments: 'Seamless ramping.',
      },
    ],
    strengths: 'Executive selling, market expansion, and hiring high performers.',
    improvements: 'None.',
    managerOverallComments: 'Consistently exceeding revenue goals.',
    isClosed: true,
    completedAt: '2026-04-12T17:00:00.000Z',
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-04-12T17:00:00.000Z',
  },
  {
    id: 'rev_2026_q2_emp_hod_sales',
    employeeId: 'emp_hod_sales',
    employeeCode: 'EMP-200',
    employeeName: 'Ananya Sharma',
    departmentId: 'dept_sales',
    departmentName: 'Sales & Business Development',
    designationName: 'Sales Director (HOD)',
    reviewPeriodId: 'period_2026_q2',
    reviewPeriodName: '2026-Q2 (Apr - Jun)',
    cycleId: 'cycle_h',
    cycleCode: 'H',
    cycleColor: '#312e81',
    isAppraisalMonthDue: false,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.55,
    isSelfSubmitted: true,
    finalScore: 4.55,
    kraSnapshot: [
      {
        id: 'snap_hods_q2_1',
        kraId: 'kra_sales_quota',
        kraName: 'Departmental Revenue Target',
        title: 'Departmental Revenue Target',
        targetSnapshot: '100% of quarterly departmental quota',
        measurementCriteria: '1: <80% | 3: 100% | 5: >115%',
        weight: 45,
        achievement: 'Department hit 112% of revenue quota ($1.79M ARR)',
        rating: 5,
        comments: 'Consistent team-wide quota achievement.',
      },
      {
        id: 'snap_hods_q2_2',
        kraId: 'kra_sales_pipe',
        kraName: 'Enterprise Pipeline Expansion',
        title: 'Enterprise Pipeline Expansion',
        targetSnapshot: '3.5x pipeline coverage for commercial team',
        measurementCriteria: '1: <2x | 3: 3.5x | 5: >4.5x',
        weight: 30,
        achievement: 'Generated 4.0x qualified pipeline for Q3',
        rating: 4,
        comments: 'Strong outbound engine.',
      },
      {
        id: 'snap_hods_q2_3',
        kraId: 'kra_client_retention',
        kraName: 'Sales Team Retention & Enablement',
        title: 'Sales Team Retention & Enablement',
        targetSnapshot: 'Attrition < 8%, 100% sales enablement certification',
        measurementCriteria: '1: Churn | 3: On track | 5: Top decile enablement',
        weight: 25,
        achievement: '100% AE quota attainment across mid-market team',
        rating: 5,
        comments: 'Great coaching.',
      },
    ],
    strengths: 'Commercial acumen, coaching, and pipeline health.',
    improvements: 'None.',
    managerOverallComments: 'High trust director with stellar delivery.',
    isClosed: true,
    completedAt: '2026-07-14T17:00:00.000Z',
    createdAt: '2026-04-01T09:00:00.000Z',
    updatedAt: '2026-07-14T17:00:00.000Z',
  },
  {
    id: 'rev_2026_q3_emp_hod_sales',
    employeeId: 'emp_hod_sales',
    employeeCode: 'EMP-200',
    employeeName: 'Ananya Sharma',
    departmentId: 'dept_sales',
    departmentName: 'Sales & Business Development',
    designationName: 'Sales Director (HOD)',
    reviewPeriodId: 'period_2026_q3',
    reviewPeriodName: '2026-Q3 (Jul - Sep)',
    cycleId: 'cycle_h',
    cycleCode: 'H',
    cycleColor: '#312e81',
    isAppraisalMonthDue: false,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.60,
    isSelfSubmitted: true,
    finalScore: 4.60,
    kraSnapshot: [
      {
        id: 'snap_hods_q3_1',
        kraId: 'kra_sales_quota',
        kraName: 'Departmental Revenue Target',
        title: 'Departmental Revenue Target',
        targetSnapshot: '100% of quarterly departmental quota',
        measurementCriteria: '1: <80% | 3: 100% | 5: >115%',
        weight: 45,
        achievement: 'Department achieved 118% of quota ($1.88M closed ARR)',
        rating: 5,
        comments: 'Quarter-over-quarter record revenue.',
      },
      {
        id: 'snap_hods_q3_2',
        kraId: 'kra_sales_pipe',
        kraName: 'Enterprise Pipeline Expansion',
        title: 'Enterprise Pipeline Expansion',
        targetSnapshot: '3.5x pipeline coverage for commercial team',
        measurementCriteria: '1: <2x | 3: 3.5x | 5: >4.5x',
        weight: 30,
        achievement: '4.3x pipeline coverage for Q4 enterprise prospects',
        rating: 5,
        comments: 'Outstanding pipeline creation.',
      },
      {
        id: 'snap_hods_q3_3',
        kraId: 'kra_client_retention',
        kraName: 'Sales Team Retention & Enablement',
        title: 'Sales Team Retention & Enablement',
        targetSnapshot: 'Attrition < 8%, 100% sales enablement certification',
        measurementCriteria: '1: Churn | 3: On track | 5: Top decile enablement',
        weight: 25,
        achievement: 'Maintained 0% voluntary turnover in commercial team',
        rating: 4,
        comments: 'Great culture and morale.',
      },
    ],
    strengths: 'Commercial strategy, revenue predictability, and leadership.',
    improvements: 'None.',
    managerOverallComments: 'Consistently exceptional leadership.',
    isClosed: true,
    completedAt: '2026-09-01T15:30:00.000Z',
    createdAt: '2026-07-01T09:00:00.000Z',
    updatedAt: '2026-09-01T15:30:00.000Z',
  },

  // --- Rajesh Nambiar (emp_exec_mgmt - EMP-999) ---
  {
    id: 'rev_2025_q4_emp_exec_mgmt',
    employeeId: 'emp_exec_mgmt',
    employeeCode: 'EMP-999',
    employeeName: 'Rajesh Nambiar',
    departmentId: 'dept_eng',
    departmentName: 'Executive Office',
    designationName: 'Chief Operating Officer',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleColor: '#1e3a8a',
    isAppraisalMonthDue: false,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.80,
    isSelfSubmitted: true,
    finalScore: 4.80,
    kraSnapshot: [
      {
        id: 'snap_coo_q4_1',
        kraId: 'kra_code_delivery',
        kraName: 'Company Operational Execution & OKR Attainment',
        title: 'Company Operational Execution & OKR Attainment',
        targetSnapshot: '100% corporate OKRs achieved within financial budget',
        measurementCriteria: '1: <80% | 3: 95% | 5: >100%',
        weight: 40,
        achievement: 'Delivered 100% of executive operational roadmap goals',
        rating: 5,
        comments: 'Pristine leadership.',
      },
      {
        id: 'snap_coo_q4_2',
        kraId: 'kra_sys_arch',
        kraName: 'Financial Stewardship & EBITDA Margins',
        title: 'Financial Stewardship & EBITDA Margins',
        targetSnapshot: 'Healthy EBITDA margins and cost control',
        measurementCriteria: '1: Budget overrun | 3: Balanced | 5: High efficiency',
        weight: 35,
        achievement: 'Maintained 24% operating margin with positive cash flow',
        rating: 5,
        comments: 'Strong fiscal discipline.',
      },
      {
        id: 'snap_coo_q4_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Organization Scaling & Governance',
        title: 'Organization Scaling & Governance',
        targetSnapshot: 'Zero compliance breaches, high governance ratings',
        measurementCriteria: '1: Audit remarks | 3: Clean | 5: Exemplary governance',
        weight: 25,
        achievement: 'Clean statutory audit and corporate compliance across all units',
        rating: 4,
        comments: 'Excellent governance.',
      },
    ],
    strengths: 'Executive leadership, strategic vision, and operations management.',
    improvements: 'None.',
    managerOverallComments: 'Exemplary executive performance.',
    isClosed: true,
    completedAt: '2026-01-15T18:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
    updatedAt: '2026-01-15T18:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_emp_exec_mgmt',
    employeeId: 'emp_exec_mgmt',
    employeeCode: 'EMP-999',
    employeeName: 'Rajesh Nambiar',
    departmentId: 'dept_eng',
    departmentName: 'Executive Office',
    designationName: 'Chief Operating Officer',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleColor: '#1e3a8a',
    isAppraisalMonthDue: true,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.85,
    isSelfSubmitted: true,
    finalScore: 4.85,
    kraSnapshot: [
      {
        id: 'snap_coo_q1_1',
        kraId: 'kra_code_delivery',
        kraName: 'Company Operational Execution & OKR Attainment',
        title: 'Company Operational Execution & OKR Attainment',
        targetSnapshot: '100% corporate OKRs achieved within financial budget',
        measurementCriteria: '1: <80% | 3: 95% | 5: >100%',
        weight: 40,
        achievement: 'Guided Q1 business scaling and new product launch',
        rating: 5,
        comments: 'Exemplary execution.',
      },
      {
        id: 'snap_coo_q1_2',
        kraId: 'kra_sys_arch',
        kraName: 'Financial Stewardship & EBITDA Margins',
        title: 'Financial Stewardship & EBITDA Margins',
        targetSnapshot: 'Healthy EBITDA margins and cost control',
        measurementCriteria: '1: Budget overrun | 3: Balanced | 5: High efficiency',
        weight: 35,
        achievement: 'Operating margins expanded by 2.4%',
        rating: 5,
        comments: 'Strong financial management.',
      },
      {
        id: 'snap_coo_q1_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Organization Scaling & Governance',
        title: 'Organization Scaling & Governance',
        targetSnapshot: 'Zero compliance breaches, high governance ratings',
        measurementCriteria: '1: Audit remarks | 3: Clean | 5: Exemplary governance',
        weight: 25,
        achievement: '100% cross-functional compliance in all department reviews',
        rating: 5,
        comments: 'High governance standard.',
      },
    ],
    strengths: 'Corporate leadership, financial planning, and operational excellence.',
    improvements: 'None.',
    managerOverallComments: 'Outstanding executive contribution.',
    isClosed: true,
    completedAt: '2026-04-15T18:00:00.000Z',
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-04-15T18:00:00.000Z',
  },
  {
    id: 'rev_2026_q2_emp_exec_mgmt',
    employeeId: 'emp_exec_mgmt',
    employeeCode: 'EMP-999',
    employeeName: 'Rajesh Nambiar',
    departmentId: 'dept_eng',
    departmentName: 'Executive Office',
    designationName: 'Chief Operating Officer',
    reviewPeriodId: 'period_2026_q2',
    reviewPeriodName: '2026-Q2 (Apr - Jun)',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleColor: '#1e3a8a',
    isAppraisalMonthDue: false,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.80,
    isSelfSubmitted: true,
    finalScore: 4.80,
    kraSnapshot: [
      {
        id: 'snap_coo_q2_1',
        kraId: 'kra_code_delivery',
        kraName: 'Company Operational Execution & OKR Attainment',
        title: 'Company Operational Execution & OKR Attainment',
        targetSnapshot: '100% corporate OKRs achieved within financial budget',
        measurementCriteria: '1: <80% | 3: 95% | 5: >100%',
        weight: 40,
        achievement: 'Closed mid-year strategic reviews across all business divisions',
        rating: 5,
        comments: 'Seamless leadership.',
      },
      {
        id: 'snap_coo_q2_2',
        kraId: 'kra_sys_arch',
        kraName: 'Financial Stewardship & EBITDA Margins',
        title: 'Financial Stewardship & EBITDA Margins',
        targetSnapshot: 'Healthy EBITDA margins and cost control',
        measurementCriteria: '1: Budget overrun | 3: Balanced | 5: High efficiency',
        weight: 35,
        achievement: 'Maintained low cost of capital and budget discipline',
        rating: 5,
        comments: 'Efficient allocation of capital.',
      },
      {
        id: 'snap_coo_q2_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Organization Scaling & Governance',
        title: 'Organization Scaling & Governance',
        targetSnapshot: 'Zero compliance breaches, high governance ratings',
        measurementCriteria: '1: Audit remarks | 3: Clean | 5: Exemplary governance',
        weight: 25,
        achievement: 'Executed global compliance checks with 100% pass score',
        rating: 4,
        comments: 'Solid governance.',
      },
    ],
    strengths: 'Executive alignment and business execution.',
    improvements: 'None.',
    managerOverallComments: 'Consistently exceptional executive performance.',
    isClosed: true,
    completedAt: '2026-07-16T18:00:00.000Z',
    createdAt: '2026-04-01T09:00:00.000Z',
    updatedAt: '2026-07-16T18:00:00.000Z',
  },
  {
    id: 'rev_2026_q3_emp_exec_mgmt',
    employeeId: 'emp_exec_mgmt',
    employeeCode: 'EMP-999',
    employeeName: 'Rajesh Nambiar',
    departmentId: 'dept_eng',
    departmentName: 'Executive Office',
    designationName: 'Chief Operating Officer',
    reviewPeriodId: 'period_2026_q3',
    reviewPeriodName: '2026-Q3 (Jul - Sep)',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleColor: '#1e3a8a',
    isAppraisalMonthDue: false,
    managerId: 'emp_exec_mgmt',
    managerName: 'Rajesh Nambiar',
    hrId: 'emp_hr_lead',
    hrName: 'Pooja Iyer',
    status: 'CLOSED',
    selfScore: 4.85,
    isSelfSubmitted: true,
    finalScore: 4.85,
    kraSnapshot: [
      {
        id: 'snap_coo_q3_1',
        kraId: 'kra_code_delivery',
        kraName: 'Company Operational Execution & OKR Attainment',
        title: 'Company Operational Execution & OKR Attainment',
        targetSnapshot: '100% corporate OKRs achieved within financial budget',
        measurementCriteria: '1: <80% | 3: 95% | 5: >100%',
        weight: 40,
        achievement: 'Oversaw company-wide launch of the 8-cycle appraisal architecture',
        rating: 5,
        comments: 'Major milestone delivered with high operational rigor.',
      },
      {
        id: 'snap_coo_q3_2',
        kraId: 'kra_sys_arch',
        kraName: 'Financial Stewardship & EBITDA Margins',
        title: 'Financial Stewardship & EBITDA Margins',
        targetSnapshot: 'Healthy EBITDA margins and cost control',
        measurementCriteria: '1: Budget overrun | 3: Balanced | 5: High efficiency',
        weight: 35,
        achievement: 'Operating margins reached 26.2% in Q3',
        rating: 5,
        comments: 'High fiscal efficiency.',
      },
      {
        id: 'snap_coo_q3_3',
        kraId: 'kra_prod_reliab',
        kraName: 'Organization Scaling & Governance',
        title: 'Organization Scaling & Governance',
        targetSnapshot: 'Zero compliance breaches, high governance ratings',
        measurementCriteria: '1: Audit remarks | 3: Clean | 5: Exemplary governance',
        weight: 25,
        achievement: 'Company eNPS reached all-time high of +56',
        rating: 5,
        comments: 'Outstanding organizational health.',
      },
    ],
    strengths: 'Visionary leadership, enterprise agility, and exceptional financial stewardship.',
    improvements: 'None.',
    managerOverallComments: 'Chief Operating Officer benchmark standard.',
    isClosed: true,
    completedAt: '2026-09-01T17:00:00.000Z',
    createdAt: '2026-07-01T09:00:00.000Z',
    updatedAt: '2026-09-01T17:00:00.000Z',
  },
];
