import { EmployeeReview } from '../src/types.js';

export const SEED_EMPLOYEE_REVIEWS: EmployeeReview[] = [
  // ==========================================
  // GRACE ENGINEER (emp_com_1) - High Performer
  // ==========================================
  {
    id: 'rev_2025_q3_grace',
    employeeId: 'emp_com_1',
    employeeCode: 'EMP-007',
    employeeName: 'Grace Engineer',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    designationName: 'Software Engineer',
    reviewPeriodId: 'period_2025_q3',
    reviewPeriodName: '2025-Q3 (Jul - Sep)',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleColor: '#1e3a8a',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_eng',
    managerName: 'Dave Eng Manager',
    hrId: 'emp_mgr_hr',
    hrName: 'Frank HR Manager',
    status: 'CLOSED',
    selfScore: 4.5,
    isSelfSubmitted: true,
    selfSubmittedAt: '2025-10-05T10:00:00.000Z',
    finalScore: 4.5,
    kraSnapshot: [
      { id: 'snap_gr_q3_1', kraId: 'kra_eng_sprint', kraName: 'Sprint Velocity & Delivery Cadence', targetSnapshot: '95% planned deliverables', measurementCriteria: '1: <80% | 3: 90% | 5: >95%', weight: 40, achievement: 'Delivered 98% of committed sprint tasks on time', rating: 5, comments: 'Consistent delivery with zero missed deadlines' },
      { id: 'snap_gr_q3_2', kraId: 'kra_eng_quality', kraName: 'Code Quality & Reliability', targetSnapshot: 'Zero P0 regressions, 85% test coverage', measurementCriteria: '1: P0 bugs | 3: 80% coverage | 5: 90%+ coverage', weight: 35, achievement: 'Maintained 88% unit test coverage, 0 critical defects', rating: 4, comments: 'High quality code with rigorous automated testing' },
      { id: 'snap_gr_q3_3', kraId: 'kra_eng_arch', kraName: 'System Architecture & Performance', targetSnapshot: 'p99 latency < 150ms', measurementCriteria: '1: >300ms | 3: 150-200ms | 5: <150ms', weight: 25, achievement: 'Optimized DB queries reducing API latency to 110ms', rating: 4.5, comments: 'Significant performance gains on high-volume endpoints' },
    ],
    strengths: 'Exceptional architectural thinking, proactive code reviews, rapid debugging.',
    improvements: 'Continue knowledge sharing and lead cross-department technical workshops.',
    managerOverallComments: 'Outstanding contributor to the engineering core platform.',
    isClosed: true,
    completedAt: '2025-10-14T15:00:00.000Z',
    createdAt: '2025-07-01T09:00:00.000Z',
    updatedAt: '2025-10-14T15:00:00.000Z',
  },
  {
    id: 'rev_2025_q4_grace',
    employeeId: 'emp_com_1',
    employeeCode: 'EMP-007',
    employeeName: 'Grace Engineer',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    designationName: 'Software Engineer',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleColor: '#1e3a8a',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_eng',
    managerName: 'Dave Eng Manager',
    hrId: 'emp_mgr_hr',
    hrName: 'Frank HR Manager',
    status: 'CLOSED',
    selfScore: 4.6,
    isSelfSubmitted: true,
    selfSubmittedAt: '2026-01-08T11:00:00.000Z',
    finalScore: 4.65,
    kraSnapshot: [
      { id: 'snap_gr_q4_1', kraId: 'kra_eng_sprint', kraName: 'Sprint Velocity & Delivery Cadence', targetSnapshot: '95% planned deliverables', measurementCriteria: '1: <80% | 3: 90% | 5: >95%', weight: 40, achievement: 'Led Q4 release, delivered all milestones 3 days early', rating: 5, comments: 'Flawless execution of critical microservice refactoring' },
      { id: 'snap_gr_q4_2', kraId: 'kra_eng_quality', kraName: 'Code Quality & Reliability', targetSnapshot: 'Zero P0 regressions, 85% test coverage', measurementCriteria: '1: P0 bugs | 3: 80% coverage | 5: 90%+ coverage', weight: 35, achievement: 'Achieved 91% code coverage across new components', rating: 4.5, comments: 'Solid architectural standards and documentation' },
      { id: 'snap_gr_q4_3', kraId: 'kra_eng_arch', kraName: 'System Architecture & Performance', targetSnapshot: 'p99 latency < 150ms', measurementCriteria: '1: >300ms | 3: 150-200ms | 5: <150ms', weight: 25, achievement: 'Engineered in-memory caching reducing peak load by 40%', rating: 4.5, comments: 'High impact on operational stability and infrastructure costs' },
    ],
    strengths: 'Leadership capabilities and high technical velocity.',
    improvements: 'Ready for Senior Software Engineer responsibilities.',
    managerOverallComments: 'Consistently sets the benchmark for engineering excellence.',
    isClosed: true,
    completedAt: '2026-01-15T16:30:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
    updatedAt: '2026-01-15T16:30:00.000Z',
  },
  {
    id: 'rev_2026_q1_grace',
    employeeId: 'emp_com_1',
    employeeCode: 'EMP-007',
    employeeName: 'Grace Engineer',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    designationName: 'Software Engineer',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleColor: '#1e3a8a',
    isAppraisalMonthDue: true,
    managerId: 'emp_mgr_eng',
    managerName: 'Dave Eng Manager',
    hrId: 'emp_mgr_hr',
    hrName: 'Frank HR Manager',
    status: 'HR_PENDING',
    selfScore: 4.7,
    isSelfSubmitted: true,
    selfSubmittedAt: '2026-03-25T14:00:00.000Z',
    finalScore: 4.7,
    kraSnapshot: [
      { id: 'snap_gr_q1_1', kraId: 'kra_eng_sprint', kraName: 'Sprint Velocity & Delivery Cadence', targetSnapshot: '95% planned deliverables', measurementCriteria: '1: <80% | 3: 90% | 5: >95%', weight: 40, achievement: 'Completed all enterprise API feature requirements', rating: 5, comments: 'Stellar velocity and delivery discipline' },
      { id: 'snap_gr_q1_2', kraId: 'kra_eng_quality', kraName: 'Code Quality & Reliability', targetSnapshot: 'Zero P0 regressions, 85% test coverage', measurementCriteria: '1: P0 bugs | 3: 80% coverage | 5: 90%+ coverage', weight: 35, achievement: 'Zero incidents in production, comprehensive E2E tests', rating: 4.5, comments: 'High reliability in continuous delivery pipeline' },
      { id: 'snap_gr_q1_3', kraId: 'kra_eng_arch', kraName: 'System Architecture & Performance', targetSnapshot: 'p99 latency < 150ms', measurementCriteria: '1: >300ms | 3: 150-200ms | 5: <150ms', weight: 25, achievement: 'Designed event-driven messaging layer with sub-100ms response', rating: 4.5, comments: 'Excellent architectural vision' },
    ],
    strengths: 'Independent technical leadership and rapid execution.',
    improvements: 'Take up junior engineer mentorship officially.',
    managerOverallComments: 'Strongly recommend promotion to Senior Software Engineer.',
    isClosed: false,
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-03-28T10:00:00.000Z',
  },

  // ==========================================
  // HANK ENGINEER (emp_com_2) - Solid Performer
  // ==========================================
  {
    id: 'rev_2025_q3_hank',
    employeeId: 'emp_com_2',
    employeeCode: 'EMP-008',
    employeeName: 'Hank Engineer',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    designationName: 'Software Engineer',
    reviewPeriodId: 'period_2025_q3',
    reviewPeriodName: '2025-Q3 (Jul - Sep)',
    cycleId: 'cycle_b',
    cycleCode: 'B',
    cycleColor: '#0d9488',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_eng',
    managerName: 'Dave Eng Manager',
    status: 'CLOSED',
    selfScore: 3.8,
    isSelfSubmitted: true,
    finalScore: 3.75,
    kraSnapshot: [
      { id: 'snap_hk_q3_1', kraId: 'kra_eng_sprint', kraName: 'Sprint Velocity & Delivery Cadence', targetSnapshot: '95% planned deliverables', measurementCriteria: '1: <80% | 3: 90% | 5: >95%', weight: 40, achievement: 'Delivered 88% of planned sprint tickets', rating: 3.5, comments: 'Good steady progress, slight delays on external dependencies' },
      { id: 'snap_hk_q3_2', kraId: 'kra_eng_quality', kraName: 'Code Quality & Reliability', targetSnapshot: 'Zero P0 regressions, 85% test coverage', measurementCriteria: '1: P0 bugs | 3: 80% coverage | 5: 90%+ coverage', weight: 35, achievement: 'Maintained 82% unit test coverage', rating: 4, comments: 'Clean code and diligent PR reviews' },
      { id: 'snap_hk_q3_3', kraId: 'kra_eng_arch', kraName: 'System Architecture & Performance', targetSnapshot: 'p99 latency < 150ms', measurementCriteria: '1: >300ms | 3: 150-200ms | 5: <150ms', weight: 25, achievement: 'Maintained stable services within acceptable limits', rating: 4, comments: 'Dependable operational support' },
    ],
    strengths: 'Reliable team player, solid backend knowledge.',
    improvements: 'Improve sprint task estimation accuracy.',
    managerOverallComments: 'Reliable engineer meeting all essential expectations.',
    isClosed: true,
    completedAt: '2025-10-12T14:00:00.000Z',
    createdAt: '2025-07-01T09:00:00.000Z',
  },
  {
    id: 'rev_2025_q4_hank',
    employeeId: 'emp_com_2',
    employeeCode: 'EMP-008',
    employeeName: 'Hank Engineer',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    designationName: 'Software Engineer',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_b',
    cycleCode: 'B',
    cycleColor: '#0d9488',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_eng',
    managerName: 'Dave Eng Manager',
    status: 'CLOSED',
    selfScore: 3.9,
    isSelfSubmitted: true,
    finalScore: 3.85,
    kraSnapshot: [
      { id: 'snap_hk_q4_1', kraId: 'kra_eng_sprint', kraName: 'Sprint Velocity & Delivery Cadence', targetSnapshot: '95% planned deliverables', measurementCriteria: '1: <80% | 3: 90% | 5: >95%', weight: 40, achievement: 'Delivered 92% of committed sprint goals', rating: 4, comments: 'Improved velocity and task breakdown' },
      { id: 'snap_hk_q4_2', kraId: 'kra_eng_quality', kraName: 'Code Quality & Reliability', targetSnapshot: 'Zero P0 regressions, 85% test coverage', measurementCriteria: '1: P0 bugs | 3: 80% coverage | 5: 90%+ coverage', weight: 35, achievement: 'Coverage increased to 85%', rating: 4, comments: 'Very thorough testing on database migration' },
      { id: 'snap_hk_q4_3', kraId: 'kra_eng_arch', kraName: 'System Architecture & Performance', targetSnapshot: 'p99 latency < 150ms', measurementCriteria: '1: >300ms | 3: 150-200ms | 5: <150ms', weight: 25, achievement: 'Service p99 maintained under 140ms', rating: 3.5, comments: 'Good maintenance and uptime stability' },
    ],
    strengths: 'Cooperative attitude and steady improvement.',
    improvements: 'Take up initiative on complex system components.',
    managerOverallComments: 'Positive trajectory throughout the quarter.',
    isClosed: true,
    completedAt: '2026-01-14T11:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_hank',
    employeeId: 'emp_com_2',
    employeeCode: 'EMP-008',
    employeeName: 'Hank Engineer',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    designationName: 'Software Engineer',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_b',
    cycleCode: 'B',
    cycleColor: '#0d9488',
    isAppraisalMonthDue: true,
    managerId: 'emp_mgr_eng',
    managerName: 'Dave Eng Manager',
    status: 'MANAGER_PENDING',
    selfScore: 3.9,
    isSelfSubmitted: true,
    selfSubmittedAt: '2026-03-24T16:00:00.000Z',
    kraSnapshot: [
      { id: 'snap_hk_q1_1', kraId: 'kra_eng_sprint', kraName: 'Sprint Velocity & Delivery Cadence', targetSnapshot: '95% planned deliverables', measurementCriteria: '1: <80% | 3: 90% | 5: >95%', weight: 40, achievement: 'Completed authentication security updates', rating: 4, comments: 'Good execution on compliance tasks' },
      { id: 'snap_hk_q1_2', kraId: 'kra_eng_quality', kraName: 'Code Quality & Reliability', targetSnapshot: 'Zero P0 regressions, 85% test coverage', measurementCriteria: '1: P0 bugs | 3: 80% coverage | 5: 90%+ coverage', weight: 35, achievement: 'Zero regression defects reported', rating: 4, comments: 'Diligent automated test coverage' },
      { id: 'snap_hk_q1_3', kraId: 'kra_eng_arch', kraName: 'System Architecture & Performance', targetSnapshot: 'p99 latency < 150ms', measurementCriteria: '1: >300ms | 3: 150-200ms | 5: <150ms', weight: 25, achievement: 'Optimized log aggregation pipelines', rating: 3.5, comments: 'Solid infrastructure performance' },
    ],
    strengths: 'Consistent work ethic, dependable team contributor.',
    improvements: 'Deepen knowledge in cloud microservice scaling.',
    isClosed: false,
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-03-24T16:00:00.000Z',
  },

  // ==========================================
  // IVY SALES REP (emp_com_3) - High Performer
  // ==========================================
  {
    id: 'rev_2025_q3_ivy',
    employeeId: 'emp_com_3',
    employeeCode: 'EMP-009',
    employeeName: 'Ivy Sales Rep',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    designationName: 'Sales Representative',
    reviewPeriodId: 'period_2025_q3',
    reviewPeriodName: '2025-Q3 (Jul - Sep)',
    cycleId: 'cycle_c',
    cycleCode: 'C',
    cycleColor: '#059669',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_sales',
    managerName: 'Eve Sales Manager',
    status: 'CLOSED',
    selfScore: 4.3,
    isSelfSubmitted: true,
    finalScore: 4.3,
    kraSnapshot: [
      { id: 'snap_iv_q3_1', kraId: 'kra_sales_quota', kraName: 'Quarterly Revenue & Quota Achievement', targetSnapshot: '100% quota achieved', measurementCriteria: '1: <70% | 3: 100% | 5: >120%', weight: 50, achievement: 'Achieved 112% of quarterly revenue quota', rating: 4.5, comments: 'Closed 2 major annual recurring enterprise contracts' },
      { id: 'snap_iv_q3_2', kraId: 'kra_sales_acquisition', kraName: 'Enterprise Logo Acquisition', targetSnapshot: '8 enterprise logos', measurementCriteria: '1: <4 | 3: 8 | 5: >10', weight: 30, achievement: 'Acquired 9 new customer accounts', rating: 4.5, comments: 'Aggressive outbound prospecting and high conversion rate' },
      { id: 'snap_iv_q3_3', kraId: 'kra_sales_crm', kraName: 'CRM Pipeline Hygiene & Accuracy', targetSnapshot: '95% hygiene score', measurementCriteria: '1: <80% | 3: 95% | 5: 100%', weight: 20, achievement: 'Maintained 96% CRM data accuracy', rating: 4, comments: 'Timely sales stage updates and customer touch logs' },
    ],
    strengths: 'Outstanding consultative closing skills, strong customer empathy.',
    improvements: 'Mentor newer sales reps on outbound discovery calls.',
    managerOverallComments: 'Top sales producer for the region.',
    isClosed: true,
    completedAt: '2025-10-10T12:00:00.000Z',
    createdAt: '2025-07-01T09:00:00.000Z',
  },
  {
    id: 'rev_2025_q4_ivy',
    employeeId: 'emp_com_3',
    employeeCode: 'EMP-009',
    employeeName: 'Ivy Sales Rep',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    designationName: 'Sales Representative',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_c',
    cycleCode: 'C',
    cycleColor: '#059669',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_sales',
    managerName: 'Eve Sales Manager',
    status: 'CLOSED',
    selfScore: 4.5,
    isSelfSubmitted: true,
    finalScore: 4.45,
    kraSnapshot: [
      { id: 'snap_iv_q4_1', kraId: 'kra_sales_quota', kraName: 'Quarterly Revenue & Quota Achievement', targetSnapshot: '100% quota achieved', measurementCriteria: '1: <70% | 3: 100% | 5: >120%', weight: 50, achievement: 'Achieved 124% of Q4 target during year-end push', rating: 5, comments: 'Exceptional quota over-achievement' },
      { id: 'snap_iv_q4_2', kraId: 'kra_sales_acquisition', kraName: 'Enterprise Logo Acquisition', targetSnapshot: '8 enterprise logos', measurementCriteria: '1: <4 | 3: 8 | 5: >10', weight: 30, achievement: 'Brought in 10 enterprise customers', rating: 4.5, comments: 'High-value multi-year commitments secured' },
      { id: 'snap_iv_q4_3', kraId: 'kra_sales_crm', kraName: 'CRM Pipeline Hygiene & Accuracy', targetSnapshot: '95% hygiene score', measurementCriteria: '1: <80% | 3: 95% | 5: 100%', weight: 20, achievement: 'Maintained 94% CRM completeness', rating: 3.5, comments: 'Solid pipeline records' },
    ],
    strengths: 'Excellent negotiation abilities and enterprise relationship management.',
    improvements: 'Expand account management for upsell opportunities.',
    managerOverallComments: 'Exceptional sales execution throughout Q4.',
    isClosed: true,
    completedAt: '2026-01-11T16:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_ivy',
    employeeId: 'emp_com_3',
    employeeCode: 'EMP-009',
    employeeName: 'Ivy Sales Rep',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    designationName: 'Sales Representative',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_c',
    cycleCode: 'C',
    cycleColor: '#059669',
    isAppraisalMonthDue: true,
    managerId: 'emp_mgr_sales',
    managerName: 'Eve Sales Manager',
    status: 'CLOSED',
    selfScore: 4.6,
    isSelfSubmitted: true,
    finalScore: 4.55,
    kraSnapshot: [
      { id: 'snap_iv_q1_1', kraId: 'kra_sales_quota', kraName: 'Quarterly Revenue & Quota Achievement', targetSnapshot: '100% quota achieved', measurementCriteria: '1: <70% | 3: 100% | 5: >120%', weight: 50, achievement: 'Exceeded target at 118% quota', rating: 5, comments: 'Closed early in the quarter' },
      { id: 'snap_iv_q1_2', kraId: 'kra_sales_acquisition', kraName: 'Enterprise Logo Acquisition', targetSnapshot: '8 enterprise logos', measurementCriteria: '1: <4 | 3: 8 | 5: >10', weight: 30, achievement: 'Secured 8 enterprise deals', rating: 4, comments: 'Solid conversion rate' },
      { id: 'snap_iv_q1_3', kraId: 'kra_sales_crm', kraName: 'CRM Pipeline Hygiene & Accuracy', targetSnapshot: '95% hygiene score', measurementCriteria: '1: <80% | 3: 95% | 5: 100%', weight: 20, achievement: '100% compliant with CRM logging protocols', rating: 4.5, comments: 'Flawless sales documentation' },
    ],
    strengths: 'Consistent quota attainment, strong executive presence.',
    improvements: 'Ready for Senior Sales Representative role.',
    managerOverallComments: 'Recommended for promotion and tier-1 account tier.',
    isClosed: true,
    completedAt: '2026-03-29T11:00:00.000Z',
    createdAt: '2026-01-01T09:00:00.000Z',
  },

  // ==========================================
  // JACK SALES REP (emp_com_4) - Underperformer / On PIP
  // ==========================================
  {
    id: 'rev_2025_q3_jack',
    employeeId: 'emp_com_4',
    employeeCode: 'EMP-010',
    employeeName: 'Jack Sales Rep',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    designationName: 'Sales Representative',
    reviewPeriodId: 'period_2025_q3',
    reviewPeriodName: '2025-Q3 (Jul - Sep)',
    cycleId: 'cycle_d',
    cycleCode: 'D',
    cycleColor: '#7c3aed',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_sales',
    managerName: 'Eve Sales Manager',
    status: 'CLOSED',
    selfScore: 3.2,
    isSelfSubmitted: true,
    finalScore: 2.8,
    kraSnapshot: [
      { id: 'snap_jk_q3_1', kraId: 'kra_sales_quota', kraName: 'Quarterly Revenue & Quota Achievement', targetSnapshot: '100% quota achieved', measurementCriteria: '1: <70% | 3: 100% | 5: >120%', weight: 50, achievement: 'Reached 68% of assigned quota', rating: 2.5, comments: 'Slipped 3 major expected deals past quarter end' },
      { id: 'snap_jk_q3_2', kraId: 'kra_sales_acquisition', kraName: 'Enterprise Logo Acquisition', targetSnapshot: '8 enterprise logos', measurementCriteria: '1: <4 | 3: 8 | 5: >10', weight: 30, achievement: 'Acquired 4 enterprise logos', rating: 3, comments: 'Low outbound prospect volume' },
      { id: 'snap_jk_q3_3', kraId: 'kra_sales_crm', kraName: 'CRM Pipeline Hygiene & Accuracy', targetSnapshot: '95% hygiene score', measurementCriteria: '1: <80% | 3: 95% | 5: 100%', weight: 20, achievement: '81% hygiene score, multiple overdue deals in pipeline', rating: 3, comments: 'Needs to maintain accurate forecast dates' },
    ],
    strengths: 'Enthusiastic and polite with prospective clients.',
    improvements: 'Urgent need to improve prospect qualification and deal closing techniques.',
    managerOverallComments: 'Performance fell short of target expectations.',
    isClosed: true,
    completedAt: '2025-10-16T15:00:00.000Z',
    createdAt: '2025-07-01T09:00:00.000Z',
  },
  {
    id: 'rev_2025_q4_jack',
    employeeId: 'emp_com_4',
    employeeCode: 'EMP-010',
    employeeName: 'Jack Sales Rep',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    designationName: 'Sales Representative',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_d',
    cycleCode: 'D',
    cycleColor: '#7c3aed',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_sales',
    managerName: 'Eve Sales Manager',
    status: 'CLOSED',
    selfScore: 3.0,
    isSelfSubmitted: true,
    finalScore: 2.7,
    kraSnapshot: [
      { id: 'snap_jk_q4_1', kraId: 'kra_sales_quota', kraName: 'Quarterly Revenue & Quota Achievement', targetSnapshot: '100% quota achieved', measurementCriteria: '1: <70% | 3: 100% | 5: >120%', weight: 50, achievement: 'Finished at 64% of Q4 quota', rating: 2.5, comments: 'Persistent shortfall in pipeline generation' },
      { id: 'snap_jk_q4_2', kraId: 'kra_sales_acquisition', kraName: 'Enterprise Logo Acquisition', targetSnapshot: '8 enterprise logos', measurementCriteria: '1: <4 | 3: 8 | 5: >10', weight: 30, achievement: 'Closed 3 logos against target of 8', rating: 2.5, comments: 'Insufficient outreach cadence' },
      { id: 'snap_jk_q4_3', kraId: 'kra_sales_crm', kraName: 'CRM Pipeline Hygiene & Accuracy', targetSnapshot: '95% hygiene score', measurementCriteria: '1: <80% | 3: 95% | 5: 100%', weight: 20, achievement: 'Maintained 84% CRM completeness', rating: 3, comments: 'Requires manager intervention to keep pipeline current' },
    ],
    strengths: 'Positive team demeanor.',
    improvements: 'Initiating structured Performance Improvement Plan (PIP) to support recovery.',
    managerOverallComments: 'Requires structured milestone monitoring in Q1.',
    isClosed: true,
    completedAt: '2026-01-18T10:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_jack',
    employeeId: 'emp_com_4',
    employeeCode: 'EMP-010',
    employeeName: 'Jack Sales Rep',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    designationName: 'Sales Representative',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_d',
    cycleCode: 'D',
    cycleColor: '#7c3aed',
    isAppraisalMonthDue: true,
    managerId: 'emp_mgr_sales',
    managerName: 'Eve Sales Manager',
    status: 'MANAGER_PENDING',
    selfScore: 3.1,
    isSelfSubmitted: true,
    selfSubmittedAt: '2026-03-22T09:30:00.000Z',
    kraSnapshot: [
      { id: 'snap_jk_q1_1', kraId: 'kra_sales_quota', kraName: 'Quarterly Revenue & Quota Achievement', targetSnapshot: '100% quota achieved', measurementCriteria: '1: <70% | 3: 100% | 5: >120%', weight: 50, achievement: 'Current achievement at 60%', rating: 2.5, comments: 'Ongoing coaching sessions underway' },
      { id: 'snap_jk_q1_2', kraId: 'kra_sales_acquisition', kraName: 'Enterprise Logo Acquisition', targetSnapshot: '8 enterprise logos', measurementCriteria: '1: <4 | 3: 8 | 5: >10', weight: 30, achievement: '3 logos closed to date', rating: 2.5, comments: 'Pipeline nurturing in progress' },
      { id: 'snap_jk_q1_3', kraId: 'kra_sales_crm', kraName: 'CRM Pipeline Hygiene & Accuracy', targetSnapshot: '95% hygiene score', measurementCriteria: '1: <80% | 3: 95% | 5: 100%', weight: 20, achievement: 'Hygiene score improved to 88%', rating: 3, comments: 'Showing better diligence in CRM notes' },
    ],
    strengths: 'Responsiveness to manager coaching.',
    improvements: 'Must achieve PIP milestones to retain role.',
    isClosed: false,
    createdAt: '2026-01-01T09:00:00.000Z',
  },

  // ==========================================
  // KAREN HR SPEC (emp_com_5) - High Performer
  // ==========================================
  {
    id: 'rev_2025_q3_karen',
    employeeId: 'emp_com_5',
    employeeCode: 'EMP-011',
    employeeName: 'Karen HR Spec',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources',
    designationName: 'HR Specialist',
    reviewPeriodId: 'period_2025_q3',
    reviewPeriodName: '2025-Q3 (Jul - Sep)',
    cycleId: 'cycle_e',
    cycleCode: 'E',
    cycleColor: '#e11d48',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_hr',
    managerName: 'Frank HR Manager',
    status: 'CLOSED',
    selfScore: 4.1,
    isSelfSubmitted: true,
    finalScore: 4.1,
    kraSnapshot: [
      { id: 'snap_kr_q3_1', kraId: 'kra_hr_appraisal', kraName: 'Appraisal & Performance Review Operations', targetSnapshot: '100% on-time execution', measurementCriteria: '1: <85% | 3: 95% | 5: 100%', weight: 40, achievement: 'Coordinated Q3 reviews with 98% on-time submission', rating: 4, comments: 'Very smooth communications with managers' },
      { id: 'snap_kr_q3_2', kraId: 'kra_hr_talent', kraName: 'Talent Acquisition SLA & Time-to-Hire', targetSnapshot: '< 30 days time-to-hire', measurementCriteria: '1: >45d | 3: 30d | 5: <22d', weight: 35, achievement: 'Average time-to-fill was 26 days', rating: 4.5, comments: 'Fast turnaround on candidate scheduling' },
      { id: 'snap_kr_q3_3', kraId: 'kra_hr_retention', kraName: 'Employee Retention & eNPS Engagement', targetSnapshot: 'eNPS >= 45', measurementCriteria: '1: <25 | 3: 45 | 5: >55', weight: 25, achievement: 'eNPS measured at +48 for Q3', rating: 4, comments: 'Organized successful wellness & onboarding webinars' },
    ],
    strengths: 'Empathy, organized documentation, prompt employee grievance resolution.',
    improvements: 'Automate repetitive onboarding paperwork.',
    managerOverallComments: 'Great work managing employee operations.',
    isClosed: true,
    completedAt: '2025-10-13T11:00:00.000Z',
    createdAt: '2025-07-01T09:00:00.000Z',
  },
  {
    id: 'rev_2025_q4_karen',
    employeeId: 'emp_com_5',
    employeeCode: 'EMP-011',
    employeeName: 'Karen HR Spec',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources',
    designationName: 'HR Specialist',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_e',
    cycleCode: 'E',
    cycleColor: '#e11d48',
    isAppraisalMonthDue: false,
    managerId: 'emp_mgr_hr',
    managerName: 'Frank HR Manager',
    status: 'CLOSED',
    selfScore: 4.3,
    isSelfSubmitted: true,
    finalScore: 4.25,
    kraSnapshot: [
      { id: 'snap_kr_q4_1', kraId: 'kra_hr_appraisal', kraName: 'Appraisal & Performance Review Operations', targetSnapshot: '100% on-time execution', measurementCriteria: '1: <85% | 3: 95% | 5: 100%', weight: 40, achievement: '100% review cycle compliance achieved', rating: 4.5, comments: 'Zero missed deadlines across departments' },
      { id: 'snap_kr_q4_2', kraId: 'kra_hr_talent', kraName: 'Talent Acquisition SLA & Time-to-Hire', targetSnapshot: '< 30 days time-to-hire', measurementCriteria: '1: >45d | 3: 30d | 5: <22d', weight: 35, achievement: 'Reduced time-to-hire to 24 days', rating: 4.5, comments: 'Excellent coordination with hiring teams' },
      { id: 'snap_kr_q4_3', kraId: 'kra_hr_retention', kraName: 'Employee Retention & eNPS Engagement', targetSnapshot: 'eNPS >= 45', measurementCriteria: '1: <25 | 3: 45 | 5: >55', weight: 25, achievement: 'eNPS reached +51 in December survey', rating: 4, comments: 'Positive feedback on holiday event planning' },
    ],
    strengths: 'Process discipline and high engagement scores.',
    improvements: 'Lead HR analytics reporting for leadership meetings.',
    managerOverallComments: 'Consistently dependable and proactive.',
    isClosed: true,
    completedAt: '2026-01-12T14:30:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_karen',
    employeeId: 'emp_com_5',
    employeeCode: 'EMP-011',
    employeeName: 'Karen HR Spec',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources',
    designationName: 'HR Specialist',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_e',
    cycleCode: 'E',
    cycleColor: '#e11d48',
    isAppraisalMonthDue: true,
    managerId: 'emp_mgr_hr',
    managerName: 'Frank HR Manager',
    status: 'CLOSED',
    selfScore: 4.3,
    isSelfSubmitted: true,
    finalScore: 4.3,
    kraSnapshot: [
      { id: 'snap_kr_q1_1', kraId: 'kra_hr_appraisal', kraName: 'Appraisal & Performance Review Operations', targetSnapshot: '100% on-time execution', measurementCriteria: '1: <85% | 3: 95% | 5: 100%', weight: 40, achievement: 'Executed annual appraisal distribution', rating: 4.5, comments: 'Handled appraisal letters and acknowledgements seamlessly' },
      { id: 'snap_kr_q1_2', kraId: 'kra_hr_talent', kraName: 'Talent Acquisition SLA & Time-to-Hire', targetSnapshot: '< 30 days time-to-hire', measurementCriteria: '1: >45d | 3: 30d | 5: <22d', weight: 35, achievement: 'Maintained 25 day turnaround time', rating: 4, comments: 'Well-structured onboarding pipeline' },
      { id: 'snap_kr_q1_3', kraId: 'kra_hr_retention', kraName: 'Employee Retention & eNPS Engagement', targetSnapshot: 'eNPS >= 45', measurementCriteria: '1: <25 | 3: 45 | 5: >55', weight: 25, achievement: 'eNPS sustained at +50', rating: 4.5, comments: 'Employee pulse ratings consistently high' },
    ],
    strengths: 'Flawless execution of HR policies and appraisal letters.',
    improvements: 'Explore HR business partner growth path.',
    managerOverallComments: 'High-caliber HR specialist.',
    isClosed: true,
    completedAt: '2026-03-27T17:00:00.000Z',
    createdAt: '2026-01-01T09:00:00.000Z',
  },

  // ==========================================
  // DAVE ENG MANAGER (emp_mgr_eng) - Reports to Alice
  // ==========================================
  {
    id: 'rev_2025_q3_dave',
    employeeId: 'emp_mgr_eng',
    employeeCode: 'EMP-004',
    employeeName: 'Dave Eng Manager',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    designationName: 'Engineering Manager',
    reviewPeriodId: 'period_2025_q3',
    reviewPeriodName: '2025-Q3 (Jul - Sep)',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleColor: '#1e3a8a',
    isAppraisalMonthDue: false,
    managerId: 'emp_hod_eng',
    managerName: 'Alice Engineering HOD',
    status: 'CLOSED',
    selfScore: 4.4,
    isSelfSubmitted: true,
    finalScore: 4.4,
    kraSnapshot: [
      { id: 'snap_dv_q3_1', kraId: 'kra_eng_sprint', kraName: 'Engineering Delivery Cadence', targetSnapshot: 'Team sprint velocity > 90%', measurementCriteria: '1: <80% | 3: 90% | 5: >95%', weight: 40, achievement: 'Team delivered 94% of roadmap initiatives', rating: 4.5, comments: 'Strong managerial guidance and sprint balance' },
      { id: 'snap_dv_q3_2', kraId: 'kra_eng_quality', kraName: 'Service Reliability & Uptime', targetSnapshot: '99.9% uptime across production services', measurementCriteria: '1: <99% | 3: 99.5% | 5: 99.9%', weight: 35, achievement: 'Maintained 99.95% system availability', rating: 4.5, comments: 'Zero severe downtime incidents' },
      { id: 'snap_dv_q3_3', kraId: 'kra_eng_arch', kraName: 'People Development & Retention', targetSnapshot: 'Team attrition < 5%, 100% 1-on-1s', measurementCriteria: '1: >10% | 3: 5% | 5: 0%', weight: 25, achievement: 'Zero team attrition, weekly 1-on-1s logged', rating: 4, comments: 'High team morale and retention' },
    ],
    strengths: 'People leadership and technical clarity.',
    improvements: 'Engage more directly with product roadmap planning.',
    managerOverallComments: 'Effective manager driving high engineering throughput.',
    isClosed: true,
    completedAt: '2025-10-14T17:00:00.000Z',
    createdAt: '2025-07-01T09:00:00.000Z',
  },
  {
    id: 'rev_2025_q4_dave',
    employeeId: 'emp_mgr_eng',
    employeeCode: 'EMP-004',
    employeeName: 'Dave Eng Manager',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    designationName: 'Engineering Manager',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleColor: '#1e3a8a',
    isAppraisalMonthDue: false,
    managerId: 'emp_hod_eng',
    managerName: 'Alice Engineering HOD',
    status: 'CLOSED',
    selfScore: 4.5,
    isSelfSubmitted: true,
    finalScore: 4.5,
    kraSnapshot: [
      { id: 'snap_dv_q4_1', kraId: 'kra_eng_sprint', kraName: 'Engineering Delivery Cadence', targetSnapshot: 'Team sprint velocity > 90%', measurementCriteria: '1: <80% | 3: 90% | 5: >95%', weight: 40, achievement: 'Completed major platform release ahead of schedule', rating: 4.5, comments: 'Excellent coordination with QA and product teams' },
      { id: 'snap_dv_q4_2', kraId: 'kra_eng_quality', kraName: 'Service Reliability & Uptime', targetSnapshot: '99.9% uptime across production services', measurementCriteria: '1: <99% | 3: 99.5% | 5: 99.9%', weight: 35, achievement: 'Achieved 99.98% uptime during holiday traffic', rating: 5, comments: 'Proactive load testing paid off significantly' },
      { id: 'snap_dv_q4_3', kraId: 'kra_eng_arch', kraName: 'People Development & Retention', targetSnapshot: 'Team attrition < 5%, 100% 1-on-1s', measurementCriteria: '1: >10% | 3: 5% | 5: 0%', weight: 25, achievement: 'Successfully coached Grace to senior readiness', rating: 4.5, comments: 'Great talent development' },
    ],
    strengths: 'Operational rigor and steady leadership.',
    improvements: 'Lead cross-department architectural syncs.',
    managerOverallComments: 'Consistently strong performance across all managerial metrics.',
    isClosed: true,
    completedAt: '2026-01-16T15:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_dave',
    employeeId: 'emp_mgr_eng',
    employeeCode: 'EMP-004',
    employeeName: 'Dave Eng Manager',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    designationName: 'Engineering Manager',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleColor: '#1e3a8a',
    isAppraisalMonthDue: true,
    managerId: 'emp_hod_eng',
    managerName: 'Alice Engineering HOD',
    status: 'HR_PENDING',
    selfScore: 4.6,
    isSelfSubmitted: true,
    finalScore: 4.6,
    kraSnapshot: [
      { id: 'snap_dv_q1_1', kraId: 'kra_eng_sprint', kraName: 'Engineering Delivery Cadence', targetSnapshot: 'Team sprint velocity > 90%', measurementCriteria: '1: <80% | 3: 90% | 5: >95%', weight: 40, achievement: '96% on-time milestone delivery', rating: 4.5, comments: 'Very high delivery discipline' },
      { id: 'snap_dv_q1_2', kraId: 'kra_eng_quality', kraName: 'Service Reliability & Uptime', targetSnapshot: '99.9% uptime across production services', measurementCriteria: '1: <99% | 3: 99.5% | 5: 99.9%', weight: 35, achievement: 'Zero critical regressions', rating: 4.5, comments: 'Solid architectural standards' },
      { id: 'snap_dv_q1_3', kraId: 'kra_eng_arch', kraName: 'People Development & Retention', targetSnapshot: 'Team attrition < 5%, 100% 1-on-1s', measurementCriteria: '1: >10% | 3: 5% | 5: 0%', weight: 25, achievement: 'Completed all team quarterly reviews on time', rating: 5, comments: 'Exemplary people management' },
    ],
    strengths: 'Leadership maturity, architectural foresight.',
    improvements: 'Participate in engineering branding & conferences.',
    managerOverallComments: 'Alice Engineering HOD calibrated: Top-tier manager.',
    isClosed: false,
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-03-29T14:00:00.000Z',
  },

  // ==========================================
  // EVE SALES MANAGER (emp_mgr_sales) - Reports to Bob
  // ==========================================
  {
    id: 'rev_2025_q3_eve',
    employeeId: 'emp_mgr_sales',
    employeeCode: 'EMP-005',
    employeeName: 'Eve Sales Manager',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    designationName: 'Sales Manager',
    reviewPeriodId: 'period_2025_q3',
    reviewPeriodName: '2025-Q3 (Jul - Sep)',
    cycleId: 'cycle_c',
    cycleCode: 'C',
    cycleColor: '#059669',
    isAppraisalMonthDue: false,
    managerId: 'emp_hod_sales',
    managerName: 'Bob Sales HOD',
    status: 'CLOSED',
    selfScore: 4.1,
    isSelfSubmitted: true,
    finalScore: 4.1,
    kraSnapshot: [
      { id: 'snap_ev_q3_1', kraId: 'kra_sales_quota', kraName: 'Department Sales Quota Target', targetSnapshot: '100% cumulative sales quota', measurementCriteria: '1: <80% | 3: 100% | 5: >115%', weight: 50, achievement: 'Team reached 102% of Q3 aggregate sales quota', rating: 4, comments: 'Balanced team revenue contribution' },
      { id: 'snap_ev_q3_2', kraId: 'kra_sales_acquisition', kraName: 'Enterprise Pipeline Expansion', targetSnapshot: '$2.5M qualified pipeline generated', measurementCriteria: '1: <$1.5M | 3: $2.5M | 5: >$3M', weight: 30, achievement: 'Generated $2.8M in enterprise opportunities', rating: 4.5, comments: 'Strong outbound strategy' },
      { id: 'snap_ev_q3_3', kraId: 'kra_sales_crm', kraName: 'Rep Coaching & Retention', targetSnapshot: '100% bi-weekly deal coaching sessions', measurementCriteria: '1: <80% | 3: 95% | 5: 100%', weight: 20, achievement: 'All coaching sessions executed; active PIP coaching for Jack', rating: 4, comments: 'Good dedication to rep development' },
    ],
    strengths: 'Sales motivation and strategic account intervention.',
    improvements: 'Improve forecasting accuracy for mid-tier accounts.',
    managerOverallComments: 'Solid leadership over the sales unit.',
    isClosed: true,
    completedAt: '2025-10-15T16:00:00.000Z',
    createdAt: '2025-07-01T09:00:00.000Z',
  },
  {
    id: 'rev_2025_q4_eve',
    employeeId: 'emp_mgr_sales',
    employeeCode: 'EMP-005',
    employeeName: 'Eve Sales Manager',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    designationName: 'Sales Manager',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_c',
    cycleCode: 'C',
    cycleColor: '#059669',
    isAppraisalMonthDue: false,
    managerId: 'emp_hod_sales',
    managerName: 'Bob Sales HOD',
    status: 'CLOSED',
    selfScore: 4.2,
    isSelfSubmitted: true,
    finalScore: 4.2,
    kraSnapshot: [
      { id: 'snap_ev_q4_1', kraId: 'kra_sales_quota', kraName: 'Department Sales Quota Target', targetSnapshot: '100% cumulative sales quota', measurementCriteria: '1: <80% | 3: 100% | 5: >115%', weight: 50, achievement: 'Team finished at 106% of Q4 target', rating: 4.5, comments: 'Strong close led by Ivy' },
      { id: 'snap_ev_q4_2', kraId: 'kra_sales_acquisition', kraName: 'Enterprise Pipeline Expansion', targetSnapshot: '$2.5M qualified pipeline generated', measurementCriteria: '1: <$1.5M | 3: $2.5M | 5: >$3M', weight: 30, achievement: 'Generated $3.1M qualified pipeline for H1', rating: 4.5, comments: 'Robust pipeline into 2026' },
      { id: 'snap_ev_q4_3', kraId: 'kra_sales_crm', kraName: 'Rep Coaching & Retention', targetSnapshot: '100% bi-weekly deal coaching sessions', measurementCriteria: '1: <80% | 3: 95% | 5: 100%', weight: 20, achievement: 'Regular check-ins maintained with all reps', rating: 3.5, comments: 'Ongoing support provided to struggling accounts' },
    ],
    strengths: 'Executive deal closing, client relationships.',
    improvements: 'Increase conversion rates across junior reps.',
    managerOverallComments: 'Consistently delivers on quota commitments.',
    isClosed: true,
    completedAt: '2026-01-15T18:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_eve',
    employeeId: 'emp_mgr_sales',
    employeeCode: 'EMP-005',
    employeeName: 'Eve Sales Manager',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    designationName: 'Sales Manager',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_c',
    cycleCode: 'C',
    cycleColor: '#059669',
    isAppraisalMonthDue: true,
    managerId: 'emp_hod_sales',
    managerName: 'Bob Sales HOD',
    status: 'CLOSED',
    selfScore: 4.25,
    isSelfSubmitted: true,
    finalScore: 4.25,
    kraSnapshot: [
      { id: 'snap_ev_q1_1', kraId: 'kra_sales_quota', kraName: 'Department Sales Quota Target', targetSnapshot: '100% cumulative sales quota', measurementCriteria: '1: <80% | 3: 100% | 5: >115%', weight: 50, achievement: 'Finished Q1 at 104% quota', rating: 4.5, comments: 'Well-managed sales cycle' },
      { id: 'snap_ev_q1_2', kraId: 'kra_sales_acquisition', kraName: 'Enterprise Pipeline Expansion', targetSnapshot: '$2.5M qualified pipeline generated', measurementCriteria: '1: <$1.5M | 3: $2.5M | 5: >$3M', weight: 30, achievement: 'Added $2.6M pipeline', rating: 4, comments: 'Consistent enterprise interest' },
      { id: 'snap_ev_q1_3', kraId: 'kra_sales_crm', kraName: 'Rep Coaching & Retention', targetSnapshot: '100% bi-weekly deal coaching sessions', measurementCriteria: '1: <80% | 3: 95% | 5: 100%', weight: 20, achievement: 'Diligent PIP check-ins logged for Jack', rating: 4, comments: 'Very professional handling of performance management' },
    ],
    strengths: 'Accountable management, transparent forecasting.',
    improvements: 'Lead national sales summit presentation.',
    managerOverallComments: 'Recommended for merit increment by Bob Sales HOD.',
    isClosed: true,
    completedAt: '2026-03-30T16:00:00.000Z',
    createdAt: '2026-01-01T09:00:00.000Z',
  },

  // ==========================================
  // FRANK HR MANAGER (emp_mgr_hr) - Reports to Carol
  // ==========================================
  {
    id: 'rev_2025_q3_frank',
    employeeId: 'emp_mgr_hr',
    employeeCode: 'EMP-006',
    employeeName: 'Frank HR Manager',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources',
    designationName: 'HR Manager',
    reviewPeriodId: 'period_2025_q3',
    reviewPeriodName: '2025-Q3 (Jul - Sep)',
    cycleId: 'cycle_e',
    cycleCode: 'E',
    cycleColor: '#e11d48',
    isAppraisalMonthDue: false,
    managerId: 'emp_hod_hr',
    managerName: 'Carol HR HOD',
    status: 'CLOSED',
    selfScore: 4.2,
    isSelfSubmitted: true,
    finalScore: 4.2,
    kraSnapshot: [
      { id: 'snap_fr_q3_1', kraId: 'kra_hr_appraisal', kraName: 'Appraisal & Quarterly Review Operations', targetSnapshot: '100% on-time execution of review cohorts', measurementCriteria: '1: <80% | 3: 95-100% | 5: 100% on-time', weight: 40, achievement: '100% completion of Q3 reviews across all business units', rating: 4.5, comments: 'Seamless collaboration with HODs' },
      { id: 'snap_fr_q3_2', kraId: 'kra_hr_talent', kraName: 'Talent Acquisition & Time-to-Fill', targetSnapshot: 'Average time-to-hire < 30 days', measurementCriteria: '1: >45 days | 3: 25-30 days | 5: <20 days', weight: 35, achievement: 'Closed 6 key engineering and sales openings within 28 days', rating: 4, comments: 'High offer acceptance rate' },
      { id: 'snap_fr_q3_3', kraId: 'kra_hr_retention', kraName: 'Employee Engagement & Retention', targetSnapshot: 'eNPS ≥ +45, attrition rate < 8%', measurementCriteria: '1: <20 | 3: 40-45 | 5: >55', weight: 25, achievement: 'eNPS at +48, overall quarterly attrition 3.2%', rating: 4, comments: 'Strong employee sentiment' },
    ],
    strengths: 'Strategic HR planning, policy compliance, calm dispute resolution.',
    improvements: 'Streamline manager training for quarterly evaluations.',
    managerOverallComments: 'Very dependable HR manager.',
    isClosed: true,
    completedAt: '2025-10-15T15:00:00.000Z',
    createdAt: '2025-07-01T09:00:00.000Z',
  },
  {
    id: 'rev_2025_q4_frank',
    employeeId: 'emp_mgr_hr',
    employeeCode: 'EMP-006',
    employeeName: 'Frank HR Manager',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources',
    designationName: 'HR Manager',
    reviewPeriodId: 'period_2025_q4',
    reviewPeriodName: '2025-Q4 (Oct - Dec)',
    cycleId: 'cycle_e',
    cycleCode: 'E',
    cycleColor: '#e11d48',
    isAppraisalMonthDue: false,
    managerId: 'emp_hod_hr',
    managerName: 'Carol HR HOD',
    status: 'CLOSED',
    selfScore: 4.3,
    isSelfSubmitted: true,
    finalScore: 4.3,
    kraSnapshot: [
      { id: 'snap_fr_q4_1', kraId: 'kra_hr_appraisal', kraName: 'Appraisal & Quarterly Review Operations', targetSnapshot: '100% on-time execution of review cohorts', measurementCriteria: '1: <80% | 3: 95-100% | 5: 100% on-time', weight: 40, achievement: 'Completed year-end review rollouts with zero disputes', rating: 4.5, comments: 'Well prepared appraisal cycle' },
      { id: 'snap_fr_q4_2', kraId: 'kra_hr_talent', kraName: 'Talent Acquisition & Time-to-Fill', targetSnapshot: 'Average time-to-hire < 30 days', measurementCriteria: '1: >45 days | 3: 25-30 days | 5: <20 days', weight: 35, achievement: 'Filled critical leadership vacancies', rating: 4, comments: 'Solid executive recruitment' },
      { id: 'snap_fr_q4_3', kraId: 'kra_hr_retention', kraName: 'Employee Engagement & Retention', targetSnapshot: 'eNPS ≥ +45, attrition rate < 8%', measurementCriteria: '1: <20 | 3: 40-45 | 5: >55', weight: 25, achievement: 'Company-wide town hall with 95% positive feedback', rating: 4.5, comments: 'Strong leadership trust' },
    ],
    strengths: 'HR business partnering and leadership alignment.',
    improvements: 'Enhance data analytics reporting for executive board.',
    managerOverallComments: 'High-performing HR manager.',
    isClosed: true,
    completedAt: '2026-01-16T12:00:00.000Z',
    createdAt: '2025-10-01T09:00:00.000Z',
  },
  {
    id: 'rev_2026_q1_frank',
    employeeId: 'emp_mgr_hr',
    employeeCode: 'EMP-006',
    employeeName: 'Frank HR Manager',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources',
    designationName: 'HR Manager',
    reviewPeriodId: 'period_2026_q1',
    reviewPeriodName: '2026-Q1 (Jan - Mar)',
    cycleId: 'cycle_e',
    cycleCode: 'E',
    cycleColor: '#e11d48',
    isAppraisalMonthDue: true,
    managerId: 'emp_hod_hr',
    managerName: 'Carol HR HOD',
    status: 'CLOSED',
    selfScore: 4.35,
    isSelfSubmitted: true,
    finalScore: 4.35,
    kraSnapshot: [
      { id: 'snap_fr_q1_1', kraId: 'kra_hr_appraisal', kraName: 'Appraisal & Quarterly Review Operations', targetSnapshot: '100% on-time execution of review cohorts', measurementCriteria: '1: <80% | 3: 95-100% | 5: 100% on-time', weight: 40, achievement: '100% on-time calibration and appraisal letters issued', rating: 4.5, comments: 'Excellent execution' },
      { id: 'snap_fr_q1_2', kraId: 'kra_hr_talent', kraName: 'Talent Acquisition & Time-to-Fill', targetSnapshot: 'Average time-to-hire < 30 days', measurementCriteria: '1: >45 days | 3: 25-30 days | 5: <20 days', weight: 35, achievement: 'Supported Hiring Manager Leo in rapid staffing', rating: 4, comments: 'Well-aligned recruitment strategy' },
      { id: 'snap_fr_q1_3', kraId: 'kra_hr_retention', kraName: 'Employee Engagement & Retention', targetSnapshot: 'eNPS ≥ +45, attrition rate < 8%', measurementCriteria: '1: <20 | 3: 40-45 | 5: >55', weight: 25, achievement: 'eNPS +51 achieved', rating: 4.5, comments: 'High employee morale' },
    ],
    strengths: 'Executive credibility, thorough governance.',
    improvements: 'Expand leadership development programs.',
    managerOverallComments: 'Approved by Carol HR HOD.',
    isClosed: true,
    completedAt: '2026-03-30T17:30:00.000Z',
    createdAt: '2026-01-01T09:00:00.000Z',
  },
];
