import { AuditLogEntry, ComplianceFlag } from '../src/types.js';

export const SEED_PHASE8_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud_001',
    timestamp: '2026-09-01T08:15:22.000Z',
    actionType: 'KRA_TEMPLATE_MODIFIED',
    module: 'KRA_MANAGEMENT',
    severity: 'INFO',
    actorId: 'usr_hr_lead',
    actorName: 'Priya Sundaram',
    actorRole: 'HR',
    actorEmail: 'priya.sundaram@company.com',
    targetDepartment: 'Engineering & Technology',
    cycleName: 'Cycle F (September)',
    description: 'Updated Senior Full-Stack Engineer KRA template: Increased System Reliability SLA weight from 20% to 25%.',
    previousValue: { weight: 20, metric: '99.5% Uptime' },
    newValue: { weight: 25, metric: '99.9% Uptime' },
    diffSummary: 'Weight: 20% → 25%, Metric Target: 99.5% → 99.9%',
    ipAddress: '192.168.1.104',
    userAgent: 'Chrome 128 / macOS',
    isFlaggedCompliance: false,
  },
  {
    id: 'aud_002',
    timestamp: '2026-09-01T09:30:10.000Z',
    actionType: 'MANAGER_RATING_SUBMITTED',
    module: 'QUARTERLY_REVIEW',
    severity: 'INFO',
    actorId: 'usr_mgr_eng',
    actorName: 'Rajesh Kumar',
    actorRole: 'MANAGER',
    actorEmail: 'rajesh.kumar@company.com',
    targetEmployeeId: 'emp_dev_1',
    targetEmployeeName: 'Aarav Patel',
    targetDepartment: 'Engineering & Technology',
    cycleId: 'cycle_f',
    cycleName: 'Cycle F (September)',
    description: 'Submitted Q4 Performance Review for Aarav Patel with an aggregate score of 4.35 / 5.0.',
    previousValue: { q4Score: null, status: 'PENDING_MANAGER' },
    newValue: { q4Score: 4.35, status: 'SUBMITTED', managerNotes: 'Exceeded deliverables on microservices migration.' },
    diffSummary: 'Q4 Score: Unrated → 4.35 (Exceeds Expectations)',
    ipAddress: '192.168.1.112',
    userAgent: 'Firefox 129 / Windows',
    isFlaggedCompliance: false,
  },
  {
    id: 'aud_003',
    timestamp: '2026-09-01T11:45:00.000Z',
    actionType: 'HOD_CALIBRATION_OVERRIDE',
    module: 'CALIBRATION',
    severity: 'WARNING',
    actorId: 'usr_hod_eng',
    actorName: 'Vikram Mehta',
    actorRole: 'HOD',
    actorEmail: 'vikram.mehta@company.com',
    targetEmployeeId: 'emp_dev_2',
    targetEmployeeName: 'Rohan Gupta',
    targetDepartment: 'Engineering & Technology',
    cycleId: 'cycle_f',
    cycleName: 'Cycle F (September)',
    description: 'HOD adjusted annual normalized rating from 4.20 to 3.20 (-1.00 score delta) during departmental bell-curve calibration.',
    previousValue: { annualScore: 4.20, category: 'EXCEEDS_EXPECTATIONS', proposedIncrement: 14.0 },
    newValue: { annualScore: 3.20, category: 'MEETS_EXPECTATIONS', proposedIncrement: 7.5, justification: 'Major Q4 production incident on payment gateway not accounted for in manager draft evaluation.' },
    diffSummary: 'Rating: 4.20 → 3.20 (-1.00 delta) | Increment: 14.0% → 7.5%',
    ipAddress: '192.168.1.108',
    userAgent: 'Safari 17.5 / macOS',
    isFlaggedCompliance: true,
    metadata: { overrideDelta: -1.0, requiredEscalation: true },
  },
  {
    id: 'aud_004',
    timestamp: '2026-09-01T14:10:30.000Z',
    actionType: 'BUDGET_POOL_REALLOCATED',
    module: 'BUDGET_INCREMENT',
    severity: 'NOTICE',
    actorId: 'usr_super_admin',
    actorName: 'Arjun Singhania',
    actorRole: 'SUPER_ADMIN',
    actorEmail: 'admin@company.com',
    targetDepartment: 'Engineering & Technology',
    cycleId: 'cycle_f',
    cycleName: 'Cycle F (September)',
    description: 'Reallocated ₹1,50,000 from General Contingency Pool into Engineering Department Increment Pool to support critical retention.',
    previousValue: { budgetCap: 1250000 },
    newValue: { budgetCap: 1400000, reason: 'High market demand for senior backend skills.' },
    diffSummary: 'Budget Cap: ₹12.50L → ₹14.00L (+₹1.50L)',
    ipAddress: '10.0.0.1',
    userAgent: 'Chrome 128 / Linux',
    isFlaggedCompliance: false,
  },
  {
    id: 'aud_005',
    timestamp: '2026-09-01T15:20:00.000Z',
    actionType: 'PROMOTION_APPROVED',
    module: 'BUDGET_INCREMENT',
    severity: 'INFO',
    actorId: 'usr_hr_lead',
    actorName: 'Priya Sundaram',
    actorRole: 'HR',
    actorEmail: 'priya.sundaram@company.com',
    targetEmployeeId: 'emp_dev_1',
    targetEmployeeName: 'Aarav Patel',
    targetDepartment: 'Engineering & Technology',
    cycleId: 'cycle_f',
    cycleName: 'Cycle F (September)',
    description: 'Promotion approved: Software Engineer II promoted to Senior Software Engineer (Band L4).',
    previousValue: { designation: 'Software Engineer II', band: 'L3', ctc: 1450000 },
    newValue: { designation: 'Senior Software Engineer', band: 'L4', ctc: 1720000, incrementPercent: 18.6 },
    diffSummary: 'Designation: Software Engineer II → Senior Software Engineer | CTC: ₹14.50L → ₹17.20L (+18.6%)',
    ipAddress: '192.168.1.104',
    userAgent: 'Chrome 128 / macOS',
    isFlaggedCompliance: false,
  },
  {
    id: 'aud_006',
    timestamp: '2026-09-01T16:00:00.000Z',
    actionType: 'LETTER_GENERATED',
    module: 'LETTERS',
    severity: 'INFO',
    actorId: 'usr_hr_lead',
    actorName: 'Priya Sundaram',
    actorRole: 'HR',
    actorEmail: 'priya.sundaram@company.com',
    targetEmployeeId: 'emp_dev_1',
    targetEmployeeName: 'Aarav Patel',
    targetDepartment: 'Engineering & Technology',
    cycleId: 'cycle_f',
    cycleName: 'Cycle F (September)',
    description: 'Generated formal Digital Annual Appraisal & Increment Letter #AL-2026-CYF-001.',
    previousValue: { letterStatus: 'NONE' },
    newValue: { letterStatus: 'GENERATED', referenceNo: 'AL-2026-CYF-001', effectiveDate: '2026-10-01' },
    diffSummary: 'Letter generated with effective salary ₹17,20,000 p.a.',
    ipAddress: '192.168.1.104',
    userAgent: 'Chrome 128 / macOS',
    isFlaggedCompliance: false,
  },
  {
    id: 'aud_007',
    timestamp: '2026-09-01T17:45:15.000Z',
    actionType: 'LETTER_ACKNOWLEDGED',
    module: 'LETTERS',
    severity: 'INFO',
    actorId: 'emp_dev_1',
    actorName: 'Aarav Patel',
    actorRole: 'EMPLOYEE',
    actorEmail: 'aarav.patel@company.com',
    targetEmployeeId: 'emp_dev_1',
    targetEmployeeName: 'Aarav Patel',
    targetDepartment: 'Engineering & Technology',
    cycleId: 'cycle_f',
    cycleName: 'Cycle F (September)',
    description: 'Employee digitally reviewed, confirmed, and signed Annual Appraisal Letter #AL-2026-CYF-001.',
    previousValue: { acknowledged: false },
    newValue: { acknowledged: true, signatureDate: '2026-09-01T17:45:15.000Z', ipSignature: '49.36.128.45' },
    diffSummary: 'Digital Signature Recorded (Hash: a7f89b...e21) from IP 49.36.128.45',
    ipAddress: '49.36.128.45',
    userAgent: 'Safari 18.0 / iOS Mobile',
    isFlaggedCompliance: false,
  },
  {
    id: 'aud_008',
    timestamp: '2026-08-15T10:00:00.000Z',
    actionType: 'LETTER_PUBLISHED',
    module: 'LETTERS',
    severity: 'WARNING',
    actorId: 'usr_hr_lead',
    actorName: 'Priya Sundaram',
    actorRole: 'HR',
    actorEmail: 'priya.sundaram@company.com',
    targetEmployeeId: 'emp_sales_2',
    targetEmployeeName: 'Priya Iyer',
    targetDepartment: 'Sales & Business Development',
    cycleId: 'cycle_d',
    cycleName: 'Cycle D (July)',
    description: 'Published Annual Appraisal Letter #AL-2026-CYD-042 to employee portal. Overdue for signature (>18 days).',
    previousValue: { status: 'DRAFT' },
    newValue: { status: 'PUBLISHED_AWAITING_SIGNATURE' },
    diffSummary: 'Letter dispatched; employee acknowledgement pending for 18 days.',
    ipAddress: '192.168.1.104',
    userAgent: 'Chrome 128 / macOS',
    isFlaggedCompliance: true,
  },
  {
    id: 'aud_009',
    timestamp: '2026-09-02T02:10:00.000Z',
    actionType: 'BULK_DATA_IMPORTED',
    module: 'BULK_IMPORT',
    severity: 'INFO',
    actorId: 'usr_super_admin',
    actorName: 'Arjun Singhania',
    actorRole: 'SUPER_ADMIN',
    actorEmail: 'admin@company.com',
    description: 'Bulk Excel import executed: Batch #BATCH-2026-0902-8874 (48 employee records synced across Cycles A through H).',
    previousValue: { count: 120 },
    newValue: { count: 168, inserted: 24, updated: 24, errors: 0 },
    diffSummary: 'Inserted 24 records, Updated 24 existing records seamlessly.',
    ipAddress: '10.0.0.1',
    userAgent: 'Chrome 128 / Linux',
    isFlaggedCompliance: false,
  },
  {
    id: 'aud_010',
    timestamp: '2026-09-02T02:30:00.000Z',
    actionType: 'CYCLE_STAGE_CHANGED',
    module: 'CYCLE_ADMIN',
    severity: 'INFO',
    actorId: 'usr_hr_lead',
    actorName: 'Priya Sundaram',
    actorRole: 'HR',
    actorEmail: 'priya.sundaram@company.com',
    cycleId: 'cycle_f',
    cycleName: 'Cycle F (September)',
    description: 'Transitioned Cycle F stage from "HOD_CALIBRATION" to "HR_FINAL_APPROVAL".',
    previousValue: { stage: 'HOD_CALIBRATION' },
    newValue: { stage: 'HR_FINAL_APPROVAL' },
    diffSummary: 'Stage progressed: HOD Calibration → HR Final Approval',
    ipAddress: '192.168.1.104',
    userAgent: 'Chrome 128 / macOS',
    isFlaggedCompliance: false,
  }
];

export const SEED_COMPLIANCE_FLAGS: ComplianceFlag[] = [
  {
    id: 'flag_001',
    employeeId: 'emp_dev_2',
    employeeName: 'Rohan Gupta',
    department: 'Engineering & Technology',
    cycleId: 'cycle_f',
    flagType: 'LARGE_SCORE_OVERRIDE',
    severity: 'CRITICAL',
    title: 'High Calibration Score Discrepancy (-1.00 rating reduction)',
    description: 'HOD Vikram Mehta adjusted annual performance rating from 4.20 (Manager Rajesh Kumar) down to 3.20. Requires written justification and HR sign-off.',
    detectedAt: '2026-09-01T11:45:00.000Z',
    isResolved: false,
    impactMetric: 'Rating dropped from Top Tier (14% hike) to Core Tier (7.5% hike)',
  },
  {
    id: 'flag_002',
    employeeId: 'emp_sales_2',
    employeeName: 'Priya Iyer',
    department: 'Sales & Business Development',
    cycleId: 'cycle_d',
    flagType: 'UNACKNOWLEDGED_LETTER',
    severity: 'WARNING',
    title: 'Appraisal Letter Signature Overdue (>18 Days)',
    description: 'Appraisal letter #AL-2026-CYD-042 was published on August 15, 2026. The 14-day compliance grace period expired without employee acknowledgement.',
    detectedAt: '2026-08-30T00:00:00.000Z',
    isResolved: false,
    impactMetric: '18 days elapsed since letter dispatch',
  },
  {
    id: 'flag_003',
    employeeId: 'emp_mgr_sales',
    employeeName: 'Ananya Sharma',
    department: 'Sales & Business Development',
    cycleId: 'cycle_f',
    flagType: 'SUBMISSION_OVERDUE',
    severity: 'WARNING',
    title: 'Manager Evaluation Overdue for 2 Direct Reports',
    description: 'Q4 reviews for Sales Associate cohort were due on August 28, 2026. Submissions remain in pending state.',
    detectedAt: '2026-08-29T00:00:00.000Z',
    isResolved: false,
    impactMetric: '4 days past cycle review submission deadline',
  },
  {
    id: 'flag_004',
    employeeId: 'dept_sales',
    employeeName: 'Sales Department Pool',
    department: 'Sales & Business Development',
    cycleId: 'cycle_f',
    flagType: 'BUDGET_OVERRUN',
    severity: 'NOTICE',
    title: 'Preliminary Department Budget Threshold Exceeded (+₹45,000)',
    description: 'Proposed increment pool total for Cycle F reached ₹8,45,000 against allocated cap of ₹8,00,000 (+5.6% overrun).',
    detectedAt: '2026-08-31T16:00:00.000Z',
    isResolved: true,
    resolvedAt: '2026-09-01T10:00:00.000Z',
    resolvedBy: 'Arjun Singhania (Super Admin)',
    resolutionNote: 'Approved 6% contingency buffer adjustment based on H1 sales quota overachievement.',
    impactMetric: 'Overrun of ₹45,000 absorbed by executive reserve',
  },
  {
    id: 'flag_005',
    employeeId: 'tmpl_product_01',
    employeeName: 'Product Design KRA Template',
    department: 'Product & Design',
    cycleId: 'cycle_a',
    flagType: 'INSUFFICIENT_KRA_WEIGHT',
    severity: 'NOTICE',
    title: 'Draft KRA Template Weight Sum Incomplete (90%)',
    description: 'Template for Senior UI/UX Designer held 3 KRAs totaling 90% instead of mandatory 100% mathematical weight.',
    detectedAt: '2026-08-20T11:00:00.000Z',
    isResolved: true,
    resolvedAt: '2026-08-20T14:30:00.000Z',
    resolvedBy: 'Priya Sundaram (HR)',
    resolutionNote: 'Adjusted Design System Consistency KPI weight from 20% to 30% to complete 100% total.',
    impactMetric: 'Corrected to exactly 100% weight allocation',
  }
];
