import {
  Appraisal,
  Notification,
  AuditLog,
  FeedbackEntry,
  PipRecord,
  TalentRecord,
} from '../src/types.js';

export const SEED_APPRAISALS: Appraisal[] = [
  // ==========================================
  // GRACE ENGINEER (emp_com_1) - Promotion Recommended
  // ==========================================
  {
    id: 'app_2026_grace',
    employeeId: 'emp_com_1',
    employeeCode: 'EMP-007',
    employeeName: 'Grace Engineer',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    designationId: 'des_eng_emp',
    designationName: 'Software Engineer',
    managerId: 'emp_mgr_eng',
    managerName: 'Dave Eng Manager',
    hodId: 'emp_hod_eng',
    hodName: 'Alice Engineering HOD',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleName: 'Cycle A (Jan)',
    cycleColor: '#1e3a8a',
    appraisalYear: 2026,
    appraisalMonth: 1,
    currentCtc: 1500000,
    currency: '₹',
    quarterlyHistory: [
      { periodId: 'period_2025_q2', periodName: '2025-Q2', score: 4.45 },
      { periodId: 'period_2025_q3', periodName: '2025-Q3 (Jul - Sep)', score: 4.50 },
      { periodId: 'period_2025_q4', periodName: '2025-Q4 (Oct - Dec)', score: 4.65 },
      { periodId: 'period_2026_q1', periodName: '2026-Q1 (Jan - Mar)', score: 4.70 },
    ],
    averageQuarterlyScore: 4.58,
    recommendedRating: 'OUTSTANDING',
    suggestedIncrementMin: 15.0,
    suggestedIncrementMax: 18.0,
    finalRating: 'OUTSTANDING',
    proposedIncrementPercentage: 16.5,
    approvedIncrementPercentage: 16.5,
    incrementAmount: 247500,
    revisedCtc: 1747500,
    promotionRecommended: true,
    promotionDesignationId: 'des_eng_sr',
    promotionDesignationName: 'Senior Software Engineer',
    status: 'HOD_CALIBRATED',
    isLocked: false,
    managerRecommendation: {
      suggestedIncrementPercent: 16.5,
      promotionRecommended: true,
      promotionDesignationId: 'des_eng_sr',
      promotionDesignationName: 'Senior Software Engineer',
      justification: 'Grace has consistently outperformed expectations, architecting critical platform components and demonstrating senior engineering maturity.',
      recommendedBy: 'emp_mgr_eng',
      recommendedByName: 'Dave Eng Manager',
      recommendedAt: '2026-03-26T11:00:00.000Z',
    },
    hodCalibration: {
      calibratedIncrementPercent: 16.5,
      promotionApproved: true,
      calibratedRating: 'OUTSTANDING',
      notes: 'Calibrated and fully endorsed. Grace is among our top 5% talent across the engineering department.',
      calibratedBy: 'emp_hod_eng',
      calibratedByName: 'Alice Engineering HOD',
      calibratedAt: '2026-03-28T14:00:00.000Z',
    },
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-03-28T14:00:00.000Z',
  },

  // ==========================================
  // HANK ENGINEER (emp_com_2) - Solid Performer
  // ==========================================
  {
    id: 'app_2026_hank',
    employeeId: 'emp_com_2',
    employeeCode: 'EMP-008',
    employeeName: 'Hank Engineer',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    designationId: 'des_eng_emp',
    designationName: 'Software Engineer',
    managerId: 'emp_mgr_eng',
    managerName: 'Dave Eng Manager',
    hodId: 'emp_hod_eng',
    hodName: 'Alice Engineering HOD',
    cycleId: 'cycle_b',
    cycleCode: 'B',
    cycleName: 'Cycle B (Feb)',
    cycleColor: '#0d9488',
    appraisalYear: 2026,
    appraisalMonth: 2,
    currentCtc: 1400000,
    currency: '₹',
    quarterlyHistory: [
      { periodId: 'period_2025_q2', periodName: '2025-Q2', score: 3.70 },
      { periodId: 'period_2025_q3', periodName: '2025-Q3 (Jul - Sep)', score: 3.75 },
      { periodId: 'period_2025_q4', periodName: '2025-Q4 (Oct - Dec)', score: 3.85 },
      { periodId: 'period_2026_q1', periodName: '2026-Q1 (Jan - Mar)', score: 3.90 },
    ],
    averageQuarterlyScore: 3.80,
    recommendedRating: 'EXCEEDS_EXPECTATIONS',
    suggestedIncrementMin: 10.0,
    suggestedIncrementMax: 13.0,
    finalRating: 'EXCEEDS_EXPECTATIONS',
    proposedIncrementPercentage: 11.0,
    approvedIncrementPercentage: 11.0,
    incrementAmount: 154000,
    revisedCtc: 1554000,
    promotionRecommended: false,
    status: 'MANAGER_RECOMMENDED',
    isLocked: false,
    managerRecommendation: {
      suggestedIncrementPercent: 11.0,
      promotionRecommended: false,
      justification: 'Hank is a dependable engineer showing strong upward progress across quarters. Recommended for standard merit band.',
      recommendedBy: 'emp_mgr_eng',
      recommendedByName: 'Dave Eng Manager',
      recommendedAt: '2026-03-25T16:00:00.000Z',
    },
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-03-25T16:00:00.000Z',
  },

  // ==========================================
  // IVY SALES REP (emp_com_3) - HR Approved / Promotion
  // ==========================================
  {
    id: 'app_2026_ivy',
    employeeId: 'emp_com_3',
    employeeCode: 'EMP-009',
    employeeName: 'Ivy Sales Rep',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    designationId: 'des_sales_emp',
    designationName: 'Sales Representative',
    managerId: 'emp_mgr_sales',
    managerName: 'Eve Sales Manager',
    hodId: 'emp_hod_sales',
    hodName: 'Bob Sales HOD',
    cycleId: 'cycle_c',
    cycleCode: 'C',
    cycleName: 'Cycle C (Apr)',
    cycleColor: '#059669',
    appraisalYear: 2026,
    appraisalMonth: 4,
    currentCtc: 1200000,
    currency: '₹',
    quarterlyHistory: [
      { periodId: 'period_2025_q2', periodName: '2025-Q2', score: 4.20 },
      { periodId: 'period_2025_q3', periodName: '2025-Q3 (Jul - Sep)', score: 4.30 },
      { periodId: 'period_2025_q4', periodName: '2025-Q4 (Oct - Dec)', score: 4.45 },
      { periodId: 'period_2026_q1', periodName: '2026-Q1 (Jan - Mar)', score: 4.55 },
    ],
    averageQuarterlyScore: 4.38,
    recommendedRating: 'OUTSTANDING',
    suggestedIncrementMin: 12.0,
    suggestedIncrementMax: 15.0,
    finalRating: 'OUTSTANDING',
    proposedIncrementPercentage: 14.0,
    approvedIncrementPercentage: 14.0,
    incrementAmount: 168000,
    revisedCtc: 1368000,
    promotionRecommended: true,
    promotionDesignationId: 'des_sales_sr',
    promotionDesignationName: 'Senior Sales Representative',
    status: 'HR_APPROVED',
    isLocked: false,
    managerRecommendation: {
      suggestedIncrementPercent: 14.0,
      promotionRecommended: true,
      promotionDesignationId: 'des_sales_sr',
      promotionDesignationName: 'Senior Sales Representative',
      justification: 'Top sales producer with 118% annual quota attainment. Outstanding client relationship management.',
      recommendedBy: 'emp_mgr_sales',
      recommendedByName: 'Eve Sales Manager',
      recommendedAt: '2026-03-24T12:00:00.000Z',
    },
    hodCalibration: {
      calibratedIncrementPercent: 14.0,
      promotionApproved: true,
      calibratedRating: 'OUTSTANDING',
      notes: 'Endorsed. Ivy has closed the two largest enterprise accounts this fiscal year.',
      calibratedBy: 'emp_hod_sales',
      calibratedByName: 'Bob Sales HOD',
      calibratedAt: '2026-03-26T15:00:00.000Z',
    },
    hrApproval: {
      finalIncrementPercent: 14.0,
      finalRating: 'OUTSTANDING',
      revisedCtc: 1368000,
      effectiveDate: '2026-04-01',
      letterGenerated: true,
      letterGeneratedAt: '2026-03-28T17:00:00.000Z',
      notes: 'Approved within departmental sales pool budget.',
      approvedBy: 'usr_mgr_hr',
      approvedByName: 'Frank HR Manager',
      approvedAt: '2026-03-28T17:00:00.000Z',
    },
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-03-28T17:00:00.000Z',
  },

  // ==========================================
  // JACK SALES REP (emp_com_4) - Needs Improvement / PENDING
  // ==========================================
  {
    id: 'app_2026_jack',
    employeeId: 'emp_com_4',
    employeeCode: 'EMP-010',
    employeeName: 'Jack Sales Rep',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    designationId: 'des_sales_emp',
    designationName: 'Sales Representative',
    managerId: 'emp_mgr_sales',
    managerName: 'Eve Sales Manager',
    hodId: 'emp_hod_sales',
    hodName: 'Bob Sales HOD',
    cycleId: 'cycle_d',
    cycleCode: 'D',
    cycleName: 'Cycle D (May)',
    cycleColor: '#7c3aed',
    appraisalYear: 2026,
    appraisalMonth: 5,
    currentCtc: 1100000,
    currency: '₹',
    quarterlyHistory: [
      { periodId: 'period_2025_q2', periodName: '2025-Q2', score: 2.80 },
      { periodId: 'period_2025_q3', periodName: '2025-Q3 (Jul - Sep)', score: 2.80 },
      { periodId: 'period_2025_q4', periodName: '2025-Q4 (Oct - Dec)', score: 2.70 },
      { periodId: 'period_2026_q1', periodName: '2026-Q1 (Jan - Mar)', score: 2.60 },
    ],
    averageQuarterlyScore: 2.72,
    recommendedRating: 'NEEDS_IMPROVEMENT',
    suggestedIncrementMin: 0.0,
    suggestedIncrementMax: 3.0,
    finalRating: 'NEEDS_IMPROVEMENT',
    proposedIncrementPercentage: 2.0,
    approvedIncrementPercentage: 0.0,
    incrementAmount: 0,
    revisedCtc: 1100000,
    promotionRecommended: false,
    status: 'PENDING',
    remarks: 'Under active 60-day Performance Improvement Plan. Increment deferred pending PIP completion.',
    isLocked: false,
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-03-20T10:00:00.000Z',
  },

  // ==========================================
  // KAREN HR SPEC (emp_com_5) - Locked & Letter Acknowledged
  // ==========================================
  {
    id: 'app_2026_karen',
    employeeId: 'emp_com_5',
    employeeCode: 'EMP-011',
    employeeName: 'Karen HR Spec',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources',
    designationId: 'des_hr_emp',
    designationName: 'HR Specialist',
    managerId: 'emp_mgr_hr',
    managerName: 'Frank HR Manager',
    hodId: 'emp_hod_hr',
    hodName: 'Carol HR HOD',
    cycleId: 'cycle_e',
    cycleCode: 'E',
    cycleName: 'Cycle E (Jul)',
    cycleColor: '#e11d48',
    appraisalYear: 2026,
    appraisalMonth: 7,
    currentCtc: 1000000,
    currency: '₹',
    quarterlyHistory: [
      { periodId: 'period_2025_q2', periodName: '2025-Q2', score: 4.00 },
      { periodId: 'period_2025_q3', periodName: '2025-Q3 (Jul - Sep)', score: 4.10 },
      { periodId: 'period_2025_q4', periodName: '2025-Q4 (Oct - Dec)', score: 4.25 },
      { periodId: 'period_2026_q1', periodName: '2026-Q1 (Jan - Mar)', score: 4.30 },
    ],
    averageQuarterlyScore: 4.16,
    recommendedRating: 'EXCEEDS_EXPECTATIONS',
    suggestedIncrementMin: 10.0,
    suggestedIncrementMax: 13.0,
    finalRating: 'EXCEEDS_EXPECTATIONS',
    proposedIncrementPercentage: 12.0,
    approvedIncrementPercentage: 12.0,
    incrementAmount: 120000,
    revisedCtc: 1120000,
    promotionRecommended: false,
    status: 'LOCKED',
    isLocked: true,
    lockedAt: '2026-03-27T10:00:00.000Z',
    managerRecommendation: {
      suggestedIncrementPercent: 12.0,
      promotionRecommended: false,
      justification: 'Karen has delivered stellar HR operations and perfect review compliance.',
      recommendedBy: 'emp_mgr_hr',
      recommendedByName: 'Frank HR Manager',
      recommendedAt: '2026-03-20T10:00:00.000Z',
    },
    hodCalibration: {
      calibratedIncrementPercent: 12.0,
      promotionApproved: false,
      calibratedRating: 'EXCEEDS_EXPECTATIONS',
      notes: 'Calibrated and approved within HR budget.',
      calibratedBy: 'emp_hod_hr',
      calibratedByName: 'Carol HR HOD',
      calibratedAt: '2026-03-22T14:00:00.000Z',
    },
    hrApproval: {
      finalIncrementPercent: 12.0,
      finalRating: 'EXCEEDS_EXPECTATIONS',
      revisedCtc: 1120000,
      effectiveDate: '2026-04-01',
      letterGenerated: true,
      letterGeneratedAt: '2026-03-26T09:00:00.000Z',
      notes: 'Approved and official appraisal letter generated.',
      approvedBy: 'usr_mgr_hr',
      approvedByName: 'Frank HR Manager',
      approvedAt: '2026-03-25T11:00:00.000Z',
    },
    employeeAcknowledgement: {
      acknowledged: true,
      acknowledgedAt: '2026-03-27T10:00:00.000Z',
      acknowledgedBy: 'emp_com_5',
      acknowledgedByName: 'Karen HR Spec',
      comments: 'Thank you for the encouragement and recognition. Looking forward to achieving higher milestones in 2026.',
    },
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-03-27T10:00:00.000Z',
  },

  // ==========================================
  // DAVE ENG MANAGER (emp_mgr_eng) - HOD Calibrated
  // ==========================================
  {
    id: 'app_2026_dave',
    employeeId: 'emp_mgr_eng',
    employeeCode: 'EMP-004',
    employeeName: 'Dave Eng Manager',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    designationId: 'des_eng_mgr',
    designationName: 'Engineering Manager',
    managerId: 'emp_hod_eng',
    managerName: 'Alice Engineering HOD',
    hodId: 'emp_hod_eng',
    hodName: 'Alice Engineering HOD',
    cycleId: 'cycle_a',
    cycleCode: 'A',
    cycleName: 'Cycle A (Jan)',
    cycleColor: '#1e3a8a',
    appraisalYear: 2026,
    appraisalMonth: 1,
    currentCtc: 2400000,
    currency: '₹',
    quarterlyHistory: [
      { periodId: 'period_2025_q2', periodName: '2025-Q2', score: 4.35 },
      { periodId: 'period_2025_q3', periodName: '2025-Q3 (Jul - Sep)', score: 4.40 },
      { periodId: 'period_2025_q4', periodName: '2025-Q4 (Oct - Dec)', score: 4.50 },
      { periodId: 'period_2026_q1', periodName: '2026-Q1 (Jan - Mar)', score: 4.60 },
    ],
    averageQuarterlyScore: 4.46,
    recommendedRating: 'OUTSTANDING',
    suggestedIncrementMin: 14.0,
    suggestedIncrementMax: 17.0,
    finalRating: 'OUTSTANDING',
    proposedIncrementPercentage: 15.0,
    approvedIncrementPercentage: 15.0,
    incrementAmount: 360000,
    revisedCtc: 2760000,
    promotionRecommended: false,
    status: 'HOD_CALIBRATED',
    isLocked: false,
    managerRecommendation: {
      suggestedIncrementPercent: 15.0,
      promotionRecommended: false,
      justification: 'Exceptional engineering leadership, team retention, and zero Sev-1 outages.',
      recommendedBy: 'emp_hod_eng',
      recommendedByName: 'Alice Engineering HOD',
      recommendedAt: '2026-03-25T11:00:00.000Z',
    },
    hodCalibration: {
      calibratedIncrementPercent: 15.0,
      promotionApproved: false,
      calibratedRating: 'OUTSTANDING',
      notes: 'Recommended for Senior Engineering Manager track in the upcoming cycle.',
      calibratedBy: 'emp_hod_eng',
      calibratedByName: 'Alice Engineering HOD',
      calibratedAt: '2026-03-27T16:00:00.000Z',
    },
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-03-27T16:00:00.000Z',
  },

  // ==========================================
  // EVE SALES MANAGER (emp_mgr_sales) - HR Approved
  // ==========================================
  {
    id: 'app_2026_eve',
    employeeId: 'emp_mgr_sales',
    employeeCode: 'EMP-005',
    employeeName: 'Eve Sales Manager',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    designationId: 'des_sales_mgr',
    designationName: 'Sales Manager',
    managerId: 'emp_hod_sales',
    managerName: 'Bob Sales HOD',
    hodId: 'emp_hod_sales',
    hodName: 'Bob Sales HOD',
    cycleId: 'cycle_c',
    cycleCode: 'C',
    cycleName: 'Cycle C (Apr)',
    cycleColor: '#059669',
    appraisalYear: 2026,
    appraisalMonth: 4,
    currentCtc: 2200000,
    currency: '₹',
    quarterlyHistory: [
      { periodId: 'period_2025_q2', periodName: '2025-Q2', score: 4.05 },
      { periodId: 'period_2025_q3', periodName: '2025-Q3 (Jul - Sep)', score: 4.10 },
      { periodId: 'period_2025_q4', periodName: '2025-Q4 (Oct - Dec)', score: 4.20 },
      { periodId: 'period_2026_q1', periodName: '2026-Q1 (Jan - Mar)', score: 4.25 },
    ],
    averageQuarterlyScore: 4.15,
    recommendedRating: 'EXCEEDS_EXPECTATIONS',
    suggestedIncrementMin: 10.0,
    suggestedIncrementMax: 13.0,
    finalRating: 'EXCEEDS_EXPECTATIONS',
    proposedIncrementPercentage: 11.5,
    approvedIncrementPercentage: 11.5,
    incrementAmount: 253000,
    revisedCtc: 2453000,
    promotionRecommended: false,
    status: 'HR_APPROVED',
    isLocked: false,
    managerRecommendation: {
      suggestedIncrementPercent: 11.5,
      promotionRecommended: false,
      justification: 'Led team to 105% of cumulative sales quota target.',
      recommendedBy: 'emp_hod_sales',
      recommendedByName: 'Bob Sales HOD',
      recommendedAt: '2026-03-24T15:00:00.000Z',
    },
    hodCalibration: {
      calibratedIncrementPercent: 11.5,
      promotionApproved: false,
      calibratedRating: 'EXCEEDS_EXPECTATIONS',
      notes: 'Calibrated and approved.',
      calibratedBy: 'emp_hod_sales',
      calibratedByName: 'Bob Sales HOD',
      calibratedAt: '2026-03-26T14:00:00.000Z',
    },
    hrApproval: {
      finalIncrementPercent: 11.5,
      finalRating: 'EXCEEDS_EXPECTATIONS',
      revisedCtc: 2453000,
      effectiveDate: '2026-04-01',
      letterGenerated: true,
      letterGeneratedAt: '2026-03-29T10:00:00.000Z',
      notes: 'Approved within budget.',
      approvedBy: 'usr_mgr_hr',
      approvedByName: 'Frank HR Manager',
      approvedAt: '2026-03-29T10:00:00.000Z',
    },
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-03-29T10:00:00.000Z',
  },

  // ==========================================
  // FRANK HR MANAGER (emp_mgr_hr) - HR Approved
  // ==========================================
  {
    id: 'app_2026_frank',
    employeeId: 'emp_mgr_hr',
    employeeCode: 'EMP-006',
    employeeName: 'Frank HR Manager',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources',
    designationId: 'des_hr_mgr',
    designationName: 'HR Manager',
    managerId: 'emp_hod_hr',
    managerName: 'Carol HR HOD',
    hodId: 'emp_hod_hr',
    hodName: 'Carol HR HOD',
    cycleId: 'cycle_e',
    cycleCode: 'E',
    cycleName: 'Cycle E (Jul)',
    cycleColor: '#e11d48',
    appraisalYear: 2026,
    appraisalMonth: 7,
    currentCtc: 2000000,
    currency: '₹',
    quarterlyHistory: [
      { periodId: 'period_2025_q2', periodName: '2025-Q2', score: 4.15 },
      { periodId: 'period_2025_q3', periodName: '2025-Q3 (Jul - Sep)', score: 4.20 },
      { periodId: 'period_2025_q4', periodName: '2025-Q4 (Oct - Dec)', score: 4.30 },
      { periodId: 'period_2026_q1', periodName: '2026-Q1 (Jan - Mar)', score: 4.35 },
    ],
    averageQuarterlyScore: 4.25,
    recommendedRating: 'EXCEEDS_EXPECTATIONS',
    suggestedIncrementMin: 10.0,
    suggestedIncrementMax: 13.0,
    finalRating: 'EXCEEDS_EXPECTATIONS',
    proposedIncrementPercentage: 12.0,
    approvedIncrementPercentage: 12.0,
    incrementAmount: 240000,
    revisedCtc: 2240000,
    promotionRecommended: false,
    status: 'HR_APPROVED',
    isLocked: false,
    managerRecommendation: {
      suggestedIncrementPercent: 12.0,
      promotionRecommended: false,
      justification: 'Superb operational rigor across company appraisals and people policies.',
      recommendedBy: 'emp_hod_hr',
      recommendedByName: 'Carol HR HOD',
      recommendedAt: '2026-03-25T14:00:00.000Z',
    },
    hodCalibration: {
      calibratedIncrementPercent: 12.0,
      promotionApproved: false,
      calibratedRating: 'EXCEEDS_EXPECTATIONS',
      notes: 'Fully endorsed.',
      calibratedBy: 'emp_hod_hr',
      calibratedByName: 'Carol HR HOD',
      calibratedAt: '2026-03-27T11:00:00.000Z',
    },
    hrApproval: {
      finalIncrementPercent: 12.0,
      finalRating: 'EXCEEDS_EXPECTATIONS',
      revisedCtc: 2240000,
      effectiveDate: '2026-04-01',
      letterGenerated: true,
      letterGeneratedAt: '2026-03-29T15:00:00.000Z',
      notes: 'Approved.',
      approvedBy: 'usr_mgr_hr',
      approvedByName: 'HR Executive Committee',
      approvedAt: '2026-03-29T15:00:00.000Z',
    },
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-03-29T15:00:00.000Z',
  },
];

export const SEED_NOTIFICATIONS: Notification[] = [
  // Super Admin
  {
    id: 'notif_sa_1',
    userId: 'usr_sa',
    userRole: 'SUPER_ADMIN',
    type: 'CALIBRATION_WARNING',
    title: 'Cycle A Appraisal Calibration Active',
    message: 'Engineering & Sales departments have completed initial manager evaluations. HOD calibrations are in progress across 8 cohort cycles.',
    isRead: false,
    priority: 'HIGH',
    createdAt: '2026-03-28T10:00:00.000Z',
    metadata: { cycleId: 'cycle_a', activeSection: 'bellCurveAnalytics' },
  },
  {
    id: 'notif_sa_2',
    userId: 'usr_sa',
    userRole: 'SUPER_ADMIN',
    type: 'BUDGET_ALERT',
    title: 'Company Increment Budget Headroom: 78% Allocated',
    message: 'Corporate budget pool utilization is currently at 78.4% of authorized envelope with 2 departments pending sign-off.',
    isRead: false,
    priority: 'MEDIUM',
    createdAt: '2026-03-28T11:30:00.000Z',
    metadata: { cycleId: 'cycle_a', activeSection: 'budgetPool' },
  },

  // Executive Management
  {
    id: 'notif_mgmt_1',
    userId: 'usr_mgmt_persona',
    userRole: 'MANAGEMENT',
    type: 'CALIBRATION_WARNING',
    title: 'Executive Sign-Off Pending: 2026 Cycle A Appraisal Cohort',
    message: 'Engineering and Sales departmental calibration distributions and promotion quotas are ready for executive review and sign-off.',
    isRead: false,
    priority: 'HIGH',
    createdAt: '2026-03-28T13:00:00.000Z',
    metadata: { cycleId: 'cycle_a', activeSection: 'bellCurveAnalytics' },
  },
  {
    id: 'notif_mgmt_2',
    userId: 'usr_mgmt_persona',
    userRole: 'MANAGEMENT',
    type: 'BUDGET_ALERT',
    title: 'Department Budget Pool Review: Sales & Engineering',
    message: 'Departmental budget allocations are tracking within guidelines. Total proposed increment spend is ₹9.8L against ₹12.5L pool.',
    isRead: false,
    priority: 'MEDIUM',
    createdAt: '2026-03-28T14:00:00.000Z',
    metadata: { cycleId: 'cycle_a', activeSection: 'budgetPool' },
  },

  // HR Manager (Frank HR Manager)
  {
    id: 'notif_hr_1',
    userId: 'usr_mgr_hr',
    userRole: 'HR',
    type: 'HOD_ACTION_REQUIRED',
    title: 'Appraisal Recommendations Pending HR Approval',
    message: 'Alice Engineering HOD and Bob Sales HOD have calibrated appraisals for Grace Engineer and Ivy Sales Rep. Ready for final approval.',
    isRead: false,
    priority: 'HIGH',
    createdAt: '2026-03-28T14:30:00.000Z',
    metadata: { cycleId: 'cycle_a', activeSection: 'appraisals', status: 'HOD_CALIBRATED' },
  },
  {
    id: 'notif_hr_2',
    userId: 'usr_mgr_hr',
    userRole: 'HR',
    type: 'MANAGER_SUBMITTED',
    title: 'Quarterly Review Submissions Ready for Audit',
    message: 'Manager evaluations submitted for 2026-Q1 cycle. Review distribution curves and complete HR audit sign-off.',
    isRead: false,
    priority: 'MEDIUM',
    createdAt: '2026-03-27T16:00:00.000Z',
    metadata: { periodId: 'period_2026_q1', status: 'MANAGER_COMPLETED' },
  },
  {
    id: 'notif_hr_3',
    userId: 'usr_mgr_hr',
    userRole: 'HR',
    type: 'LETTER_ACKNOWLEDGED',
    title: 'Appraisal Letter Acknowledged: Karen HR Spec',
    message: 'Karen HR Spec has digitally signed and acknowledged the 2026 annual revision letter with a 12% increment.',
    isRead: true,
    priority: 'LOW',
    createdAt: '2026-03-26T15:00:00.000Z',
    metadata: { appraisalId: 'app_2026_karen', cycleId: 'cycle_e', activeSection: 'appraisals' },
  },

  // HOD Engineering (Alice Engineering HOD)
  {
    id: 'notif_hod_eng_1',
    userId: 'usr_hod_eng',
    userRole: 'HOD',
    type: 'HOD_ACTION_REQUIRED',
    title: 'Manager Appraisal Submitted: Grace Engineer',
    message: 'Dave Eng Manager recommended Outstanding (16.5% increment) and promotion to Senior Software Engineer for Grace Engineer.',
    isRead: false,
    priority: 'HIGH',
    createdAt: '2026-03-26T12:00:00.000Z',
    metadata: { appraisalId: 'app_2026_grace', cycleId: 'cycle_a', activeSection: 'appraisals' },
  },
  {
    id: 'notif_hod_eng_2',
    userId: 'usr_hod_eng',
    userRole: 'HOD',
    type: 'BUDGET_ALERT',
    title: 'Engineering Budget Pool Utilization: 82%',
    message: 'Engineering department increment proposals total ₹4.85L against authorized pool of ₹5.90L. 2 slots remaining.',
    isRead: false,
    priority: 'MEDIUM',
    createdAt: '2026-03-27T09:30:00.000Z',
    metadata: { cycleId: 'cycle_a', departmentId: 'dept_eng', activeSection: 'budgetPool' },
  },

  // HOD Sales (Bob Sales HOD)
  {
    id: 'notif_hod_sales_1',
    userId: 'usr_hod_sales',
    userRole: 'HOD',
    type: 'HOD_ACTION_REQUIRED',
    title: 'Manager Appraisal Submitted: Ivy Sales Rep',
    message: 'Eve Sales Manager recommended Exceeds Expectations (15.0% increment) for Ivy Sales Rep in Cycle C.',
    isRead: false,
    priority: 'HIGH',
    createdAt: '2026-03-27T10:00:00.000Z',
    metadata: { appraisalId: 'app_2026_ivy', cycleId: 'cycle_c', activeSection: 'appraisals' },
  },

  // HOD HR (Carol HR HOD)
  {
    id: 'notif_hod_hr_1',
    userId: 'usr_hod_hr',
    userRole: 'HOD',
    type: 'HOD_ACTION_REQUIRED',
    title: 'HR Department Appraisal Review: Frank HR Manager',
    message: 'Annual performance calibration and letter preparation for Frank HR Manager is pending HOD sign-off.',
    isRead: false,
    priority: 'MEDIUM',
    createdAt: '2026-03-27T11:00:00.000Z',
    metadata: { appraisalId: 'app_2026_frank', cycleId: 'cycle_e', activeSection: 'appraisals' },
  },

  // Manager Engineering (Dave Eng Manager)
  {
    id: 'notif_mgr_eng_1',
    userId: 'usr_mgr_eng',
    userRole: 'MANAGER',
    type: 'REVIEW_ASSIGNED',
    title: 'Q1 Review: Hank Engineer Self-Assessment Submitted',
    message: 'Hank Engineer has completed and submitted his 2026-Q1 self-assessment. Manager rating is now due.',
    isRead: false,
    priority: 'HIGH',
    createdAt: '2026-03-25T09:00:00.000Z',
    metadata: { periodId: 'period_2026_q1', status: 'MANAGER_PENDING' },
  },
  {
    id: 'notif_mgr_eng_2',
    userId: 'usr_mgr_eng',
    userRole: 'MANAGER',
    type: 'APPRAISAL_DUE',
    title: 'Cycle A Appraisal Recommendation: Grace Engineer',
    message: 'Annual appraisal recommendation and increment proposal is open for team member Grace Engineer.',
    isRead: false,
    priority: 'MEDIUM',
    createdAt: '2026-03-26T10:00:00.000Z',
    metadata: { appraisalId: 'app_2026_grace', cycleId: 'cycle_a', activeSection: 'appraisals' },
  },

  // Manager Sales (Eve Sales Manager)
  {
    id: 'notif_mgr_sales_1',
    userId: 'usr_mgr_sales',
    userRole: 'MANAGER',
    type: 'DUE_SOON',
    title: 'Bi-Weekly PIP Check-in Due: Jack Sales Rep',
    message: 'Week 4 milestone review and goal progression check-in for Jack Sales Rep is due on April 2nd.',
    isRead: false,
    priority: 'HIGH',
    createdAt: '2026-03-29T11:00:00.000Z',
    metadata: { activeSection: 'pipTracker' },
  },
  {
    id: 'notif_mgr_sales_2',
    userId: 'usr_mgr_sales',
    userRole: 'MANAGER',
    type: 'APPRAISAL_DUE',
    title: 'Cycle C Appraisal Recommendation: Ivy Sales Rep',
    message: 'Annual appraisal window open. Submit performance rating and increment recommendation for Ivy Sales Rep.',
    isRead: false,
    priority: 'MEDIUM',
    createdAt: '2026-03-27T08:30:00.000Z',
    metadata: { appraisalId: 'app_2026_ivy', cycleId: 'cycle_c', activeSection: 'appraisals' },
  },

  // Employees
  {
    id: 'notif_emp_grace_1',
    userId: 'usr_emp_1',
    userRole: 'EMPLOYEE',
    type: 'LETTER_RELEASED',
    title: 'Q1 Performance Review Submitted by Manager',
    message: 'Your Q1 performance evaluation has been reviewed by Dave Eng Manager and forwarded to HR.',
    isRead: false,
    priority: 'MEDIUM',
    createdAt: '2026-03-28T10:00:00.000Z',
    metadata: { periodId: 'period_2026_q1', subTab: 'reviews' },
  },
  {
    id: 'notif_emp_grace_2',
    userId: 'usr_emp_1',
    userRole: 'EMPLOYEE',
    type: 'APPRAISAL_DUE',
    title: '2026 Annual Appraisal Rollup Active',
    message: 'Cycle A annual appraisal rollup is active. Your manager recommendation has been submitted.',
    isRead: false,
    priority: 'HIGH',
    createdAt: '2026-03-28T12:00:00.000Z',
    metadata: { cycleId: 'cycle_a', subTab: 'appraisal' },
  },
  {
    id: 'notif_emp_hank_1',
    userId: 'usr_emp_2',
    userRole: 'EMPLOYEE',
    type: 'REVIEW_ASSIGNED',
    title: 'Q1 Self-Assessment Pending Submission',
    message: 'Your 2026-Q1 self-assessment is open. Please review your KRAs and submit your ratings.',
    isRead: false,
    priority: 'HIGH',
    createdAt: '2026-03-25T08:00:00.000Z',
    metadata: { periodId: 'period_2026_q1', subTab: 'reviews' },
  },
  {
    id: 'notif_emp_ivy_1',
    userId: 'usr_emp_3',
    userRole: 'EMPLOYEE',
    type: 'LETTER_RELEASED',
    title: 'Cycle C Appraisal In Progress',
    message: 'Eve Sales Manager has submitted your annual appraisal recommendation. Official letter release expected shortly.',
    isRead: false,
    priority: 'MEDIUM',
    createdAt: '2026-03-27T10:30:00.000Z',
    metadata: { cycleId: 'cycle_c', subTab: 'appraisal' },
  },
  {
    id: 'notif_emp_jack_1',
    userId: 'usr_emp_4',
    userRole: 'EMPLOYEE',
    type: 'DUE_SOON',
    title: 'Bi-Weekly PIP Goal Progress Check-in',
    message: 'Scheduled check-in meeting with Eve Sales Manager on Sales Pipeline Generation KRAs.',
    isRead: false,
    priority: 'HIGH',
    createdAt: '2026-03-29T10:00:00.000Z',
    metadata: { subTab: 'pip' },
  },
  {
    id: 'notif_emp_karen_1',
    userId: 'usr_emp_5',
    userRole: 'EMPLOYEE',
    type: 'LETTER_ACKNOWLEDGED',
    title: '2026 Annual Increment Letter Published',
    message: 'Your annual revision letter has been officially approved and locked with a 12% increment. Digital copy is available in your portal.',
    isRead: false,
    priority: 'HIGH',
    createdAt: '2026-03-26T12:00:00.000Z',
    metadata: { appraisalId: 'app_2026_karen', cycleId: 'cycle_e', subTab: 'appraisal' },
  },
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_001',
    userId: 'usr_sa',
    userName: 'System Admin',
    userRole: 'SUPER_ADMIN',
    module: 'KRA_MANAGEMENT',
    action: 'KRA_TEMPLATE_CREATED',
    recordId: 'tmpl_eng_ic',
    details: 'Created Software Engineer Standard Template with 3 weighted KRAs.',
    createdAt: '2025-01-01T10:00:00.000Z',
  },
  {
    id: 'aud_002',
    userId: 'usr_mgr_eng',
    userName: 'Dave Eng Manager',
    userRole: 'MANAGER',
    module: 'QUARTERLY_REVIEW',
    action: 'MANAGER_RATING_SUBMITTED',
    recordId: 'rev_2025_q3_grace',
    details: 'Submitted Q3 review rating 4.50 for Grace Engineer.',
    createdAt: '2025-10-14T14:30:00.000Z',
  },
  {
    id: 'aud_003',
    userId: 'usr_mgr_sales',
    userName: 'Eve Sales Manager',
    userRole: 'MANAGER',
    module: 'PIP_MANAGEMENT',
    action: 'PIP_INITIATED',
    recordId: 'pip_jack_sales',
    details: 'Initiated 60-day Performance Improvement Plan for Jack Sales Rep.',
    createdAt: '2026-01-19T09:00:00.000Z',
  },
  {
    id: 'aud_004',
    userId: 'usr_hod_eng',
    userName: 'Alice Engineering HOD',
    userRole: 'HOD',
    module: 'APPRAISALS',
    action: 'HOD_CALIBRATION_OVERRIDE',
    recordId: 'app_2026_grace',
    details: 'Endorsed 16.5% increment and promotion to Senior Software Engineer for Grace Engineer.',
    createdAt: '2026-03-28T14:00:00.000Z',
  },
  {
    id: 'aud_005',
    userId: 'usr_mgr_hr',
    userName: 'Frank HR Manager',
    userRole: 'HR',
    module: 'APPRAISALS',
    action: 'LETTER_PUBLISHED',
    recordId: 'app_2026_karen',
    details: 'Generated and published 2026 Annual Appraisal letter for Karen HR Spec.',
    createdAt: '2026-03-26T10:00:00.000Z',
  },
  {
    id: 'aud_006',
    userId: 'usr_emp_5',
    userName: 'Karen HR Spec',
    userRole: 'EMPLOYEE',
    module: 'APPRAISALS',
    action: 'LETTER_ACKNOWLEDGED',
    recordId: 'app_2026_karen',
    details: 'Employee digitally signed and acknowledged annual increment letter.',
    createdAt: '2026-03-27T10:00:00.000Z',
  },
];

export const SEED_FEEDBACK: FeedbackEntry[] = [
  {
    id: 'fb_1',
    fromUserId: 'emp_mgr_eng',
    fromUserName: 'Dave Eng Manager',
    fromUserRole: 'MANAGER',
    fromDepartment: 'Engineering',
    toEmployeeId: 'emp_com_1',
    toEmployeeName: 'Grace Engineer',
    toDepartment: 'Engineering',
    type: 'kudos',
    badgeCategory: 'technical_excellence',
    message: 'Grace did phenomenal work refactoring our core authentication pipeline with zero production regressions!',
    linkedKraTitle: 'System Architecture & Performance',
    quarter: 'Q1',
    cycleId: 'cycle_a',
    isPublic: true,
    likesCount: 5,
    likedBy: ['usr_sa', 'usr_hod_eng', 'usr_emp_2', 'usr_mgr_eng', 'usr_mgr_hr'],
    createdAt: '2026-03-15T10:00:00.000Z',
  },
  {
    id: 'fb_2',
    fromUserId: 'emp_com_1',
    fromUserName: 'Grace Engineer',
    fromUserRole: 'EMPLOYEE',
    fromDepartment: 'Engineering',
    toEmployeeId: 'emp_com_2',
    toEmployeeName: 'Hank Engineer',
    toDepartment: 'Engineering',
    type: 'kudos',
    badgeCategory: 'team_collaboration',
    message: 'Big shoutout to Hank for jumping in during the weekend database migration and ensuring smooth backup verifications.',
    linkedKraTitle: 'Code Quality & Reliability',
    quarter: 'Q1',
    cycleId: 'cycle_a',
    isPublic: true,
    likesCount: 3,
    likedBy: ['usr_mgr_eng', 'usr_emp_1', 'usr_hod_eng'],
    createdAt: '2026-03-18T14:20:00.000Z',
  },
  {
    id: 'fb_3',
    fromUserId: 'emp_mgr_sales',
    fromUserName: 'Eve Sales Manager',
    fromUserRole: 'MANAGER',
    fromDepartment: 'Sales',
    toEmployeeId: 'emp_com_3',
    toEmployeeName: 'Ivy Sales Rep',
    toDepartment: 'Sales',
    type: 'kudos',
    badgeCategory: 'customer_first',
    message: 'Ivy successfully closed our premier tier enterprise customer with glowing feedback on her consultative solution presentation!',
    linkedKraTitle: 'Enterprise Logo Acquisition',
    quarter: 'Q1',
    cycleId: 'cycle_a',
    isPublic: true,
    likesCount: 4,
    likedBy: ['usr_hod_sales', 'usr_mgr_sales', 'usr_sa', 'usr_mgr_hr'],
    createdAt: '2026-03-21T11:00:00.000Z',
  },
  {
    id: 'fb_4',
    fromUserId: 'emp_hod_hr',
    fromUserName: 'Carol HR HOD',
    fromUserRole: 'HOD',
    fromDepartment: 'Human Resources',
    toEmployeeId: 'emp_com_5',
    toEmployeeName: 'Karen HR Spec',
    toDepartment: 'Human Resources',
    type: 'kudos',
    badgeCategory: 'speed_execution',
    message: 'Karen coordinated our annual appraisal logistics and letter generation with absolute precision and on-time delivery.',
    linkedKraTitle: 'Appraisal & Performance Review Operations',
    quarter: 'Q1',
    cycleId: 'cycle_a',
    isPublic: true,
    likesCount: 6,
    likedBy: ['usr_mgr_hr', 'usr_hod_eng', 'usr_sa', 'usr_emp_1'],
    createdAt: '2026-03-27T09:30:00.000Z',
  },
];

export const SEED_PIPS: PipRecord[] = [
  {
    id: 'pip_jack_sales',
    employeeId: 'emp_com_4',
    employeeName: 'Jack Sales Rep',
    employeeCode: 'EMP-010',
    department: 'Sales',
    designation: 'Sales Representative',
    managerId: 'emp_mgr_sales',
    managerName: 'Eve Sales Manager',
    startDate: '2026-02-01',
    targetEndDate: '2026-04-01',
    durationDays: 60,
    status: 'active',
    overallProgress: 50,
    cycleNumber: 1,
    signatures: {
      managerSign: {
        signedBy: 'Eve Sales Manager',
        signedAt: '2026-02-01T10:00:00.000Z',
        role: 'MANAGER',
        comments: 'Plan initiated with agreed quarterly sales performance objectives.'
      },
      employeeAck: {
        signedBy: 'Jack Sales Rep',
        signedAt: '2026-02-02T11:00:00.000Z',
        role: 'EMPLOYEE',
        comments: 'Acknowledged requirements and milestone schedule.'
      }
    },
    coreGaps: [
      'Shortfall in qualified outbound sales pipeline volume',
      'Lower than benchmark deal conversion rate in enterprise discovery calls',
      'Inconsistent CRM deal stage updates and revenue forecasting',
    ],
    milestones: [
      {
        id: 'ms_1',
        title: 'Outbound Prospecting Cadence',
        targetMetric: 'Generate 40 verified qualified sales conversations per month',
        dueDate: '2026-02-28',
        status: 'met',
        notes: 'Target achieved with 42 conversations completed in February.',
      },
      {
        id: 'ms_2',
        title: 'Deal Qualification & Pipeline Hygiene',
        targetMetric: 'Maintain 100% compliant CRM pipeline stages and logs',
        dueDate: '2026-03-15',
        status: 'met',
        notes: 'Significant improvement in CRM data quality.',
      },
      {
        id: 'ms_3',
        title: 'Enterprise Deal Closures',
        targetMetric: 'Close at least 3 new customer accounts before April 1st',
        dueDate: '2026-04-01',
        status: 'in_progress',
        notes: '2 deals closed to date; 3rd deal in final contract stage.',
      },
    ],
    checkins: [
      {
        id: 'chk_1',
        date: '2026-02-15',
        weekNumber: 2,
        managerNotes: 'Reviewed outreach scripts and objection handling. Good engagement from Jack.',
        ratingOutOf5: 3.0,
        actionItems: 'Focus on multi-threading key prospect accounts.',
        employeeComments: 'Feeling clearer about target account personas.',
      },
      {
        id: 'chk_2',
        date: '2026-03-01',
        weekNumber: 4,
        managerNotes: 'Outbound volume hit target. Working on executive pitch confidence.',
        ratingOutOf5: 3.5,
        actionItems: 'Shadow Eve on two enterprise pricing calls.',
        employeeComments: 'Observing manager demos was very helpful.',
      },
      {
        id: 'chk_3',
        date: '2026-03-15',
        weekNumber: 6,
        managerNotes: 'CRM data is clean. Closing focus needed on the remaining open opportunities.',
        ratingOutOf5: 3.5,
        actionItems: 'Finalize contracts for 2 enterprise accounts in negotiation.',
        employeeComments: 'Determined to close the 3rd deal before quarter deadline.',
      },
    ],
    createdAt: '2026-01-25T10:00:00.000Z',
    updatedAt: '2026-03-15T11:00:00.000Z',
  },
];

export const SEED_TALENT_RECORDS: TalentRecord[] = [
  {
    id: 'tal_grace',
    employeeId: 'emp_com_1',
    employeeName: 'Grace Engineer',
    employeeCode: 'EMP-007',
    department: 'Engineering',
    designation: 'Software Engineer',
    currentScore: 4.60,
    performanceLevel: 'high',
    potentialLevel: 'high',
    nineBoxCategory: 'star_leader',
    flightRisk: 'low',
    riskFactors: ['Competitive market demand for senior full-stack architects'],
    recommendedActions: ['Promote to Senior Software Engineer', 'Assign technical architecture ownership for Q3 platform initiatives'],
    successionReady: true,
    targetNextRole: 'Senior Software Engineer / Tech Lead',
    lastAssessedDate: '2026-03-28',
  },
  {
    id: 'tal_hank',
    employeeId: 'emp_com_2',
    employeeName: 'Hank Engineer',
    employeeCode: 'EMP-008',
    department: 'Engineering',
    designation: 'Software Engineer',
    currentScore: 3.80,
    performanceLevel: 'medium',
    potentialLevel: 'medium',
    nineBoxCategory: 'core_contributor',
    flightRisk: 'low',
    riskFactors: [],
    recommendedActions: ['Provide advanced cloud architecture certification support', 'Encourage proactive technical documentation'],
    successionReady: false,
    lastAssessedDate: '2026-03-25',
  },
  {
    id: 'tal_ivy',
    employeeId: 'emp_com_3',
    employeeName: 'Ivy Sales Rep',
    employeeCode: 'EMP-009',
    department: 'Sales',
    designation: 'Sales Representative',
    currentScore: 4.40,
    performanceLevel: 'high',
    potentialLevel: 'high',
    nineBoxCategory: 'star_leader',
    flightRisk: 'low',
    riskFactors: ['High headhunter interest for enterprise sales reps'],
    recommendedActions: ['Promote to Senior Sales Representative', 'Allocate top enterprise target territory for 2026'],
    successionReady: true,
    targetNextRole: 'Senior Sales Representative / Enterprise Account Executive',
    lastAssessedDate: '2026-03-26',
  },
  {
    id: 'tal_jack',
    employeeId: 'emp_com_4',
    employeeName: 'Jack Sales Rep',
    employeeCode: 'EMP-010',
    department: 'Sales',
    designation: 'Sales Representative',
    currentScore: 2.70,
    performanceLevel: 'low',
    potentialLevel: 'low',
    nineBoxCategory: 'talent_risk',
    flightRisk: 'medium',
    riskFactors: ['Struggling with pipeline quota targets', 'Currently under 60-day PIP monitoring'],
    recommendedActions: ['Continue bi-weekly PIP coaching sessions', 'Assess milestone completion by April 1st'],
    successionReady: false,
    lastAssessedDate: '2026-03-15',
  },
  {
    id: 'tal_karen',
    employeeId: 'emp_com_5',
    employeeName: 'Karen HR Spec',
    employeeCode: 'EMP-011',
    department: 'Human Resources',
    designation: 'HR Specialist',
    currentScore: 4.20,
    performanceLevel: 'high',
    potentialLevel: 'medium',
    nineBoxCategory: 'key_asset',
    flightRisk: 'low',
    riskFactors: [],
    recommendedActions: ['Broaden HR business partner responsibilities', 'Involve in compensation and benefits planning'],
    successionReady: true,
    targetNextRole: 'Senior HR Specialist / HR Business Partner',
    lastAssessedDate: '2026-03-27',
  },
  {
    id: 'tal_dave',
    employeeId: 'emp_mgr_eng',
    employeeName: 'Dave Eng Manager',
    employeeCode: 'EMP-004',
    department: 'Engineering',
    designation: 'Engineering Manager',
    currentScore: 4.50,
    performanceLevel: 'high',
    potentialLevel: 'high',
    nineBoxCategory: 'star_leader',
    flightRisk: 'low',
    riskFactors: [],
    recommendedActions: ['Sponsor for Executive Engineering Leadership track', 'Shadow Alice Engineering HOD for department budget planning'],
    successionReady: true,
    targetNextRole: 'Director of Engineering',
    lastAssessedDate: '2026-03-27',
  },
  {
    id: 'tal_eve',
    employeeId: 'emp_mgr_sales',
    employeeName: 'Eve Sales Manager',
    employeeCode: 'EMP-005',
    department: 'Sales',
    designation: 'Sales Manager',
    currentScore: 4.20,
    performanceLevel: 'high',
    potentialLevel: 'medium',
    nineBoxCategory: 'key_asset',
    flightRisk: 'low',
    riskFactors: [],
    recommendedActions: ['Lead strategic enterprise sales enablement program'],
    successionReady: true,
    targetNextRole: 'Regional Sales Director',
    lastAssessedDate: '2026-03-26',
  },
  {
    id: 'tal_frank',
    employeeId: 'emp_mgr_hr',
    employeeName: 'Frank HR Manager',
    employeeCode: 'EMP-006',
    department: 'Human Resources',
    designation: 'HR Manager',
    currentScore: 4.30,
    performanceLevel: 'high',
    potentialLevel: 'medium',
    nineBoxCategory: 'key_asset',
    flightRisk: 'low',
    riskFactors: [],
    recommendedActions: ['Direct corporate people strategy and executive compensation'],
    successionReady: true,
    targetNextRole: 'Director of People Operations',
    lastAssessedDate: '2026-03-27',
  },
];
